### ISSUE TITLE
Load Averages maximum limited to 1.0

### ISSUE THREAD

**Issue by ptoal** [hexparrot/mineos-node#107]
Multicore machines frequently go over a load-average of 1.0.  The Graph in mineos-node is fixed at a max value of 1.0 in the y-axis.  It should auto-adjust, either to the number of cores, or to the most recent max-value.

**Comment by hexparrot** [comment]
Fixed today with commit: 85c04f12f6c7556ef47a374e21ae362c91fa6c13
