### ISSUE TITLE
Server broadcast across LAN doesn't work with multiple IPs

### ISSUE THREAD

**Issue by Zsub** [hexparrot/mineos-node#110]
I have multiple servers running on one machine, but each server is bound to its own IP with the default port. (For background, I used hostnames to make this girlfriend-friendly, she and I found those easier to remember than ports.) Now I'm trying to bring it to the next level with MineOS and I noticed it has a broadcast-function which is really cool.

However, it doesn't work. That is to say, it works for one server because all my servers share the same port. Furthermore, even if I change the ports to non-default, but also bind the servers to different IPs, only one server (the one bound to the same IP as the broadcaster is using) will actually work (even though all three show up in the client).

I can work around this by giving all servers the same IP, but I was wondering if there might be a more robust solution to this, for example by binding the broadcaster socket to other IPs such as may exist in the `server.properties` for all servers.

**Comment by Zsub** [comment]
A little testing reveals that binding the broadcasting UDP socket to different IPs would indeed work. I have manually set a server's IP on line 41 of `server.js` and now all servers show up with that IP:

    udp_broadcaster.bind(41234, "10.0.0.10"); \\ just took a random port number

I'm not sure what would be a good place to create those sockets, or if it is better to use a single socket and `bind()` and `close()` it, I have very little experience with nodeJS =/

**Comment by Zsub** [comment]
I can write a proposal and make a PR, would that be helpful in regard of the 'help wanted' tag? :)

**Comment by hexparrot** [comment]
@Zsub Indeed.  Understand though that the vast, vast, vast majority of people actually are served quite well with 255.255.255.255 because they're using UDP broadcast for a local network--networks which are very simply...just their LAN.  So any design improvements has to keep that in mind.

**Comment by Zsub** [comment]
Yeah I have the same situation, except that my servers vary by IP (on one physical host) and not port. So I won't change the UDP destination, just bind the socket so it comes from different origin addresses varying by which addresses on the host are used by the Minecraft servers.

I'm sure the PR will make it perfectly clear, even if I don't manage to express it very clearly in words 😁

**Comment by flareofghast** [comment]
So basically you're looking at creating one broadcaster per server, each one for a different ip. Presumably opening and closing would use less resources but I doubt they really use that much any way.

**Comment by flareofghast** [comment]
Are you able to use addMembership with each ip you wish to use?

**Comment by Zsub** [comment]
I do not think so, the intention is not to join several multicast addresses, just to sent to the same multicast address using multiple source addresses. On an unrelated note, my head is spinning from all the `callback`s and `async`s :P

**Comment by flareofghast** [comment]
Ahh, I misunderstood what the documentation was saying.

**Comment by hexparrot** [comment]
resolved with #112. Thank you both for your efforts!
