### ISSUE TITLE
Hidden Passwords - Bug & Feature Request

### ISSUE THREAD

**Issue by ptoal** [hexparrot/mineos-node#114]
Hi,

First off, clicking the "Hide password" option appears to have no effect for me.

Second,
I have read the "Stop Password Masking" document, and I humbly offer that it does not apply to this use-case.

I use a password manager, and never have to actually type in my password.  Having the password masked prevents casual observers (like my children) from getting my password.

I would like to request a configuration setting which allows the operator to decide whether or not password masking is default-enabled.  While I understand that password-masking makes some UI's more difficult to use, there are many cases where it really does enhance security, and I think server owners should be given the option to decide.

**Comment by Mortalife** [comment]
A compromise of keeping the feature but defaulting it to hide the password, maybe? So it still works to prevent casual observers but you are also able to view your password if you are having difficulties.

**Comment by ptoal** [comment]
I have no issue leaving the feature.  I just don't believe that the basic premise (that obscuring passwords doesn't add any security) is flawed, especially for people like me that use password managers.

Having an option to reveal the password is, IMO, the right choice.

If I was really concerned about security, I'd add a OTP option to the site.  But that would impede usability even more than obscuring the password. :)

**Comment by ciak2009** [comment]
I would :+1: this, the mere presence of the option is a no brainer allowing each user to chose based on their convictions.

**Comment by lasercar** [comment]
There's a small problem: the browser isn't offering to save the password, I assume because it's `<input type="text">` instead of `<input type="password">`.

**Comment by hexparrot** [comment]
In commit cc4dac5b5ea1a31de85291fccb74032d32a72386, a new variable introduced to easily toggle between the default state.  Change `MASK_PASSWORD = false` to `true` and passwords will be hidden by default.
