### ISSUE TITLE
Cant create a new server

### ISSUE THREAD

**Issue by MrBretze** [hexparrot/mineos-node#117]
I update mineOS the lastest version and I cant create a new server.

**Comment by thesymbol** [comment]
I can not confirm this on bfc577893a596f879e7bcf44143d37b49d038233
working fine on my side. have you checked that your /var/games/minecraft (and directories in there) have correct permissions? (usually that is causing this type of issue).

**Comment by MrBretze** [comment]
@thesymbol The directory "Test" is create and the user and group is the same of the creator user, the server is not listed :/

**Comment by MrBretze** [comment]
I fix this a reintall mineOS (just delete the git and re-clone the git)
