### ISSUE TITLE
Incompatible with nodejs 4.0.0

### ISSUE THREAD

**Issue by KayoticSully** [hexparrot/mineos-node#122]
This probably isn't news, but figured I would report it as a bit of a PSA.  I just upgraded to node v4 by accident in my routine pacman -Syu.  For other reasons I need to reinstall MineOS so I re-cloned the repo and my npm install blew up.

This isn't really an issue with MineOS exactly but I'm guessing many of its dependencies are not compatible with Node v4.0.0 yet.  I'm also guessing that this should resolve its self as Node v4 was just released today or so.

I reverted back a version and everything works fine.  I think mostly time will fix this.  But until the dependencies get fixed I'm not sure how to check if MineOS will be compatible either.

**Comment by hexparrot** [comment]
Some modules have been updated already, but others, like `crypt` (used in FreeBSD) and `socket.io` (pretty much the whole thing) aren't yet building right for me.  I'll be keeping tabs.

**Comment by hexparrot** [comment]
Have it working on nodev4, but it won't work on FreeBSD, which depends on the `crypt3` module that has not yet been updated.

**Comment by hexparrot** [comment]
pulled in #131, which works on nodev4 (linux)
