### ISSUE TITLE
Spigot profile not build

### ISSUE THREAD

**Issue by MrBretze** [hexparrot/mineos-node#125]
I downloaded the latest version of BuildTools.jar and I run this: http://puu.sh/kgN8T/cdc8952844.png

**Comment by hexparrot** [comment]
Likely you're experiencing the problem from this issue:

https://github.com/KayoticSully/mineos-node/commit/88670614e8b84380cf40f2f3a4712ff112a2ed56

The solution is copying over the updated systemd_conf:

`cp /usr/games/minecraft/init/systemd_conf /etc/systemd/system/mineos.service`

You may have to restart the mineos service (restarting the full host would also accomplish this).

**Comment by MrBretze** [comment]
Its fixed, thanks
