### ISSUE TITLE
All servers disappeared after a reboot.

### ISSUE THREAD

**Issue by yesiateyoursheep** [hexparrot/mineos-node#133]
I'm pretty sure this was an error awhile ago, but it still hasn't been fixed for me, I copied some servers over from MineOS 1 to MineOS 2 without error after upgrading my debian based mineos server to mineos 2 via a fresh install, but a vanilla server that I then created didn't show up, so I tried rebooting to no avail. Now none of the servers appear.
![screenshot-192 168 1 101 8443 2015-10-04 14-28-54](https://cloud.githubusercontent.com/assets/7791524/10266007/b2a9f6a2-6aa4-11e5-91bb-f835fe750a3d.png)
Also, I don't have a git commit number;
![screenshot-192 168 1 101 8443 2015-10-04 14-32-31](https://cloud.githubusercontent.com/assets/7791524/10266008/c3f86484-6aa4-11e5-8d8d-00ec3c3da4ae.png)
I've moved all but the primary server (named "creative") to the serversold folder in order to try and fix it, but it makes no difference.
![capture](https://cloud.githubusercontent.com/assets/7791524/10266059/6cbf65b6-6aa7-11e5-8af3-6f072c3886ab.PNG)
![capture](https://cloud.githubusercontent.com/assets/7791524/10266060/8f186bf8-6aa7-11e5-94ce-7a86cecd1070.PNG)
My server (named creative) has no server.config file. And creating a new server named "creative" does nothing as well.

**Comment by hexparrot** [comment]
What does your /var/log/mineos.say?

Also, does your /var/games/minecraft/servers/creative contain a `server.properties` file?

**Comment by yesiateyoursheep** [comment]
After upgrading node.js to 4.0 using the top answer (by eballeste) <a href="http://askubuntu.com/questions/426750/how-can-i-update-my-nodejs-to-the-latest-version">here</a>, mineos crashes whenever I log in. Here is the log after attempting to get mineos to run 3 times; <a href="http://pastebin.com/wmvy6TUf">[JSON] mineos.log - Pastebin.com</a>

**Comment by hexparrot** [comment]
Something looks wrong with your `server.config` files.  Are they present or somehow not working?  The error logs suggest an issue trying to read values from the file, so you might try deleting the server.config file and letting it get regenerated (and then re-modifying any values you need to)

**Comment by hexparrot** [comment]
I've found the most straightforward way to update node to be from source node:

http://minecraft.codeemo.com/mineoswiki/index.php?title=MineOS-node_(apt-get)#node_4.0

**Comment by yesiateyoursheep** [comment]
server.config was already missing, I tried creating a blank server.config file, but no difference. Installing node via that method stopped it from crashing, but creating a server still doesn't work, no folder is created and the webui refuses to open it. New log; <a href="http://pastebin.com/sDjV9mRV">mineos.log</a>

**Comment by hexparrot** [comment]
Alright, so I'm not sure what happened there;  server.config never should have been missing, but the webui had marked it as having existed at one point (which it surely did).  

Regardless of how it got deleted, the webui should handle it better and I made a commit that should handle it: 4c9ae0e4976cc7b2ed276073be1a2f4feb6a68dd

Now, regardless of whether that file is deleted unintentionally or intentionally, the webui will acknowledge it as simply being absent, and it should continue working.  Update to the latest commit and I think this is settled.

(Remember, if the file is missing, you'll still need to set the XMX value and runnable jar!)

**Comment by yesiateyoursheep** [comment]
I've been updating the webui and using npm-install often, but, since commit ```4c9ae0e```, when I log in as any account, it logs in successfully, but nodejs refuses to send any data to the client, and if I refresh the page, I'm logged out again.
According to Chrome's Developer console, communications using socket.js are "400 - Bad Request"s
![capture](https://cloud.githubusercontent.com/assets/7791524/10478158/f675af1e-72b7-11e5-92ba-4b95a745d5ab.PNG)
Each time the server is started, this one line appears in the log file; <a href="http://pastebin.com/jK30yGP3">mineos.log</a> - looks like a dependancy issue. But how come I can still login, and why isn't anything put in the log when I do?

**Comment by hexparrot** [comment]
It's definitely not seeing the version it's expecting of the userid module.  Let's try this: removing the npm modules directly and having it redownload (and hopefully only the expected ones now).

   cd /usr/games/minecraft
   git fetch
   git reset --hard origin/master
   rm -rf node_modules
   npm install

**Comment by yesiateyoursheep** [comment]
Great, this seems to have fixed the issue, I've continued testing, and I haven't ran into any further issues.
