### ISSUE TITLE
API to send commands to server terminal

### ISSUE THREAD

**Issue by jooeycheng** [hexparrot/mineos-node#138]
Currently, we can interact with the server terminal via the web panel, but it would be awesome if there is an API to do this. For example, https://1.1.1.1:8443/api?c=say+hello
Will you be implementing this feature in the future?

**Comment by hexparrot** [comment]
I don't currently have plans for it, as there's more than just creating the API I think I'd have to tackle, from a technical perspective.

For example, all the API commands would have to be authenticated--we couldn't just have people send commands to a server without identifying themselves first.  That also means there needs to be a service in the background to handle incoming requests, which means an additional process in the background listening on an additional port.

Do you have a particular idea in mind that you're hoping to explore?

**Comment by jooeycheng** [comment]
Ah, i see. Sorry, I thought it would be an easy process.
Currently, nope.. I don't have much knowledge in this field.
However, I'm currently looking into some weird hack-ish way of accessing the web terminal tho. haha

**Comment by hexparrot** [comment]
Alright, so I decided that the API approach was something that was better off added to the existing webui, rather than a separate process. Today, I wrote up some new commits that actually will allow command-line API calls using CURL.

```
curl -k -c cookie.txt -d "username=mc&password=mypass" https://localhost:8443/auth
curl -k -b cookie.txt https://localhost:8443/api/myserver/backup
curl -k -b cookie.txt -d "msg=say hello" https://localhost:8443/api/myserver/stuff
curl -k -b cookie.txt -d "msg=say hello&command=stuff&server_name=testing" https://localhost:8443/admin/command

```

Note, my lines use `localhost` but it works perfectly fine when using a remote address, as one might from their desktop to the server.

I'm actually really pleased with the extra potential this API approach adds to the webui, so thanks for asking for it!

**Comment by jooeycheng** [comment]
AWESOME !
but I cant seem to login with curl. It keeps giving me "Found. Redirecting to /admin/login.html". (which seems like an incorrect login redirect)
the cookie.txt file is not generated as well. 
(I made sure my username and password are correct).
Sorry, am I missing something?

**Comment by jooeycheng** [comment]
Whats the difference between msg and command?

**Comment by hexparrot** [comment]
The available commands are every command in `mineos.js`, so all of MineOS effectively.

If the command is a function attached to the 'self' object, like self.backup, self.archive, self.accept_eula, self.delete....it'll work.
