### ISSUE TITLE
Vanilla server versions 1.2.4 and older result in a 403 error

### ISSUE THREAD

**Issue by shinji257** [hexparrot/mineos-node#139]
I don't know if this is really fixable but any server version that is 1.2.4 or older results in a 403 error.  No jar is downloaded and the file that is saved is just a file that indicated access was denied.

**Comment by hexparrot** [comment]
The Mojang official profiles are populated from the official Mojang download list here: http://s3.amazonaws.com/Minecraft.Download/versions/versions.json

The pattern for constructing the download URL is the same for all downloads:

https://s3.amazonaws.com/Minecraft.Download/versions/{0}/minecraft_server.{0}.jar

where {0} is the version, e.g., "1.2.4".  However, it just seems they're not hosting it, even though they're advertising it in the JSON. MineOS can't know the file itself doesn't exist without attempting the download, so for the most part, any list-items that don't correspond with actually-hosted files just have to be ignored; there's not much I can think of doing to prune it down to only-valid links, sorry!

**Comment by shinji257** [comment]
No worries.  I had already indicated that it might not be fixable but was hoping that you would give me insight as to the cause which you did.  Thanks for the info.  Maybe I should go yell at Mojang now. :)
