### ISSUE TITLE
PocketMine server not starting

### ISSUE THREAD

**Issue by spikespaz** [hexparrot/mineos-node#145]
PocketMine server is available as a pre-made profile, however is does not start. The server sends the "Success" notification, but the server stays "DOWN".

**Comment by hexparrot** [comment]
Can you describe the steps you used to attempt making a Pocketmine server?

Also, did you download and copy-profile the appropriate PocketMine-PHP binary?

**Comment by spikespaz** [comment]
I apologize hexparrot, for for the for the late response, my computer's graphics card failed and I was left with the responsibility of replacing it, and as I assume you know, this is not a cheap thing to replace. I will review the procedure I used and respond shortly. Once again, I apologize for the late response, and will get back to you promptly.
