### ISSUE TITLE
wui crashes with error

### ISSUE THREAD

**Issue by mhoepfner** [hexparrot/mineos-node#150]
Since the last update mineos wui has crashed with the following error in the mineos.log. 
I can't start any servers on the wui and there are no error messages.
I m running it on centOS 7.Is there anythig I can do?

{"date":"Mon Nov 23 2015 18:28:47 GMT+0100 (CET)","process":{"pid":5843,"uid":0,"gid":0,"cwd":"/","execPath":"/usr/bin/node","version":"v0.10.40","argv":["/usr/bin/node","/usr/games/minecraft/webui.js","start"],"memoryUsage":{"rss":102109184,"heapTotal":88150016,"heapUsed":64892336}},"os":{"loadavg":[0.53466796875,0.609375,0.4775390625],"uptime":1563.620597166},"trace":[{"column":26,"file":"/usr/games/minecraft/server.js","function":"","line":121,"method":null,"native":false},{"column":17,"file":"events.js","function":"EventEmitter.emit","line":95,"method":"emit","native":false},{"column":12,"file":"/usr/games/minecraft/node_modules/fireworm/index.js","function":"EventEmitter.Fireworm._onAdd","line":84,"method":"Fireworm._onAdd","native":false},{"column":17,"file":"events.js","function":"EventEmitter.emit","line":95,"method":"emit","native":false},{"column":13,"file":"/usr/games/minecraft/node_modules/fireworm/lib/file.js","function":"Object.File","line":16,"method":"File","native":false},{"column":37,"file":"/usr/games/minecraft/node_modules/fireworm/lib/dir.js","function":null,"line":111,"method":null,"native":false},{"column":15,"file":"fs.js","function":"Object.oncomplete","line":108,"method":"oncomplete","native":false}],"stack":["TypeError: Object #<Object> has no method 'parse'","    at EventEmitter.<anonymous> (/usr/games/minecraft/server.js:121:26)","    at EventEmitter.emit (events.js:95:17)","    at EventEmitter.Fireworm._onAdd (/usr/games/minecraft/node_modules/fireworm/index.js:84:12)","    at EventEmitter.emit (events.js:95:17)","    at Object.File (/usr/games/minecraft/node_modules/fireworm/lib/file.js:16:13)","    at /usr/games/minecraft/node_modules/fireworm/lib/dir.js:111:37","    at Object.oncomplete (fs.js:108:15)"],"level":"error","message":"uncaughtException: Object #<Object> has no method 'parse'","timestamp":"2015-11-23T17:28:47.023Z"}

**Comment by hexparrot** [comment]
MineOS over time will improve for stability, performance, and security reasons.  In this case, recent updates necessitate that you update to a more modern version of node.js.  Your pre-stable version 0.10.40 and the npm module builds that accompany it is the problem.  A current version is 4.0.0 or above.

    "version":"v0.10.40"

CentOS7 has yum support for 4.0.0+

**Comment by mhoepfner** [comment]
Thanks. After I installed nodejs v4.2.2 ist works perfectly.

btw:  *yum install nodejs* installs the version  v0.10.36, therefore i installed it manually from package
