### ISSUE TITLE
Please add PAM authentication like in the Python Version

### ISSUE THREAD

**Issue by Routhinator** [hexparrot/mineos-node#151]
Hi,

I just installed the new version, and I can no longer authenticate domain users via PAM as I could in the Python version. It seems this version can only access local accounts and groups.

**Comment by hexparrot** [comment]
Would definitely like to, but PAM auth doesn't seem to be well-developed in node.js.

The top 5 listed PAM modules--none of them build on stable 4.0.0 or above.
https://www.npmjs.com/search?q=pam

**Comment by Routhinator** [comment]
This seems promising:

https://github.com/Rush/node-authenticate-pam

**Comment by hexparrot** [comment]
Have you tried `npm install authenticate-pam` with any success?

**Comment by hexparrot** [comment]
Were you able to successfully download `authenticate-pam` with npm then?

**Comment by hexparrot** [comment]
PAM supported added in PAM branch: https://github.com/hexparrot/mineos-node/tree/pam

`npm` won't build all requisite modules if PAM support is absent on the host system. On Debian-based systems this will necessitate `apt-get install libpam0g-dev`.  Other distributions will have their own packaging system; be sure it is installed before switching to this branch and attempting PAM use.

**Comment by hexparrot** [comment]
pam support officially in `master` #191
