### ISSUE TITLE
Debian 8

### ISSUE THREAD

**Issue by MrBretze** [hexparrot/mineos-node#156]
i have this error for installing mineos on debian 8 minimal server

http://puu.sh/lUBVG/085317364b.png

**Comment by hexparrot** [comment]
Nose version is too old. See wiki, need 4.0 or higher, not 0.12 pre release

**Comment by MrBretze** [comment]
Node js stop work on debian ?

**Comment by MrBretze** [comment]
Util for install nodejs https://github.com/nodejs/node-v0.x-archive/wiki/Installing-Node.js-via-package-manager

**Comment by hexparrot** [comment]
Yes, your linked URL is the page you should be using for getting node, but whatever the case, the picture you sent shows the *actual node you're running* is 10.29.
