### ISSUE TITLE
How to create server from CLI

### ISSUE THREAD

**Issue by RamonSmit** [hexparrot/mineos-node#161]
Good day fine GitHub people, 

How do I create a full server from the command line? 

I think i have to use `mineos_console.js` but I find it a bit difficult to find the correct way

Thanks in advance, 
Ramon

**Comment by hexparrot** [comment]
Here's how you can create a server from scratch.  Log in as `root`:

cd /usr/games/minecraft
./mineos_console.js -s newserver create 1000:1001
./mineos_console.js -s newserver accept_eula
./mineos_console.js -s newserver modify_sc minecraft profile 1.8.9
./mineos_console.js -s newserver modify_sc java jarfile minecraft_server.1.8.9.jar
./mineos_console.js -s newserver start

**Comment by RamonSmit** [comment]
Oh I see, well, to get the uid and gid I can use `id -u root` and `id -g root`.

Many many thanks! #161 is solved! :+1:

**Comment by hexparrot** [comment]
As an aside, it is heavily discouraged to run servers as root--it offers no benefit over unprivileged users and comes with a bit of added risk to the system run as root.

All the same, glad you got it up and running!
