### ISSUE TITLE
Ubuntu Snappy Support

### ISSUE THREAD

**Issue by leoherzog** [hexparrot/mineos-node#164]
Personally, I love the Github-based installation that MineOS uses now. However, with the dependencies that MineOS needs, stability may be improved by distributing via [Ubuntu's new Snappy System](https://developer.ubuntu.com/en/snappy/#tour).

It would be neat to consider having the install procedure instead be `sudo snappy install mineos` to grab the latest known-working versions of node.js, npm, rsync, Java, etc.

**Comment by hexparrot** [comment]
Does snappy actually provide any benefit over more common, bistro-agnostic solutions like Docker?

**Comment by xd1936** [comment]
They can live together

https://insights.ubuntu.com/2015/07/20/prime-time-docker-juju-and-snappy-ubuntu-core/

**Comment by Jacalz** [comment]
Yeah this would actually be very useful, +1 on this 👍

**Comment by hexparrot** [comment]
Snappy isn't likely to ever get developed on my end.  It doesn't appear that snappy is well received, in general.  If I am to ever go into the realm of immutable packages, I think Flatpak might be the best contender, so we don't find ourselves spending dev time and effort on what is still, largely an Ubuntu show.
