### ISSUE TITLE
WebUI Bug?

### ISSUE THREAD

**Issue by ryancito02** [hexparrot/mineos-node#167]
Alright, here is a screenshot of my webui, which I can only start from 'node webui.js'.

![screenshot from 2016-02-17 22 50 48](https://cloud.githubusercontent.com/assets/17111990/13134172/ee4da944-d5c8-11e5-83b3-a51976bca4bb.png)

Is it supposed to be this buggy? For example, my username is instead replaced by blank space, and when I get to creating a profile, when I click for a dropdown* nothing shows up. 

I click create server, I type in the info, and at the bottom it says "Delete /undefined/servers/TEST"?
So it does not recognize my user login..

![screenshot from 2016-02-17 22 54 13](https://cloud.githubusercontent.com/assets/17111990/13134221/6897fcc2-d5c9-11e5-817c-4c50ecab66ab.png)

Notice all the "Undefined" plastered everywhere. I am using a HTTP version of the website, maybe HTTPS will fix this?

**Comment by ryancito02** [comment]
Just a follow up - Have 8 gigs of RAM on my computer - Just using a bunch right now.

**Comment by ryancito02** [comment]
![screenshot from 2016-02-17 22 58 36](https://cloud.githubusercontent.com/assets/17111990/13134268/03419134-d5ca-11e5-85a3-2294e4dd3d43.png)
Nope, my guess was wrong. HTTPS doesn't fix this. I am starting the MineOS using 'supervisorctl start mineos'. Is this what is supposed to happen? Please help.

**Comment by hexparrot** [comment]
This is clearly **not** how it is supposed to be operating.  So to answer your question, _no, it is not supposed to be that buggy_.

What does your `/var/log/mineos.log` say?  This is *always* the first place to check and the first things to share if we want any chance of fixing an issue.

**Comment by ryancito02** [comment]
I can't view the commit : because of all the bugginess, but I clicked it and came up on a github page with commit fe450e0, which I believe is the commit I am using. Here is the link it directed me to - 
https://github.com/hexparrot/mineos-node/commit/master

Here are the contents of my /var/log/mineos.log
[mineos.log.txt](https://github.com/hexparrot/mineos-node/files/137080/mineos.log.txt)

You probably have to scroll all the way down to the "February 17, 2016" section.

Seeing this 'timestamp' error in the log. Maybe that has something to do with it? 
A dependency maybe? An unset variable? Well, whatever it is, hope this helps.

**Comment by hexparrot** [comment]
When you updated the webui, did you do all the instructions, including the `npm install`?

```
cd /usr/games/minecraft
rm -rf node_modules
npm install
```

Do this, it should hopefully address the module missing that is peppering your mineos.log

**Comment by ryancito02** [comment]
Thank you, this worked. Apparently, I had compiled my dependencies incorrectly the first time..
