### ISSUE TITLE
Script hooks for webui actions.

### ISSUE THREAD

**Issue by treyzania** [hexparrot/mineos-node#168]
Would it be possible to run scripts for when various actions in the webui are triggered?  This could make something like rolling back a CoreProtect database automatically when restoring a snapshot backup via the webui possible.  I'm not sure how feasible this would be.

**Comment by hexparrot** [comment]
While such hooks are certainly well within the realm of technically do-able, it's not feasible for it to be implemented this late in the development cycle, where this would be a particularly drastic change/improvement.

I will keep this in mind though--as it is something I can aim to include in the next iteration, as I attempt to learn ruby: https://github.com/hexparrot/mineos-ruby
