### ISSUE TITLE
Ability to restart server automatically on shutdown

### ISSUE THREAD

**Issue by treyzania** [hexparrot/mineos-node#170]
It could just be a simple flag in the "Server Status" menu to have the server restart automatically if it shuts down.  If a moderator or someone with the ability to do `/stop` in game shuts down the server they won't be able to restart it without going to the web UI.  It also helps me when testing plugins.

**Comment by treyzania** [comment]
I'm poking around in the code to see if I'd be able to do this myself.  If I find a way soon enough I'll make a fork.  I'm quite a novice at Node.js so it might take some time.

**Comment by ciak2009** [comment]
You could use spigot and its restart script, I think it works inside of MineOS, I can't say for certain though, I'll test it myself and let you know!

**Comment by hexparrot** [comment]
The ability to automatically restart servers is a iffy ability at best, and a big nuisance at worst.

After all, if a moderator or somebody with the rights _accidentally_ executes `/stop`, that person just needs to be more attentive.

However, if it _is_ intended, such as to test plugins, I think it might be counter-productive.  After all, an automatic restart means the server is pretty much 100% uptime, which is the wrong time to be modifying/deleting/adding files to a server.

If modifying files in the working directory, you likely should already be out-of-game (or at least, playing windowed, etc.,) where you have simultaneous access to the FTP client, SSH, or the webui anyway.

For other purposes, if, say, you just want the server to never be down, there are options:

1) create a cronjob in the webui to attempt to start the server every minute.  If the server is up, the request will be ignored.
2) create a cronjob in linux, using `mineos_console.js`. See: https://discourse.codeemo.com/t/question-about-cron/2295/4?u=hexparrot
