### ISSUE TITLE
Give your users access to our packs please. <3

### ISSUE THREAD

**Issue by ciak2009** [hexparrot/mineos-node#171]
Hey HexParrot, 

Thanks for helping resolve the excessive CPU issue, I was wondering if you would be open to working with us to give your users 1-click install for some of our most popular packs like Mianite (1M Runs, 250K Downloads).

Look forward to hearing from you!

-Caleb

**Comment by hexparrot** [comment]
Hi Caleb,

I'm always excited to get more functionality and possibilities into MineOS.  I've worked on trying to get Technic working on MineOS before as a single-click install, but I ran into issues essentially being the API between me and a direct download.  But by all means, what do we need to explore to get this working?

**Comment by ciak2009** [comment]
We've got an API endpoint for any of our packs we offer server files for:

Mianite for example: http://mianite.us/repo?api=true

And to get our latest or rec build: http://mianite.us/repo?api=true&build=rec

Its my own custom API for easily grabbing all our server files, so I could setup an endpoint for you that aggregates all our packs and returns their release "Name" similar to pictured below, but with all our packs, and by supplying a rec or latest preference it grabs the associated server file builds and presents you with the packs name "name", the release version "version" and the link to the packs zip "download"

`{"download":"http:\/\/solder.endermedia.com\/repository\/downloads\/realm-of-mianite\/realm-of-mianite_1.4.1.zip","name":"Realm of Mianite","version":"1.4.1","version_tag":"Recommended"}`

Thoughts are very welcome :+1: :)

**Comment by hexparrot** [comment]
> {"download":"http:\/\/solder.endermedia.com\/repository\/downloads\/realm-of-mianite\/realm-of-mianite_1.4.1.zip","name":"Realm of Mianite","version":"1.4.1","version_tag":"Recommended"}

If you're able to do this for me, I can get it in this weekend.

**Comment by hexparrot** [comment]
Pull the `mianite` branch I just created.  It seems to work as expected, can you verify?

**Comment by ciak2009** [comment]
Worked like a dream, Eventually I'd love to swap out Mianite for "EnderMedia Packs" and I'll setup an endpoint where you can pull all our packs and their versions. For now though, thats really awesome :+1: 

Thanks for the help!

**Comment by hexparrot** [comment]
Ugh, having done the work already, I embarrassingly didn't pull it in, sorry!

https://github.com/hexparrot/mineos-node/commit/8ad586e45ed6d92c6e3b235850562870bd80313d

**Comment by ciak2009** [comment]
<3 so its pulled in now?

**Comment by hexparrot** [comment]
Had I been on top on things it would've been early March!  Yes it's in fully in master so you can switch to that branch now
