### ISSUE TITLE
One other enhancement thought. RemoteToolKit

### ISSUE THREAD

**Issue by ciak2009** [hexparrot/mineos-node#174]
I use RemoteToolkit to run things in a wrapper, and it happens to run quite well. I've found myself modifying your source code to swap out /stop with .hold and /restart with .restart. Would you consider adding a configuration toggle in the server settings like RemoteToolkit = true or something of that nature? Would be super handy!

**Comment by hexparrot** [comment]
I apologize for the negligence here in this issue.  Is RemoteToolkit still a thing relevant for modern versions (1.10+) of Minecraft?  Is this something that would be useful to implement?

**Comment by ciak2009** [comment]
Sadly I think it is gone.

**Comment by hexparrot** [comment]
My apologies.  If anything new comes down on this front, I'd be happy to take a look at it and see if such a toggle or better yet, some integration can be put into place.
