### ISSUE TITLE
Node Module 'du' crashes mineos because of massive array size.

### ISSUE THREAD

**Issue by KiloJuliet** [hexparrot/mineos-node#175]
So we had a guy try to import a server with 40GB of dynmap which calculates to more than a reasonable amount of files. Mineos CPU maxed out and a while later crashed.

I assume it's because Javascript can't handle arrays that large, at least in the way it's being handled here.

We've temporarily patched out the du call and got everything running, but if you have any users with obscene amounts of files they also will run into this issue.

==== JS stack trace =========================================

Security context: 0xb02f6ae3ac1 <JS Object>
    1: /* anonymous */(aka /* anonymous */)
[/usr/games/minecraft/node_modules/du/node_modules/async/lib/async.js:182]
[pc=0x83fe9acac69] (this=0xb02f6a04189 <undefined>,x=0x3c4c746b5de9
<String[91]: /var/games/minecraft/servers/Minecraft/plugins/dynmap/web/tiles/world/t/-24_24/-737_768.jpg>,i=0)
    2: arguments adaptor frame: 3->2
    3: InnerArrayMap(aka InnerArrayMap) [native array.js:~1019]...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory

Yet another reason to hate Dynmap =) but I figured you might want to know about this error because I'm not sure if it would trigger in other situations like, for example, a server with tons of worlds or other scenarios.

**Comment by ciak2009** [comment]
What version are you using?

**Comment by KiloJuliet** [comment]
We've removed the du disk space used per server calculations entirely in our build and replaced it with a solution using https://www.npmjs.com/package/node-df . We have that displayed on the main page instead of grabbing each individual server's size. It's good enough for our purposes to just check the total disk size. I'm not sure that solution would be something the masses appreciate though.

**Comment by hexparrot** [comment]
What's the value of `level-name` in your server.properties?

**Comment by KiloJuliet** [comment]
I'm not sure as I no longer manage that person's server and I no longer have access. It was not the default world though.

**Comment by hexparrot** [comment]
Yep, I suspected so.  I just wrote a commit that should actually resolve that issue--it's evaded me for a long enough time but I'll be pulling it into the master once I can get a confirmation of its effectiveness.

**Comment by hexparrot** [comment]
This commit has been pulled into the master branch.  `du` operation cannot be avoided using the conventional means, so it has been rewritten so that you can delete the `du` modules from the filesystem and MineOS will just report 0 bytes and not attempt to traverse the directory.

`rm -rf /usr/games/minecraft/node_modules/du`
