### ISSUE TITLE
MineOS runs out of memory after several minutes.

### ISSUE THREAD

**Issue by treyzania** [hexparrot/mineos-node#178]
The log file just repeatedly shows MineOS trying to "create a tail" on logs/latest.log.  Sometimes it fails, sometimes it succeeds.  It does this for roughly 15 minutes or so until it runs out of memory and crashes.

It *might* have something to do with the fact that the web UI is very slow on this server.  I can click on buttons and type commands into the console, but nothing will happen for several minutes until EVERYTHING gets sent all at once.

I am using the latest version, commit 1853741.

Logs:
* `supervisorctl tail mineos`: http://pastebin.com/E3eJFgqj
* `cat /var/log/mineos.log`: http://treyzania.com/mineos.log (1.83 MB is too big for Pastebin.)

**Comment by hexparrot** [comment]
Just to be sure, you have a server called "logs"--what sort of server is this?  Can you provide the URL if its not a standard profile type?

**Comment by hexparrot** [comment]
Can you check to see if there are any symlinks in your server's directory or subdirectories? `ls -la`.  I'm wondering if this could potentially be related to constantly trying to re-check a folder because it goes down one folder, finds a symlink to a folder it already has done, ad infinitum.

It'd certainly explain why I've never been able to reproduce the issue.

**Comment by hexparrot** [comment]
go ahead and clear out your `mineos.log`:   echo '' > /var/log/mineos.log

Then, switch to this new branch where I have updated the 'tail' module from 0.7.0 to 1.0.0.

    cd /usr/games/minecraft
    rm -rf node_modules
    git fetch
    git pull
    git merge origin assorted_fixes
    npm install
    supervisorctl restart mineos

**Comment by treyzania** [comment]
I may have figured out part of the problem, there was a directory called "logs" in the servers directory, but it wasn't set up as a server in MineOS.  It just had a bunch of `*.log.gz` files in it from a server.  We have "build_19", "bungeecord_19", "lobby1_18" (not in use), "lobby1_19", and "lobby2_19" on the server in question.  The other physical servers we have are running either `b49c634` or `fe450e0` and don't have this issue.

Running `ls -laR | grep '^l'` (recursively lists all symlinks) in `/var/games/minecraft/servers` returns nothing at all.

Using that update doesn't seem to fix the very slow response time in the web UI, however.

This is `/var/log/mineos.log` now: http://pastebin.com/mYUNS43K

**Comment by hexparrot** [comment]
Alright, try this:

     cd /usr/games/minecraft
     git pull
     rm -rf node_modules/du
     supervisorctl restart mineos

**Comment by treyzania** [comment]
That appears to have fixed the slow response time once you're actually in the control panel, but it still takes ages for the login page to load, and then for the control panel to initally load after that.
Thanks

**Comment by hexparrot** [comment]
Alright, try this:

```
 cd /usr/games/minecraft
 git fetch
 git checkout master
 git reset --hard origin/master
 rm -rf node_modules
 supervisorctl restart mineos
```

A different approach that I hope will completely solve all slowness.

**Comment by hexparrot** [comment]
Changes have been implemented into the master branch that hope to resolve this issue--runaway memory usage due to large server directories should be a largely solved problem.  That said, slowness from large server directories (upon webui login) has not been solved, but can be worked around through the solution offered in #175.
