### ISSUE TITLE
Restore points fail to create when symlinking a server outside of the expected directory

### ISSUE THREAD

**Issue by msmollin** [hexparrot/mineos-node#179]
**Some context to understand how I got into this situation**
I run MineOS virtualized in VMware vSphere 5.5 (have been doing so since the CRUX era) off of a shared SAN environment. With the latest 1.9 update, my players went bonkers and have been doing crazy exploration to the point the world is probably 2x the size now, with significantly more chunks active and giant railway systems in both the overworld and the nether. Exciting, right?

Well the issue is this has caused a significant strain on the SAN setup. So to resolve this I'm going to be installing a PCIe SSD and moving the entire VM to be served from that on the SAN. However until I can get to my server to install that (it's colocated), I set up a ramdisk to move the world I/O off the SAN, and symlinked my server from `/mnt/ramdisk/Mostlygeeks_Primary/` to `/var/games/minecraft/servers/Mostlygeeks_Primary`. This worked fine for everything except restore points, which broke and I have not been able to figure out what's wrong.

**Current Setup**
Running Ubuntu 14.04 LTS, fully up-to-date. Java is Oracle Java 1.8. Current server is Spigot, but was also broken running Vanilla.

Pertinent Error from logs:
```
{"level":"info","message":"[Mostlygeeks_Primary] 198.168.32.4 issued command : \"backup\"","timestamp":"2016-03-25T11:34:08.895Z"}
{"level":"info","message":"[Mostlygeeks_Primary] received request \"backup\"","timestamp":"2016-03-25T11:34:08.897Z"}
{"command":"backup","uuid":"7d233000-f27d-11e5-87d9-6baddadb8d62","time_initiated":1458905648896,"success":false,"err":1,"time_resolved":1458905648984,"level":"error","message":"[Mostlygeeks_Primary] command \"backup\" errored out:","timestamp":"2016-03-25T11:34:08.985Z"}
```

I can only imagine this is a permissions issue, so here's the current permission setup on all directories involved:
```
administrator@mineos:/var/games$ ls -la
total 12
drwxrwxr-x  3 root root 4096 Mar  1 22:24 .
drwxr-xr-x 13 root root 4096 Mar  1 22:24 ..
drwxrwxr-x  7 root root 4096 Mar  1 22:24 minecraft
administrator@mineos:/var/games$ cd minecraft/
administrator@mineos:/var/games/minecraft$ ls -la
total 28
drwxrwxr-x 7 root root 4096 Mar  1 22:24 .
drwxrwxr-x 3 root root 4096 Mar  1 22:24 ..
drwxrwxr-x 3 root root 4096 Mar  1 22:30 archive
drwxrwxr-x 3 root root 4096 Mar  1 22:30 backup
drwxrwxrwx 2 root root 4096 Mar  1 22:24 import
drwxrwxr-x 5 root root 4096 Mar 18 20:04 profiles
drwxrwxr-x 2 root root 4096 Mar 16 00:03 servers
administrator@mineos:/var/games/minecraft$ cd servers/
administrator@mineos:/var/games/minecraft/servers$ ls -la
total 8
drwxrwxr-x 2 root root 4096 Mar 16 00:03 .
drwxrwxr-x 7 root root 4096 Mar  1 22:24 ..
lrwxrwxrwx 1 root root   33 Mar 16 00:03 Mostlygeeks_Primary -> /mnt/ramdisk/Mostlygeeks_Primary/
administrator@mineos:/var/games/minecraft/servers$ cd Mostlygeeks_Primary
administrator@mineos:/var/games/minecraft/servers/Mostlygeeks_Primary$ ls -la
total 49368
drwxrwxr-x 9 administrator administrator      540 Mar 25 07:09 .
drwxrwxrwt 3 root          root                60 Mar 15 23:56 ..
-rw-rw-r-- 1 administrator administrator        2 Mar 25 07:10 banned-ips.json
-rw-rw-r-- 1 administrator administrator        2 Mar 25 07:10 banned-players.json
-rw-rw-r-- 1 administrator administrator  3411487 Mar 18 20:04 BuildTools.jar
-rw-rw-r-- 1 administrator administrator     1183 Mar 25 07:10 bukkit.yml
-rw-rw-r-- 1 administrator administrator      560 Mar 25 07:10 commands.yml
-rw-rw-r-- 1 administrator administrator 17750323 Mar 25 07:07 craftbukkit-1.9.jar
drwxrwxr-x 2 administrator administrator      120 Mar 18 19:10 crash-reports
-rw-rw-r-- 1 administrator administrator      179 Mar 15 23:56 cron.config
drwxrwxr-x 2 administrator administrator       60 Mar 15 23:56 debug
-rw-rw-r-- 1 administrator administrator        9 Mar 15 23:56 eula.txt
-rw-rw-r-- 1 administrator administrator     2576 Mar 18 09:32 help.yml
drwxrwxr-x 2 administrator administrator      860 Mar 25 07:10 logs
-rw-rw-r-- 1 administrator administrator  8848015 Mar 15 23:56 minecraft_server.1.9.jar
-rw-rw-r-- 1 administrator administrator      273 Mar 25 07:10 ops.json
-rw-rw-r-- 1 administrator administrator        0 Mar 18 09:32 permissions.yml
drwxrwxr-x 3 administrator administrator       60 Mar 18 09:32 plugins
-rw-rw-r-- 1 administrator administrator      102 Mar 18 23:39 server.config
-rw-rw-r-- 1 administrator administrator      840 Mar 25 07:10 server.properties
-rw-rw-r-- 1 administrator administrator 20483498 Mar 25 07:07 spigot-1.9.jar
-rw-rw-r-- 1 administrator administrator     2916 Mar 25 07:10 spigot.yml
-rw-rw-r-- 1 administrator administrator     1394 Mar 25 07:11 usercache.json
-rw-rw-r-- 1 administrator administrator        2 Mar 15 23:56 whitelist.json
drwxrwxr-x 6 administrator administrator      200 Mar 25 07:30 world
drwxrwxr-x 5 administrator administrator      180 Mar 25 07:30 world_nether
drwxrwxr-x 5 administrator administrator      180 Mar 25 07:30 world_the_end
administrator@mineos:/var/games/minecraft/servers/Mostlygeeks_Primary$ cd /mnt/
administrator@mineos:/mnt$ ls -la
total 8
drwxr-xr-x  3 root root 4096 Mar 15 23:38 .
drwxr-xr-x 22 root root 4096 Mar  1 22:11 ..
drwxrwxrwt  3 root root   60 Mar 15 23:56 ramdisk
administrator@mineos:/mnt$ cd ramdisk/
administrator@mineos:/mnt/ramdisk$ ls -la
total 4
drwxrwxrwt 3 root          root            60 Mar 15 23:56 .
drwxr-xr-x 3 root          root          4096 Mar 15 23:38 ..
drwxrwxr-x 9 administrator administrator  540 Mar 25 07:09 Mostlygeeks_Primary
administrator@mineos:/mnt/ramdisk$ cd Mostlygeeks_Primary/
administrator@mineos:/mnt/ramdisk/Mostlygeeks_Primary$ ls -la
total 49368
drwxrwxr-x 9 administrator administrator      540 Mar 25 07:09 .
drwxrwxrwt 3 root          root                60 Mar 15 23:56 ..
-rw-rw-r-- 1 administrator administrator        2 Mar 25 07:10 banned-ips.json
-rw-rw-r-- 1 administrator administrator        2 Mar 25 07:10 banned-players.json
-rw-rw-r-- 1 administrator administrator  3411487 Mar 18 20:04 BuildTools.jar
-rw-rw-r-- 1 administrator administrator     1183 Mar 25 07:10 bukkit.yml
-rw-rw-r-- 1 administrator administrator      560 Mar 25 07:10 commands.yml
-rw-rw-r-- 1 administrator administrator 17750323 Mar 25 07:07 craftbukkit-1.9.jar
drwxrwxr-x 2 administrator administrator      120 Mar 18 19:10 crash-reports
-rw-rw-r-- 1 administrator administrator      179 Mar 15 23:56 cron.config
drwxrwxr-x 2 administrator administrator       60 Mar 15 23:56 debug
-rw-rw-r-- 1 administrator administrator        9 Mar 15 23:56 eula.txt
-rw-rw-r-- 1 administrator administrator     2576 Mar 18 09:32 help.yml
drwxrwxr-x 2 administrator administrator      860 Mar 25 07:10 logs
-rw-rw-r-- 1 administrator administrator  8848015 Mar 15 23:56 minecraft_server.1.9.jar
-rw-rw-r-- 1 administrator administrator      273 Mar 25 07:10 ops.json
-rw-rw-r-- 1 administrator administrator        0 Mar 18 09:32 permissions.yml
drwxrwxr-x 3 administrator administrator       60 Mar 18 09:32 plugins
-rw-rw-r-- 1 administrator administrator      102 Mar 18 23:39 server.config
-rw-rw-r-- 1 administrator administrator      840 Mar 25 07:10 server.properties
-rw-rw-r-- 1 administrator administrator 20483498 Mar 25 07:07 spigot-1.9.jar
-rw-rw-r-- 1 administrator administrator     2916 Mar 25 07:10 spigot.yml
-rw-rw-r-- 1 administrator administrator     1394 Mar 25 07:11 usercache.json
-rw-rw-r-- 1 administrator administrator        2 Mar 15 23:56 whitelist.json
drwxrwxr-x 6 administrator administrator      200 Mar 25 07:30 world
drwxrwxr-x 5 administrator administrator      180 Mar 25 07:30 world_nether
drwxrwxr-x 5 administrator administrator      180 Mar 25 07:30 world_the_end
administrator@mineos:/mnt/ramdisk/Mostlygeeks_Primary$ 
```

Obviously this will go away once I can get the SSD installed and undo this setup, but I'm curious what about this is wrong?

**Comment by msmollin** [comment]
Probably also worth noting that I'm currently tracking against `origin/master` and am sitting at `0e45be751ec537a4096ee2bd56b83e5c6ad135c2` which is currently 5 commits behind origin/master, but from what I saw in the changelog, nothing got updated that should resolve this. If I missed something however, please tell me!

**Comment by hexparrot** [comment]
The issue you're running into expected, by design, though it does not meet our own expectations of how we think rdiff-backup should work.

I've mimic'ed your setup locally to demonstrate.  When MineOS attempts to make a backup, it does the following commands:

    cd /var/games/minecraft/backup/Mostlygeeks_Primary
    rdiff-backup /var/games/minecraft/servers/Mostlygeeks_Primary .

These commands say "make a backup from this source path, and write the backup to the current working directory (.)".  However, because you've symlinked Mostlygeeks_Primary, rdiff-backup sees a file--not a directory; it sees a symlink file that represents the directory.  Unfortunately, rdiff-backup makes a very strict differentiation, so it would give you this error if you could see its execution:

    root@mineos backup/Mostlygeeks_Primary# rdiff-backup  /var/games/minecraft/servers/Mostlygeeks_Primary .
    Fatal Error: Source /var/games/minecraft/servers/Mostlygeeks_Primary is not a directory

Because indeed, Mostlygeeks_Primary is a symlink--a type of file.

Realistically, one might try to solve this by instead of soft-linking it, to instead hard-link it.  That basically means leaving out the "-s" portion.  But...

    root@mineos minecraft/servers# ln /mnt/ramdisk/Mostlygeeks_Primary .
    ln: '/mnt/ramdisk/Mostlygeeks_Primary': hard link not allowed for directory

`ln` doesn't support hardlinking directories.  This puts us in a hard place, because Linux itself won't allow one solution (hardlinking) and rdiff-backup itself won't support following symlinks (it technically will, but only if you followed it from /servers, not /servers/Mostlygeeks_Primary--which might not be plausible here).

Now it's totally possible to do this with `mount --bind`, as in:

    cd /var/games/minecraft/servers
    (remove the Mostlygeeks_Primary symlink)
    mkdir Mostlygeeks_Primary
    mount --bind /mnt/ramdisk/Mostlygeeks_Primary ./Mostlygeeks_Primary

BUT.  This won't persist through reboots.  So it means you'll also have to set up this entry in your `/etc/fstab`.  It's not difficult, but you're stating to make a lot of changes now to your FS that you'd also have to undo when you get your SSD, which means there's more room for error (forgetting to UNDO this would be bad for your backups).

Bindmounts subvert the need for symlinks...but add a whole new level of complexity.  If possible, you might consider manually backing up your directory with the command line, going right from the source to your backup dir.  A manual backup approach works  because you'll be able to come from /mnt/ramdisk/Mostlygeeks_Primary rather than having to change the coded paths in the scripts away from /var/games/minecraft/servers.

    rdiff-backup /mnt/ramdisk/Mostlygeeks_Primary /var/games/minecraft/backup/Mostlygeeks_Primary

**Comment by msmollin** [comment]
As always, Will, your thoroughness and thoughtfulness in your replies is highly appreciated. I went about implementing the manual backups for now, as I still haven't managed to get time into the schedule to go down and install the SSD.

Closing this, and thanks again!
