### ISSUE TITLE
Crontab schedule arguments

### ISSUE THREAD

**Issue by i-need-to-tell-you-something** [hexparrot/mineos-node#186]
In the Crontab Schedule (aka Scheduling) part of WebUI, when making a cronjob without additional argument (tried archive and backup) right after making one with an argument (Send to console / stuff), the new cronjob gets the same argument as previous one. Not sure whether any functionality/behavior is affected. I can only remove it by editing the file manually through ssh (or by deleting the new cronjob, switching to making a new "Send to console / stuff" cronjob, deleting the existing argument in the field, remaking my original problematic cronjob that isnt supposed to have an argument).

Thanks for all of your hard work, all the best to you.

**Comment by hexparrot** [comment]
Fixed in 5b9c841b7bca22d8804b8144433b40acd2fb0670
