### ISSUE TITLE
"No spaces" limitation not enforced when importing servers from archive

### ISSUE THREAD

**Issue by Randelung** [hexparrot/mineos-node#187]
If importing an archive, the name rules for new servers are not enforced, causing spaces to be accepted. This causes the check for a running server to fail for some reason.

**Comment by hexparrot** [comment]
Fixed in df957e7666a04b22881bd5ded20feb7e886184d8.  Thanks for the heads up!

**Comment by Randelung** [comment]
Nice, thanks :)
