### ISSUE TITLE
runable jar not listing

### ISSUE THREAD

**Issue by MrBretze** [hexparrot/mineos-node#190]
I can't select a jar in the panel

**Comment by MrBretze** [comment]
My log has 41Mo :/

**Comment by MrBretze** [comment]
Logs: http://hastebin.com/wupogarolu.md
Screen: http://puu.sh/oNU81/a645d633dc.png

**Comment by hexparrot** [comment]
I need a bit more to work with, if possible.  The log you shared only shows one start-up of the server, using a commit that is not an official commit.  Not only do I not know where your webui is in terms of development, I'm also not sure what "Fix bug" did to the code.

That said, was it your intent--and more importantly, is it necessary--to have `weather clear 999` run every single second the server is up?

{"command":"stuff","source":"* * * * * *","msg":"weather clear 999","enabled":true,"success":false,"err":"up","time_resolved":1462966203897,"level":"error","message":"[BackToMinecraft] command \"stuff\" errored out:","timestamp":"2016-05-11T11:30:03.898Z"}

See the cron syntax here: https://www.npmjs.com/package/cron

Lastly, did this happen after any particular event?  Did you just create a new server, *then* this happened?  Did you just do stuff as `root` in the command line?  If anything, can it be undone to see if it was the cause of this issue?

Really, though, selective pick-and-choosing of the mineos.log is also pretty difficult to work with.

**Comment by MrBretze** [comment]
The cron command is disabled and the server is down

**Comment by hexparrot** [comment]
Are you able to address *any* of the other issues raised in my last post?

**Comment by MrBretze** [comment]
Yes, Fix bug not working, i revert this, m'y version of mineos is the same of this, i just updated the graphics,

**Comment by hexparrot** [comment]
And I still have no idea what commit your webui is on.

**Comment by MrBretze** [comment]
for jar not display not the server is a old server and happen overnight is not work :/

**Comment by hexparrot** [comment]
Please instead just open a new topic in discourse.codeemo.com.  Github issues is likely only to be looked after by too few people, and it would be nice to not clutter this with short, uninformative discussion with insufficient information to work with.

**Comment by MrBretze** [comment]
And i use the last commit of your version of mineos
