### ISSUE TITLE
Format uptime to days/weeks/months etc

### ISSUE THREAD

**Issue by wildcardjoker** [hexparrot/mineos-node#193]
Currently our uptime shows 144:50:21

It would be great if that could be presented in a more user-friendly way, such as 

- 6d 50m 21s
- 6 days, 50 minutes, 21 seconds
- 6:00:50:21

Thanks!

**Comment by MrBretze** [comment]
To fix this: https://github.com/MrBretze/mineos-node/blob/master/html/js/scriptin.js#L100-L117

**Comment by wildcardjoker** [comment]
Excellent, thanks!
