### ISSUE TITLE
Add SpongeVanilla jar

### ISSUE THREAD

**Issue by lasercar** [hexparrot/mineos-node#194]
Could you please add a profile for [SpongeVanilla](spongepowered.org)?

**Comment by hexparrot** [comment]
Sure.  Does sponge vanilla have a non-html way to get all the URLs for the downloads? 

RSS, XML, JSON, etc.?

**Comment by lasercar** [comment]
I found this file that lists the versions:
https://repo.spongepowered.org/maven/org/spongepowered/spongevanilla/maven-metadata.xml

The download urls could then be made from those versions:
`https://repo.spongepowered.org/maven/org/spongepowered/spongevanilla/{VERSION}/spongevanilla-{VERSION}.jar`

**Comment by hexparrot** [comment]
Thanks for providing all the details here; I was able to easily implement it into the webui into the mater branch commit e1f7cbc3f68173945aae015da32fe5d0efca1aed
