### ISSUE TITLE
File editor

### ISSUE THREAD

**Issue by lasercar** [hexparrot/mineos-node#195]
It would be amazing to integrate a browser-based file editor like [Ace](https://ace.c9.io) into MineOS, so the server files could be edited (browser-based upload/download would be useful too) in the web interface.

**Comment by hexparrot** [comment]
This isn't likely to happen; this is a pretty hefty file editor and not a trivial thing to implement.  The back end would have to be updated to work with transferring files--potentially large files, which has its own downsides in terms of memory consumption etc.

Especially considering how often people allocate memory to Minecraft cut so close to the wire and how some logs or files that could be edited here could be in the dozens or hundreds of megabytes (and unwittingly opened), there are big performance ramifications of that memory immediately going away/swapping.

In terms of existing browser-based file editors you could use, MineOS Turnkey comes with Webmin in the official MineOS ISOs. In the meantime, this is likely to be put off until it's partially implemented by a community developer (and I could polish).
