### ISSUE TITLE
Kill server button doesn't work on bungee

### ISSUE THREAD

**Issue by lasercar** [hexparrot/mineos-node#197]
The kill button seems to not be responsive, it doesn't stop the server running bungee.

Running git commit: 5e7c7db
![MineOS - kill button bungee server](https://cloud.githubusercontent.com/assets/6022168/15559799/f6bcc108-22aa-11e6-96db-b55242e2fed3.png)

**Comment by lasercar** [comment]
I can stop the server directly inside screen (#196) so this isn't a huge issue.

**Comment by hexparrot** [comment]
Can you provide any details or logs?  `/var/log/mineos.log`

Are you doing this as a non-root user?

Also, have you tried updating the webui to something more recent?

**Comment by lasercar** [comment]
This only happens on the Docker version, so the user is `mc`.
How do I access that log file on Docker?

**Comment by hexparrot** [comment]
Is there a reason you installed using `docker`?  Are you familiar with navigating docker instances?

**Comment by hexparrot** [comment]
I am still unable  to reproduce this issue; bungee instances for me are all kill-able.  If you're able to provide a reproducible case (instructions to experience this issue), I can work with it, but as of now, I don't have enough information about your setup, *which* docker image you're using, etc.

Please do re-open if this is still needing resolution.
