### ISSUE TITLE
Error running BuildTools

### ISSUE THREAD

**Issue by lasercar** [hexparrot/mineos-node#198]
Running on Debian jessie, as root. This error happens when I try to build spigot using the webui.

```
Loading BuildTools version: git-BuildTools-afc7566-52 (#52)
fatal: $HOME not set
Git name not set, setting it to default value.
fatal: $HOME not set Exception in thread "main"
java.lang.RuntimeException: Error running command, return status !=0: [git, config, --global, user.name, BuildTools] at org.spigotmc.builder.Builder.runProcess(Builder.java:547) at org.spigotmc.builder.Builder.main(Builder.java:161)
```

**Comment by hexparrot** [comment]
What method of starting up the webui is in place, `supervisord`?

**Comment by lasercar** [comment]
Yes, I think it is `supervisord`. I basically copied the commands inside the Dockerfile and ran them on a fresh debian server.

**Comment by hexparrot** [comment]
Is there a reason you used the commands from the Dockerfile, rather than the commands specifically for Debian servers?

At any rate, it seems like its the MineOS webui not being started up with the ENV variables set for $HOME, which is typically done by supervisord.

Have you tried a non-root user to build?

**Comment by hexparrot** [comment]
Unable to reproduce this issue.  Using the docker commands for non-docker installations seems to muddy up the process, but it works when using the normal installation steps on Debian Jessie.  If you can provide additional details on your setup (and answer the above questions), we can re-open and explore.
