### ISSUE TITLE
Forge Profiles need support for branches

### ISSUE THREAD

**Issue by tgstyle** [hexparrot/mineos-node#201]
If you select the latest version of say 1.7.10 it fails to download because it has a branch attached to it.

**Comment by hexparrot** [comment]
Can you provide more detail about what you're trying to do?  I can see that when I attempt to download versions 1.7.10 (quite old), they actually fail with a server code 404, meaning the remote host is no longer hosting them.  What is the exact message you got from this?

**Comment by tgstyle** [comment]
All versions of forge have a branch attached to them from github, unless they are in the master branch. The link you are trying does not have the branch in the path. The 1.7.10 link is valid if you put the branch in the URL. You can still download any version of forge on their file server, they still host every version.

Valid URL:
http://files.minecraftforge.net/maven/net/minecraftforge/forge/1.7.10-10.13.4.1614-1.7.10/forge-1.7.10-10.13.4.1614-1.7.10-installer.jar

The forge JSON file contains all the proper branch information to fix the downloads.
http://files.minecraftforge.net/maven/net/minecraftforge/forge/json

**Comment by tgstyle** [comment]
Just to note, the 1.9.4 version did not work until it was moved in to the master branch.

**Comment by xannor** [comment]
I submitted a pull request [#204](https://github.com/hexparrot/mineos-node/pull/204) that should fix this and add 1.10 profiles to forge.

**Comment by hexparrot** [comment]
Corrected in commit: 93d11a13cc7d0a2858ee47327529c3a183bd66e9

Thank you for the issue reporting!
