### ISSUE TITLE
Spigot 1.10 buildtoold

### ISSUE THREAD

**Issue by seria2** [hexparrot/mineos-node#202]
Pls update Spigot/Craftbukkit profile to 1.10 version. BuildToold has been updated already.

**Comment by hexparrot** [comment]
This was a bug; the webui was cutting out all versions below 1.8.0, but 1.10 was being counted as lower (wrongly).  Now, 1.10 appears as expected as of commit ef3334a38f4c702846f3d59ce7dbf5e86f7b1688
