### ISSUE TITLE
Feature Request: Forge logs

### ISSUE THREAD

**Issue by firecrafty** [hexparrot/mineos-node#205]
On forge based servers, most of the loading information occurs in the fml log. It would be a nice feature if the webui could display these logs alongside the vanilla default latest.log (the forge latest log is called fml-server-latest.log)

**Comment by hexparrot** [comment]
Added in commit https://github.com/hexparrot/mineos-node/commit/7052ef4ee5cee11430145ac207b6c075b9e578ec.
