### ISSUE TITLE
Webui crashes upon server creation in FreeNAS 9.10

### ISSUE THREAD

**Issue by RedInquisitive** [hexparrot/mineos-node#207]
I know there are already issues with FreeNAS and mineos, but this issue seems mildly different from the rest. Anyway here it goes.
### The issue:
When creating a new server the webui crashes. It's not instant (the page seems to be cached), but if I refresh the browser I can no longer connect to the server
### Information:
FreeNAS 9.10

(I don't know what else to give. Ask away!)
### Logs:
```
{"level":"info","message":"[WEBUI] mcserver connected from 192.168.0.4","timestamp":"2016-07-08T02:37:41.147Z"}
{"level":"info","message":"[WEBUI] Downloading official profiles.","timestamp":"2016-07-08T02:37:41.234Z"}
{"command":"create","server_name":"WizardServer","properties":{"level-seed":"password","difficulty":"3","gamemode":"0","generate-structures":true},"level":"info","message":"[WEBUI] Received emit command from 192.168.0.4:mcserver","timestamp":"2016-07-08T02:37:55.925Z"}
{"date":"Thu Jul 07 2016 21:37:55 GMT-0500 (CDT)","process":{"pid":94927,"uid":0,"gid":0,"cwd":"/","execPath":"/usr/pbi/mineos-amd64/bin/node","version":"v0.10.31","argv":["/usr/pbi/mineos-amd64/bin/node","/usr/pbi/mineos-amd64/share/mineos/mineos-node/webui.js","start"],"memoryUsage":{"rss":86036480,"heapTotal":67487232,"heapUsed":40599544}},"os":{"loadavg":[0.32763671875,0.22802734375,0.2333984375],"uptime":3645},"trace":[{"column":18,"file":"fs.js","function":"Object.fs.readdirSync","line":665,"method":"fs.readdirSync","native":false},{"column":17,"file":"/usr/pbi/mineos-amd64/share/mineos/mineos-node/mineos.js","function":"Object.mineos.server_pids_up","line":53,"method":"mineos.server_pids_up","native":false},{"column":27,"file":"/usr/pbi/mineos-amd64/share/mineos/mineos-node/mineos.js","function":"self.property","line":1112,"method":"property","native":false},{"column":10,"file":"/usr/pbi/mineos-amd64/share/mineos/mineos-node/mineos.js","function":"self.verify","line":1287,"method":"verify","native":false},{"column":23,"file":"/usr/pbi/mineos-amd64/share/mineos/mineos-node/node_modules/async/lib/async.js","function":null,"line":767,"method":null,"native":false},{"column":13,"file":"/usr/pbi/mineos-amd64/share/mineos/mineos-node/node_modules/async/lib/async.js","function":null,"line":735,"method":null,"native":false},{"column":13,"file":"/usr/pbi/mineos-amd64/share/mineos/mineos-node/node_modules/async/lib/async.js","function":"iterate","line":253,"method":null,"native":false},{"column":29,"file":"/usr/pbi/mineos-amd64/share/mineos/mineos-node/node_modules/async/lib/async.js","function":null,"line":265,"method":null,"native":false},{"column":16,"file":"/usr/pbi/mineos-amd64/share/mineos/mineos-node/node_modules/async/lib/async.js","function":null,"line":37,"method":null,"native":false},{"column":17,"file":"/usr/pbi/mineos-amd64/share/mineos/mineos-node/node_modules/async/lib/async.js","function":null,"line":741,"method":null,"native":false}],"stack":["TypeError: path must be a string","    at Object.fs.readdirSync (fs.js:665:18)","    at Object.mineos.server_pids_up (/usr/pbi/mineos-amd64/share/mineos/mineos-node/mineos.js:53:17)","    at self.property (/usr/pbi/mineos-amd64/share/mineos/mineos-node/mineos.js:1112:27)","    at self.verify (/usr/pbi/mineos-amd64/share/mineos/mineos-node/mineos.js:1287:10)","    at /usr/pbi/mineos-amd64/share/mineos/mineos-node/node_modules/async/lib/async.js:767:23","    at /usr/pbi/mineos-amd64/share/mineos/mineos-node/node_modules/async/lib/async.js:735:13","    at iterate (/usr/pbi/mineos-amd64/share/mineos/mineos-node/node_modules/async/lib/async.js:253:13)","    at /usr/pbi/mineos-amd64/share/mineos/mineos-node/node_modules/async/lib/async.js:265:29","    at /usr/pbi/mineos-amd64/share/mineos/mineos-node/node_modules/async/lib/async.js:37:16","    at /usr/pbi/mineos-amd64/share/mineos/mineos-node/node_modules/async/lib/async.js:741:17"],"level":"error","message":"uncaughtException: path must be a string","timestamp":"2016-07-08T02:37:55.929Z"}
```
Also, there's this, but unrelated to the overall issue:
```
Loading BuildTools version: git-BuildTools-afc7566-52 (#52)
You must run this jar through bash (msysgit) 
```
Any ideas?

EDIT: Hmm... I tried updating it but it would no longer let me log in...

**Comment by hexparrot** [comment]
First question, what commit did you start at?
Next, what commit are you on right now?

Thirdly, has creating a server ever worked or did it give you this problem from the start?

Lastly, can you confirm this is the FreeNAS plugin, and not just an installation on FreeNAS?

**Comment by RedInquisitive** [comment]
1. I could not determine what version I was on when I began. The git commit button in the top right simply brought me to the latest commit in this repo.

2. I brought myself up to the most recent commit, 33b513b. I confirmed this through the build logs.

3. No, I have been unable to create a server.

4. It was the FreeNAS plugin, yes. I can build it from scratch in a FreeBSD 10 jail if needed though.

**Comment by thesymbol** [comment]
Can also confirm that creating servers on FreeNAS 9.10 is in fact not working, but instead of using the plugin I created a jail instead with the 9.10 template and followed the installation instructions on the wiki for mineos-node.

The loading of servers appear to be broken on FreeNAS (jail) aswell i tried to copy a server from a previous MineOS-Node install and it crashes during startup instead (the webui), but it can be that the configuration is too old if it has change alot (not sure).

Tried on 79108648a319915b05713b7252e42a06b33b513b (clean install).

**Comment by hexparrot** [comment]
@RedInquisitive The FreeNAS plugin seems to be running into a number of unsurmountable problems due to the nature of the plugin jail vs ...something.  You can see the relevant thread here #95.  At the bottom is the workaround offered by @josh4trunks, the maintainer of the MineOS FreeNAS plugin.

There's a lot that changes around, evidently, in both the build environment as well as a few other things I'm not too terribly well-versed in.  If possible, building from scratch is probably the best idea; in #95, there are numerous accounts of successful installations using the instructions provided in the FreeBSD wiki page.

**Comment by RedInquisitive** [comment]
Yes! The issue was resolved using the method described here: https://forums.freenas.org/index.php?threads/freenas-9-plugin-mineos.20122/page-22#post-300032

Thanks everyone!
