### ISSUE TITLE
don't do docker anymore?

### ISSUE THREAD

**Issue by boistordu** [hexparrot/mineos-node#212]
No docker anymore on your part?

**Comment by hexparrot** [comment]
https://github.com/hexparrot/mineos-docker ?

**Comment by boistordu** [comment]
I mean on the docker hub.  I can t make a pull anymore.  I have to go to mjerries/mineos-node.  Is that normal?

Télécharger Outlook pour Android<https://aka.ms/ghei36>



On Thu, Aug 11, 2016 at 12:45 AM +0200, "William Dizon" <notifications@github.com<mailto:notifications@github.com>> wrote:


https://github.com/hexparrot/mineos-docker ?

-

**Comment by hexparrot** [comment]
https://hub.docker.com/r/hexparrot/mineos/tags/

As best as I can tell, everything is still pull-able and working.

**Comment by boistordu** [comment]
Latest doesn't work.  So docker pull hexparror/mineos-node doesn't work.  But maybe with your different tags yes but I can't really understand how did you organise your image then

Télécharger Outlook pour Android<https://aka.ms/ghei36>



On Thu, Aug 11, 2016 at 4:07 AM +0200, "William Dizon" <notifications@github.com<mailto:notifications@github.com>> wrote:


https://hub.docker.com/r/hexparrot/mineos/tags/

As best as I can tell, everything is still pull-able and working.

-

**Comment by hexparrot** [comment]
There is no 'latest'.  From the repository, there are four different tags corresponding to four different distributions in the docker repo.

Since it is docker, for the most part the distributions are largely irrelevant--you would interface with just the service within, but not the distro, but I just wanted to compare and have a good variety.

```
root@willonubuntu:~# docker pull hexparrot/mineos:node-jessie
node-jessie: Pulling from hexparrot/mineos

5c90d4a2d1a8: Pull complete
84445fcce9d9: Pull complete
71e71715375a: Pull complete
d974eb8ffae3: Pull complete
75f0cff06906: Pull complete
6b6c6c57a271: Pull complete
45d2cb8bcd85: Pull complete
ea20d9bcd80e: Pull complete
Digest: sha256:abd0ba40bec6f698988c530dce90d1c97da431a957d0024f98fa5deb230faf07
Status: Downloaded newer image for hexparrot/mineos:node-jessie
```

**Comment by boistordu** [comment]
Mmmmh OK I understand does it give any improvement?

Télécharger Outlook pour Android<https://aka.ms/ghei36>



On Thu, Aug 11, 2016 at 5:23 PM +0200, "William Dizon" <notifications@github.com<mailto:notifications@github.com>> wrote:


There is no 'latest'. From the repository, there are four different tags corresponding to four different distributions in the docker repo.

Since it is docker, for the most part the distributions are largely irrelevant--you would interface with just the service within, but not the distro, but I just wanted to compare and have a good variety.

root@willonubuntu:~# docker pull hexparrot/mineos:node-jessie
node-jessie: Pulling from hexparrot/mineos

5c90d4a2d1a8: Pull complete
84445fcce9d9: Pull complete
71e71715375a: Pull complete
d974eb8ffae3: Pull complete
75f0cff06906: Pull complete
6b6c6c57a271: Pull complete
45d2cb8bcd85: Pull complete
ea20d9bcd80e: Pull complete
Digest: sha256:abd0ba40bec6f698988c530dce90d1c97da431a957d0024f98fa5deb230faf07
Status: Downloaded newer image for hexparrot/mineos:node-jessie


-

**Comment by hexparrot** [comment]
Improvement compared to?

No, for the most part all of the docker images will be identical in operation, though I'd recommend the node-jessie one, just because I'm a particular fan of Debian and I feel like it'll be the most well-kept image.

**Comment by boistordu** [comment]
Ok I was asking if one of the version were more stable than the others but okey I have my answer.  Sorry to have you disturb with all that.  I will try it now.

Télécharger Outlook pour Android<https://aka.ms/ghei36>



On Thu, Aug 11, 2016 at 8:51 PM +0200, "William Dizon" <notifications@github.com<mailto:notifications@github.com>> wrote:


Improvement compared to?

No, for the most part all of the docker images will be identical in operation, though I'd recommend the node-jessie one, just because I'm a particular fan of Debian and I feel like it'll be the most well-kept image.

-

**Comment by boistordu** [comment]
Will you do an update to download the forge installer.jar correctly and the last one?  Because I have a lot of download failed

Télécharger Outlook pour Android<https://aka.ms/ghei36>



On Thu, Aug 11, 2016 at 8:51 PM +0200, "William Dizon" <notifications@github.com<mailto:notifications@github.com>> wrote:


Improvement compared to?

No, for the most part all of the docker images will be identical in operation, though I'd recommend the node-jessie one, just because I'm a particular fan of Debian and I feel like it'll be the most well-kept image.

-

**Comment by hexparrot** [comment]
Is this related to docker?

**Comment by boistordu** [comment]
Ok
