### ISSUE TITLE
bug with docker after upgrade to 1.12.1

### ISSUE THREAD

**Issue by boistordu** [hexparrot/mineos-node#213]
Hi, 
my configuration is docker 1.12.1 on ubuntu 16.0.4.1.
I use your mineos-node and it seems since yesterday when they released the 1.12.1 docker engine version for ubuntu your docker is not responding well. 
To be exact the following updates have been committed to 16.04.1 : 
docker-engine python3-software-properties software-properties-common software-properties-gtk

so the container stop with the minecraft servers runing(3 to be exact).  Since this moment after 3 refresh of the graphs on your dashboard the UI become unresponsive, I can go on all the pages but I can't do any actions like start/stop a server etc... If I want to start a server then I need to be very quick and be able to go to the server and click on the start button before the average 3 refresh of the graphs. And of course to know if the server have started I need to refresh the UI and so login again. 
So I don't know if it is because the docker engine have been updated or the  other updates or the abrupt stop of the container but anyway I've already tried to stop the container, rm it and recreate it but with the same results. Any idea?

**Comment by boistordu** [comment]
by the way, I didn't try to restart yet the whole server, I wanted to diagnose that thing first if it's possible.

**Comment by hexparrot** [comment]
The issue you're experiencing is likely connected to a bug introduced recently by faulty parsing of a profile (Mianite) that changed their JSON list of available downloads.  This error is causing the webui to crash and restart.  

For more details: https://discourse.codeemo.com/t/web-ui-not-showing-profiles/1461/4?u=hexparrot

The solution is to update your commit to https://github.com/hexparrot/mineos-node/commit/37e4a9dce2fad1c00bc4e162dffebf27d8744839

**Comment by boistordu** [comment]
my commit from your docker? because it tells me that my image is up to dare when I try to docker pull...

**Comment by boistordu** [comment]
if you are talking about mineos-node commit yes it seems to be different but How do you I update it in the container? by the manual way? open a terminal in the container, look for the folder where you put it and do git clone ?

**Comment by hexparrot** [comment]
Yes, enter the started container and do the instructions as prescribed for normally updating the webui.

As you might suspect, the docker method of hosting MineOS is not particularly popular (not yet comprehensively documented either), mostly because it's a whole new layer of complexity the normal user doesn't benefit from.

One of the key benefits about the Docker instance is that all the actual Minecraft data files are separated from the docker instance (in the form of a volume).  Because of this, you could even create an image from the Dockerfile which will build the most recent webui commit (because it's built-in to download the latest).

**Comment by boistordu** [comment]
Yeah okey so you don't plan to update the docker each time there is a commit, then?  But why not to but a cronjob in the docker file to update automatically the webui?
I will propose then an update on you github in the next few days then to update automatically the webui.

Télécharger Outlook pour Android<https://aka.ms/ghei36>



On Sat, Aug 20, 2016 at 8:28 PM +0200, "William Dizon" <notifications@github.com<mailto:notifications@github.com>> wrote:


Yes, enter the started container and do the instructions as prescribed for normally updating the webui.

As you might suspect, the docker method of hosting MineOS is not particularly popular (not yet comprehensively documented either), mostly because it's a whole new layer of complexity the normal user doesn't benefit from.

One of the key benefits about the Docker instance is that all the actual Minecraft data files are separated from the docker instance (in the form of a volume). Because of this, you could even create an image from the Dockerfile which will build the most recent webui commit (because it's built-in to download the latest).

-

**Comment by boistordu** [comment]
Do you want another post to speak about the change to do to your docker for updating the UI with cronjob? I've used your script by the way, reset webui and then update webui. I don't know if you ve done those script for this purpose but at least it works even if it's not the best way to do it.

**Comment by boistordu** [comment]
By the way I have several question about some error in your container when trying to use npm and stuff, do you want also another post about it?

**Comment by hexparrot** [comment]
Feel free to open up as many github issues as you see are distinct issues.  Preferably, though, do it on the mineos-docker repo, https://github.com/hexparrot/mineos-docker
