### ISSUE TITLE
Browser uses

### ISSUE THREAD

**Issue by djoey123** [hexparrot/mineos-node#218]
When i boot up a FTB Infinity server my browser will crash because all the things it need to load of MineOS.
When the server is booting it makes a lot of logs that is automatich loaded by MineOS for realtime feedback.
Is there a fix for this problem because everytime i shutdown or start the server my browser will crash.

**Comment by hexparrot** [comment]
Do you have any information about this crash that you can provide?

Does `/var/log/mineos.log` show anything?  Can you provide any steps that I can reproduce this issue?

What commit are you on?

**Comment by djoey123** [comment]
It happens when I start an ftb Infinity evolved server.
Make a Ftb infinity evolved 2.6.0 server and run it will reproduce my issue.
/var/logs/mineos.log only shows I sended a Start command.
I think it is something with the logging or Load Averages

I use Firefox 48.0.2 on Chrome i got crashes to.
When i shutdown the server it will lagg the browser but not make it crash.

version: git commit: 8dc5529

**Comment by hexparrot** [comment]
Okay, well with the information you provided, I tried this out myself.

git commit: bea277f
Downloaded FTB Infinity 2.60
Profile -> FTBInfinity-2.6.0
Runnable Jar -> FTBServer.jar
Went in as user 'mc' to manually run "FTBInstall.sh"
Accepted EULA.
Set 2048 MB ram, hit 'start'

Everything worked without browser crash.
