### ISSUE TITLE
Bug: Webgui misreports available ram

### ISSUE THREAD

**Issue by ozhound** [hexparrot/mineos-node#221]
I have 32gb of ram on my Xeon server and running htop indicates that i am only using 8gb of ram (for a few VMs) but the Webgui with no servers installed (fresh install) indicate i only have 2.37GB Free.

**Comment by flareofghast** [comment]
You haven't given enough detail to tell what the bug is. 

Is the MineOS instance run in a Virtual Machine? 
If so, how much RAM have you allocated to the MineOS virtual machine?
What OS are you running, both on the host and on the MineOS client?

That's all I can think of at the moment.

**Comment by ozhound** [comment]
My apologies, would people run nested vms?

anyway

Its on hardware, no vm
Ubuntu 16.04 - clean install

Partial lshw below

  *-core
       description: Motherboard
       product: S1200BTL
       vendor: Intel Corporation
       physical id: 0
       version: E98681-352
     *-cpu
          description: CPU
          product: Intel(R) Xeon(R) CPU E3-1220 V2 @ 3.10GHz
    *-memory
          description: System Memory
          physical id: 41
          slot: System board or motherboard
          size: 32GiB

**Comment by flareofghast** [comment]
I don’t understand what you mean by nested vms.

You said you have 8GB RAM used for some VMs. Are you saying you run Ubuntu as your host OS and then you have 8 VMs but MineOS is not run in a VM?

Are you running the docker version?

**Comment by ozhound** [comment]
Hi, Lets just ignore the fact i mentioned VM's they arnt relevant

what is relevant that i have 24gb free ram and the Dashboard reports the
free ram as only 2.37gb free

im running Mineos-Node on commit d057581

I installed the program using this tutorial -
https://minecraft.codeemo.com/mineoswiki/index.php?title=MineOS-node_(apt-get)

i installed the program onto the server and NOT into a VM.

Thanks

**Comment by flareofghast** [comment]
Looks like MineOS uses a module called OS to handle that.

**Comment by flareofghast** [comment]
I don't think it's a problem with MineOS

**Comment by ozhound** [comment]
yeh could be 16.04 ubuntu. some things just dont work right on this
version. i knew i should have stayed with 14

**Comment by hexparrot** [comment]
Can you post the output of the command `free -h` as well as the value the webui is reporting at the same time?

My best guess is that you're seeing the lower 2.37 GB available because it's reporting free, unused memory, compared to htop which might be reporting free, unused memory + caches.

**Comment by ozhound** [comment]
total        used        free      shared  buff/cache
available
Mem:            31G         11G        223M        133M         19G
19G
Swap:           31G        294M         31G

interesting.

Looks like you are correct sir.

in this case if i add more servers will the ram simply be allocated from
the Available?

[image: Inline image 1]

**Comment by ozhound** [comment]
I tested this by adding another server, Mineos still reports the same free
space as free -h but mineos has pulled more memory from the swap pool to
create and run the extra server

maybe a code change to report the Swap Free instead of the Mem Free would
be more accurate.

[image: Inline image 1]

**Comment by ozhound** [comment]
I just restarted my server after an apt-upgrade command and now everything
seems to be ok

[image: Inline image 1]
