### ISSUE TITLE
Profiles are downloading incorrect server files(older versions)

### ISSUE THREAD

**Issue by mattk926** [hexparrot/mineos-node#226]
Example Direwolf20 1.10 pack version 1.2 and 1.2.1 it download the 1.4.1 version instead. Not sure where the profile list/link comes from but hopefully this is fixable. Workaround is to manually install the server files from the curse website but I thought I should bring it to someones attention.

see below for example of profiles

/var/games/minecraft/profiles/FTBPresentsDirewolf20110-1.2.1# vi version.json
{ "forgeVersion": "2171", "mcVersion": "1.10.2", "packVersion": "1.1.4", "packID": "FTBPresentsDirewolf20110", "xml": "modpacks" }

/var/games/minecraft/profiles/FTBPresentsDirewolf20110-1.2.0# vi version.json
{ "forgeVersion": "2171", "mcVersion": "1.10.2", "packVersion": "1.1.4", "packID": "FTBPresentsDirewolf20110", "xml": "modpacks" }

/var/games/minecraft/profiles/FTBPresentsDirewolf20110-1.1.4# vi version.json
{ "forgeVersion": "2171", "mcVersion": "1.10.2", "packVersion": "1.1.4", "packID": "FTBPresentsDirewolf20110", "xml": "modpacks" }

**Comment by hexparrot** [comment]
I identified and fixed this issue in a recent commit today: 1346c0b535d192ff65c72256016b0984f503542c

Fixing this issue (download via incorrectly formed URL) emerged an entirely different issue, unfortunately.  It so happens that these FTB Presents Direwolf packs are using a "storing" method that evidently is not compatible with the current unzip mechanism in nodejs.

https://github.com/glebdmitriew/node-unzip-2/issues/1

This means that with the updated commit, you will definitely get the right file downloaded, but it will, however, fail to extract the file.  Extracting the file manually does the trick (so you are saved the effort of downloading manually, only), but it is still an incomplete workflow.

The commit already made is live and good though, so please do update, and in the meantime I'll try to identify a new unzipping module that allows the entire process to happen in the webui.

**Comment by mattk926** [comment]
Thank you for all of your hard work, hopefully you can get the unzipping module figured out.

**Comment by hexparrot** [comment]
Alright, solved this in commit: 4bb4eb32939dc4e50d47811fe75940f14708becd

Using an entirely different module "adm-zip" _only_ if it fails.  All packages now download and extract as expected (you still will need to run the `FTBInstall.sh`, though!)
