### ISSUE TITLE
Segfault when starting Minecraft server

### ISSUE THREAD

**Issue by Athorcis** [hexparrot/mineos-node#230]
When i try to start the Minecraft server i work but mineos crashes

    info: [server_hartefak] 127.0.0.1 issued command : "start"
    info: [server_hartefak] received request "start"
    error: { [Error: connect ECONNREFUSED]
      code: 'ECONNREFUSED',
      errno: 'ECONNREFUSED',
      syscall: 'connect' }
    error: { [Error: connect ECONNREFUSED]
      code: 'ECONNREFUSED',
      errno: 'ECONNREFUSED',
      syscall: 'connect' }
    error: { [Error: connect ECONNREFUSED]
      code: 'ECONNREFUSED',
      errno: 'ECONNREFUSED',
      syscall: 'connect' }
    Erreur de segmentation

And if i try to restart mineos it crashes until the Minecraft server is stopped.

**Comment by hexparrot** [comment]
A few questions:

1) is this the first server you're trying to set up? (no other servers running, etc.)
2) have you restarted the host and the problem persists?
3) what settings did you fill in for this server that are changing the default?
4) what install is this, MineOS Turnkey?  Installed on a self-installed distro?

**Comment by Athorcis** [comment]
1. yes this is the first time i use MineOS
2. i did but the problem is still there
3. I tried with the default settings and it didn't worked either, but my settings are:

         use_https = false
         socket_host = '127.0.0.1'
         socket_port = 8080
         base_directory = '/var/games/minecraft'

         webui_locale = 'fr_FR'
4. I installed mineos-node from git and i'm on Debian 8

**Comment by hexparrot** [comment]
`socket_host = '127.0.0.1'`
`use_https = false`

Why did you make these changes?  They will adversely affect the way the webui works.  For example, HTTPS....really has no reason to be off, and socket host 127.0.0.1 will actually prevent requests from properly executing because it's only going to be listening from an IP that your desktop isn't going to be originating from.

I suggest you try and successfully get a vanilla server up _with no modifications_ and see if the error persists.

**Comment by Athorcis** [comment]
I did these changes to have MineOS behind Apache on port 443.
I resetted /etc/mineos.conf but it's still crashing.
I did not changed the ip and the port for the minecraft server
I'll try to install MineOS on a fresh VM and i'll let you know

**Comment by Athorcis** [comment]
When I tried to install it on a fresh vm the installed version of node v0.10.x, which caused npm install to failed, so I installed v0.12.18 and it worked.
 I installed a new copy of node v0.12.8 (because that was already the version I was supposed to have) on my host, I deleted the node_modules folder in /usr/games/minecraft, then ran npm install again and it worked
I have an error though `Cannot bind broadcaster to ip` should i ignore it
