### ISSUE TITLE
Update always ready

### ISSUE THREAD

**Issue by clowrym** [hexparrot/mineos-node#231]
I am using Docker on an Unraid system. Mineos always shows as an update being available, but fails to pull anything when I try. I do see the following error in my docker logs:

`time="2017-02-17T15:59:57.749546995-07:00" level=error msg="Handler for POST /images/create returned error: Error parsing reference: \"hexparrot/mineos:node-jessie:latest\" is not a valid repository/tag" `

**Comment by hexparrot** [comment]
I'm not familiar with Unraid, but the error is referring to `hexparrot/mineos:node-jessie:latest`.  The actual tag is `hexparrot/mineos:node-jessie`.  Is there a means for you to adjust the tag it is trying to download?

**Comment by clowrym** [comment]
Looking at the settings, I don't have latest specified, I'll have to find out where it comes from...
![screen shot 2017-02-18 at 9 35 23 am](https://cloud.githubusercontent.com/assets/25108950/23094894/32eebba4-f5be-11e6-9197-2b32f3fd9df0.png)

**Comment by clowrym** [comment]
I believe Unraid always looks for a tag "latest" when looking for updates, I don't see anywhere this tag is noted in the config files.

**Comment by clowrym** [comment]
I thought maybe this was an issue with unraid, but Reviewing Docker hub & the tagging on all other repo's , everyone has tagged their latest version as latest, Where this one is tagged as :node-jessie, not latest. I beleive it is part of docker, or maybe unraid to add ":latest" when checking for updates.

A few examples:

https://hub.docker.com/r/mjeries/mineos-node/tags/
https://hub.docker.com/r/itzg/minecraft-server/tags/
https://hub.docker.com/r/kitematic/minecraft/tags/

**Comment by hexparrot** [comment]
I have aliased hexparrot/mineos:node-jessie as hexparrot/mineos:latest.  Can you confirm this works as you expect?

**Comment by clowrym** [comment]
Perfectly, Thank you for looking into this!!


![capture](https://cloud.githubusercontent.com/assets/25108950/23572202/aeb840b8-002a-11e7-91d7-5affafd1d6cc.JPG)
