### ISSUE TITLE
Again, 100% CPU used

### ISSUE THREAD

**Issue by DaveDevil** [hexparrot/mineos-node#233]
Hello,

I read about issues #102 and #146 

I think i have the same problem here. I'm running python MineOS with 5 really big servers (Vanilla is hitting 80gb) and everything works fine.

Now we are moving to a new machine, and i installed MineOS node. After the login, the webui freezes (Debian 8.7 LAMP).

I reinstalled all the SO (Debian 8.7 minimal) and now the webui works fine. I Imported bungee server (c.a 40mb) and it works. Now that i imported the Minigame server, webui.js is always over 100% CPU usage, and i can't even login in the webui.

I read that you blacklisted world and plugins folder from analysis, but my server is using MultiVerse, so i don't have "world" folder with map and player files (c.a. 50.000 files) but these files are present in other world folders with other names.

**Comment by hexparrot** [comment]
Can you try the fireworm_tracking branch to see if it resolves this issue?

Additional information on changing branches can be found here: https://minecraft.codeemo.com/mineoswiki/index.php?title=Trying_New_Features#fireworm_tracking

(or use the internet resource of your choice).   Be sure to restart the webui afterward.

**Comment by hexparrot** [comment]
I believe this issue should have been solved with #235.  In this commit, upon webui startup, all existing directories (such as the unnamed one you reference with 50k files) should be auto-skipped from being tracked.  This should also have resolved any issues with CPU tracking them, memory tracking them, and IO traversing the tree.

Please, of course, re-open this if the issue persists even now.
