### ISSUE TITLE
PaperTool move to PaperClip

### ISSUE THREAD

**Issue by MrBretze** [hexparrot/mineos-node#236]
PaperTool links dont work and the project has been changed by a new name: https://aquifermc.org/

**Comment by hexparrot** [comment]
Thanks for the update. Can you confirm that paperclip now is simply a normal jar, and doesn't require any amount of compilation/building forever going forward?

If so, then I guess PaperSpigot will be entirely removed from the webui and Paperclip will be added as a profile.

**Comment by MrBretze** [comment]
Yes paperclip is a simply jar file and auto compile the selected version

**Comment by MrBretze** [comment]
https://ci.destroystokyo.com/job/PaperSpigot/

**Comment by hexparrot** [comment]
Clarify: there's no compiling anymore, right?  It's simply a jarfile you download, like, say, vanilla.

**Comment by MrBretze** [comment]
Yes is a simple jarfile

**Comment by hexparrot** [comment]
Paperspigot added!

https://github.com/hexparrot/mineos-node/commit/c2db54e32013a5c6e4b42c455b3413b8655f2d3d

**Comment by MrBretze** [comment]
Thanks

**Comment by MrBretze** [comment]
The update cant not be downloaded a PaperSpigot

**Comment by MrBretze** [comment]
So its fix, i juste run reset_webui.sh

**Comment by adamwbb** [comment]
papertools no longer exists 
it is now paperclip.
This jar can patch itself once and become a fully usable server jar.

https://ci.destroystokyo.com/job/PaperSpigot/lastSuccessfulBuild/artifact/paperclip.jar
