### ISSUE TITLE
module node-userid version 0.2.0 no longer works with FreeBSD 11

### ISSUE THREAD

**Issue by jsegaert** [hexparrot/mineos-node#240]
It builds fine when I up the dependency from "0.2.x" to "0.3.x" in package.json

I tested with "userid": "0.3.x" in both FreeBSD 10.3 and 11, and both build fine.  
Maybe it's time to up the version?

**Comment by hexparrot** [comment]
Userid 0.3.x seems to work OK on my test cases, so I've gone and updated it along with a few other modules.

3a63e0079c00c47ad28c2d085531cef2aa42bf13

**Comment by jsegaert** [comment]
I tested the new commit, and it works like a charm.  Thank you for your quick response!
