### ISSUE TITLE
Crafbukkit is now missing

### ISSUE THREAD

**Issue by clowrym** [hexparrot/mineos-node#248]
Not sure if this is a bug, or intentional, but Craftbukkit build tools is now missing from MineOS-node. Currently running the latest build of Docker on unraid

![image](https://user-images.githubusercontent.com/25108950/27203493-5c1f8694-51e3-11e7-9278-7b923d834403.png)

**Comment by hexparrot** [comment]
I removed paperspigot back here: effe3a0e2c4725112a6d3c24fe0605019c2fc5f6

At the time (this past March) the profile was broken.  Perhaps they've revived it?  I'll take a look.

Possibly related: https://discourse.codeemo.com/t/paper-spigot-dont-compile/1138/3

**Comment by clowrym** [comment]
craftbukkit and Paper spigot are different i believe? maybe i'm confused!!

**Comment by hexparrot** [comment]
Well, in that case, how long ago was it there?  Because this space has been empty since Mar 22, 2017.

**Comment by clowrym** [comment]
Probably March, I don't usually use bukkit, but I was having an issue with Redstone in one of my servers, so I figured I would try it!! No big deal if it's not there, I thought they were different, so I didn't realize that was what was removed back in march

**Comment by hexparrot** [comment]
I'm doing some [renovation work on profiles](https://github.com/hexparrot/mineos-node/tree/profiles) right now, so it's as good a time as any to see if things should be added and removed.

I'll take a look at craftbukkit and see about its inclusion.  Spigot is mostly craftbukkit, but from many accounts, ... [improved](https://www.spigotmc.org/threads/spigot-vs-craftbukkit-vs-bukkit.36646/)?

**Comment by clowrym** [comment]
Spigot is better in my opinion, for the amount I would use bukkit, don't bother adding it just for me! I can manually download

**Comment by clowrym** [comment]
just maybe remove the Craftbukkit reference on the main page menu

**Comment by hexparrot** [comment]
Removed references to craftbukkit in en_US.  Couldn't remove it from foreign locales without corrupting the file, so I left them untouched for now.

**Comment by clowrym** [comment]
excellent!! Thanks!!
