### ISSUE TITLE
dgram branch

### ISSUE THREAD

**Issue by flareofghast** [hexparrot/mineos-node#25]
An issue with your dgram branch is that you haven't followed the format for the broadcast message.

it MUST be 

```
"[MOTD]" + servers[i][0] + "[/MOTD][AD]" + servers[i][1] + "[/AD]"
```

where servers[i][0] is the servers MOTD and servers[i][1] is the servers port.

I tried implementing myself but I couldn't get the value back for server-port or motd, I'm still a noob. If I manage to get it before you come back online you'll see a pull request.

**Comment by hexparrot** [comment]
Even though it wasn't committed to the dgram branch, I still have had no success using your provided script, or this one, modified which I expect to work as well (which *does* use the prescribed broadcast format).

    var dgram = require('dgram');
    var socket = dgram.createSocket("udp4");
    var broadcastIP = "255.255.255.255"
    var broadcastPort = 4445

    // allow broadcast
    socket.bind( function(){
        socket.setBroadcast(true);
    });

    // run broadcast method every 1500 ms
    setInterval(broadcast,1500);

    function broadcast() {
        var msg =  new Buffer("[MOTD]" + 'hi' + "[/MOTD][AD]" + '25565' + "[/AD]");
        socket.send(msg, 0, msg.length, broadcastPort, broadcastIP, function(err, bytes) {
            // call back, launches this code once message is sent
            console.log('sent', msg.toString())
        });
    }

does this work for you?

**Comment by flareofghast** [comment]
yep

![screen shot 2015-05-01 at 12 23 14 am](https://cloud.githubusercontent.com/assets/1791927/7415487/652d9118-ef98-11e4-8f74-7dd86c45e0f3.png)

using node 0.10.32
This is very odd how things are not working the same between you and I. I have tested that code on both my Mac and a VM running ubuntu server.

**Comment by flareofghast** [comment]
What sort of network hardware do you have? Maybe it's squelching the broadcast packets?

**Comment by flareofghast** [comment]
![screen shot 2015-05-01 at 12 50 42 am](https://cloud.githubusercontent.com/assets/1791927/7416131/5b3beab6-ef9c-11e4-81d7-aabacbfe3312.png)


Your code works.

**Comment by hexparrot** [comment]
Yeah, this morning it became apparent to me that something along the chain was wrecking my UDP broadcasts from being shown--in addition to the nodejs attempt, I also tried the original Python which showed nothing.

Figured at that point I should just trust the code works and commit it and move on--if there was any more attention it needed it could get it later...after all, this whole week has pretty much been one huge impedance of momentum :-1: 

On to the next issue/feature!   ...what will it be, anyway... aside from auth what's essential for a pre-release?

**Comment by TheDoctorsLife** [comment]
restore points and profiles is what I can think off the top of my head.

**Comment by hexparrot** [comment]
Anything specifc about restore point?

Profiles is close on the list to work on, but it is still being delayed until I can find a suitable means to always know the most recent versions of releases, e.g., RSS feeds, parse-able text files or a URL pattern a la Mojang's.

**Comment by kalvindukes** [comment]
@hexparrot regarding Broadcasts: unless set up explicitly for it, no gateway will pass broadcasts across network borders. So eg. if your servers reside within an extranet-to-DMZ-to-Intranet-like setup, no broadcasts from the DMZ will ever reach you, and vice versa. (dunno how firm you are at that point, so sorry for sounding like smart ass)

Anyway, maybe new momentum and motivation will come alongside the new helping hands and brains. :)

Regarding Profiles: I'm afraid we can't keep up with each and every modpack and release out there, anyway. Maybe it's best to let the admins do updates to custom profile URLs themselves.
But you're talking about listing official Mojang releases only here, right?

**Comment by hexparrot** [comment]
@kalvindukes in my case, it was two computers on the same subnet (physically next to eachother and were peers).  Not so much a concern anymore, though.

Regarding profiles, I don't really want admins to do updates with custom profiles because admins seemingly didn't get how it worked.  They got confused everywhere from unescaped characters in the URL, the fact they're immutable, the fact they download to a directory *then* copied to the live server directory, and then also that new profiles simply get placed atop the old ones, and that command line scripts were often needing to be run as an unprivileged user.

There really *has* to be a better way, and I can program it--I just don't want to have to commit version bumps on my own.
