### ISSUE TITLE
Service will not start.

### ISSUE THREAD

**Issue by xannor** [hexparrot/mineos-node#254]
A recent "breaking" change caused the mineos service to fail with a invalid path error in the logs. I traced it to this line:

https://github.com/hexparrot/mineos-node/commit/45bc2279abf86e7a48279c84f577bd8db8a47de1/server.js#diff-78c12f5adc1848d13b1c6f07055d996eR546

The change from passing the base_dir to user_config.base_directory will throw an error if no config file is found. This is because without a config the user_config is empty thus all properties are undefined. 

A simple fix would be either to require a config file or create a valid default config object.

I worked around this by creating the config file in /etc, so it is not a major issue but something that should be fixed via design.

**Comment by hexparrot** [comment]
Addressed in #255.  I definitely would prefer the mineos.conf to exist, even if I have previously created code that allowed graceful handling of its absence.

webui startup will abort and error out with message. Thanks!
