### ISSUE TITLE
Changing server profile breaks server ownership

### ISSUE THREAD

**Issue by LoicUV** [hexparrot/mineos-node#264]
When I create a server, and want to choose a downloaded profile to assign it to, it breaks the ownership (`Server Owner: undefined (undefined)`, blank `Group Owner` and `Space used by live server files: NaNundefined`. It also empties the Java Settings dropdown. Mineos logs only display the `modify_sc` command.

```bash
{"level":"info","message":"[patate] miner (10.0.2.100) joined server namespace","timestamp":"2017-11-03T17:05:29.373Z"}
{"level":"info","message":"[patate] 10.0.2.100 issued command : \"modify_sc\"","timestamp":"2017-11-03T17:05:36.512Z"}
{"level":"info","message":"[patate] received request \"modify_sc\"","timestamp":"2017-11-03T17:05:36.513Z"}
```
![error](https://user-images.githubusercontent.com/592542/32386781-a4e2cb0e-c0c2-11e7-97b6-2f2e482e752d.png)

Specs : debian 4.7 with java8 and everything needed from the install tutorial

EDIT : after that when I try to select the Group Owner back to `miner (1001)`, it says chown failed, the dropdown stays empty, but it sets the Server Owner back to `miner (1000)` and mineos.log shows : 

```bash
{"level":"info","message":"[patate] 10.0.2.100 issued command : \"chown\"","timestamp":"2017-11-03T17:16:02.612Z"}
{"command":"chown","uid":null,"gid":1001,"uuid":"ab28d740-c0ba-11e7-9b9f-7f12da732a85","time_initiated":1509729362612,"success":false,"err":"You may not change the user owner of the server.","time_resolved":1509729362613,"level":"error","message":"[patate] command \"chown\" errored out:","timestamp":"2017-11-03T17:16:02.613Z"}
```

**Comment by hexparrot** [comment]
Problem was linked to this change: 55604b584db46ec4064ec71c8aabb009882a9709

I have reverted this change;  update to the latest commit of mineos-node to resolve.

**Comment by LoicUV** [comment]
I reverted, but the problem doesn't seem to go away, it's very inconsistent. First time it didn't happen when changing the profile, and I managed to start the server, but then it broke down when accepting the EULA terms (removed the selected .jar). After that whenever I change the runnable .jar or the profile it does break everything again.

**Comment by hexparrot** [comment]
Can you confirm you restarted the webui process afterward?

Also, please provide the `/var/log/mineos.log` if possible, for any hints at the problem's cause.

**Comment by LoicUV** [comment]
Oh I did not, my bad, I even checked the github commit, saw it was `55604b5` and thought that it was  the good one :/ It works now, thanks !
