### ISSUE TITLE
Restore Points and Archives sorting in Web UI is not coherent.

### ISSUE THREAD

**Issue by k-dueb** [hexparrot/mineos-node#268]
Would it be possible to align the Archives sorting on the Restore Points sorting, please?
(It's a minor annoyance but it bugs me every time.)

Currently they are sorted as follow in the Web UI:
- Restore Points are sorted by newest first.
- Archives are sorted by oldest first.

I think changing both to newest first would make more sense. What do you think?

**Comment by hexparrot** [comment]
Fixed so that archives are now sorted with the most recent listed first.

83a146a1c54f285a0e2aa4b51bdead29cd145ac1
