### ISSUE TITLE
Possible issues with node dependencies

### ISSUE THREAD

**Issue by flareofghast** [hexparrot/mineos-node#277]
Just installed a new mineos and got these warnings in the npm install step.
```
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN deprecated du@0.1.0: no longer maintained
npm WARN deprecated graceful-fs@3.0.11: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN deprecated natives@1.1.3: This module relies on Node.js's internals and will break at some point. Do not use it, and update to graceful-fs@4.x.
```

it may not matter due to using an older node version but thought I would put it here in case you need to investigate.

**Comment by hexparrot** [comment]
Working on this right now.  Node 8x is going to be the next, fully supported Node for MineOS-node.

**Comment by hexparrot** [comment]
npm modules have been widely updated now for the use of NodeJS v8.  While it does not mean all node modules are without their varying vulns, it appears we have at least resolved the deprecated modules.

If you're able to upgrade to node 8.11, I would recommend doing so--it does not appear to have introduced any compatibility issues thus far (and likely has resolved countless unidentified issues from older versions of modules and node).

**Comment by hexparrot** [comment]
The upgrade to node 8 seems to have gone rather smoothly--over the past month or so, issues have cropped up, but typically not around the `npm` compatibility of the node8 branch.  If you run into any further breaking issues, please let me know.

Thanks!
