### ISSUE TITLE
issue minecraft console command

### ISSUE THREAD

**Issue by repomanz** [hexparrot/mineos-node#289]

**Comment by repomanz** [comment]
Currently in my logs; forge is prompting me to issue a /fml command.   I see in your summary this appears to be supported but unsure how this is done.    Can you explain how this is done via the docker or some other tool?

**Comment by lol7344** [comment]
Open latest.log section and write your /fml command. I don't know why but be sure to include the / when entering forge commands. All the other server commands do not require the /.
