### ISSUE TITLE
Can't get Java Settings Back

### ISSUE THREAD

**Issue by MeanJay** [hexparrot/mineos-node#299]
Sorry - stupid question...

I did "something" in the webui while setting my server java arguments and now I have a "Console" window in that screen and no ability to view/edit the java args.

How can I get the default UI java arguments back?  I've tried everything including updating the whole WebUI from the bash script.  I figured that would reset the ui but it did not.

Otherwise, MineOS + WebUI is awesome!

J.D.

![mineos-console](https://user-images.githubusercontent.com/54730461/64057934-40be7280-cb61-11e9-95eb-b237575e92e1.jpg)

**Comment by MrTechGadget** [comment]
I’m pretty sure that when you check the “not a conventional Minecraft server” box, you can’t edit the java memory.

**Comment by MeanJay** [comment]
Yep!  That was the ticket.  Thank you!

**Comment by MrTechGadget** [comment]
👏

**Comment by MrTechGadget** [comment]
@meanjay if you can close/cancel this issue that would be great.

**Comment by MeanJay** [comment]
You got it.  Thanks for the assist.
