### ISSUE TITLE
BuildTools not ran with Increased JVM Memory as necessary

### ISSUE THREAD

**Issue by dreamwraith** [hexparrot/mineos-node#301]
Keep receiving the following message when trying to use buildtools to build spigot, etc. System has plenty of ram, but it appears MineOS just runs with whatever JVM defaults - need option and/or default to override JVM Defaults for Memory footprint for build-tools. People tend to keep their defaults low for several reasons, and having to change defaults to get the interface to work seems like a bad idea. 

For my case, my server runs in a VM with Dynamic Ram allocation, so the server might report low ram to an application checking the ram available, but will increase ram size when ram is requested.

`BuildTools requires at least 512M of memory to run (1024M recommended), but has only detected 218M. This can often occur if you are running a 32-bit system, or one with low RAM.`

**Comment by dreamwraith** [comment]
Created Pull request with a simple fix that could be expanded upon https://github.com/hexparrot/mineos-node/pull/302

**Comment by hexparrot** [comment]
Merged in!  Thanks for the contribution, simple and to the point!
