### ISSUE TITLE
imports not working on FreeBSD

### ISSUE THREAD

**Issue by cross** [hexparrot/mineos-node#313]
It looks like the fix for #61 switched to using tar, but using "--force-local" which is not a valid argument for the tar in FreeBSD (12.1).

I'd hate to think that GNU tar would be a requirement, so can you adapt based on the installed   Actually, looking at man page on a Linux machine, why is --force-local needed in the first place?

**Comment by cross** [comment]
Okay.  Looking around the web more, it seems that GNU tar has a "feature" that treats filenames of "host:filename" specially.  To avoid that "special" behavior, they added this option.  I assume it was needed here because the archival filenames contain timestamps with colons.

I can confirm that putting a path specifier in front of the filename also makes tar do the right thing (locally).  If the tar command is always run from within the `imports` directory, we can just prepend `./` to the filename.  If it is called with a longer path-spec, then this should be a non-issue.

**Comment by cross** [comment]
Looking at `mineos.js:409`, it looks like the argument to tar is _always_ a fully qualified path.  I'm just going to remove the `--force-local`.  Unless there's a reason I can't see to keep it, I suggest we commit that change.

**Comment by cross** [comment]
Confirmed that it works for me to import an archive from a python mineOS server, using the U/I in mineos-node.   Let me know if you'd like me to prep a PR, but it's just removing that one element from that args list.

**Comment by cross** [comment]
Hey @hexparrot .  I know this isn't high priority for you, but if you could merge in the small number of IMO "easily agreed" PRs I've submitted, I would appreciate it.  Let me know if you have any questions or concerns!

**Comment by hexparrot** [comment]
Merged, thank you for your efforts!
