### ISSUE TITLE
Cant find the files for the server

### ISSUE THREAD

**Issue by matthew42904** [hexparrot/mineos-node#335]
Im running mineos on my unraid server and I cant find any of the files i need to add plugins to the server.

**Comment by matthew42904** [comment]
where is that located in unraid because i cant find that anywhere?

**Comment by Simmons928** [comment]
Matthew, in the settings for the docker in unraid. Look at the "Minecraft Files" variable. This is where you will set the location of the server files.
Example, My server is mapped to /mnt/cache/appdata/minecraft/

**Comment by matthew42904** [comment]
thank you so much!! i fixed it
