### ISSUE TITLE
Can't remove the xmx/xms values completely

### ISSUE THREAD

**Issue by flareofghast** [hexparrot/mineos-node#34]
I noticed that the top one on the page has a default value (or something). I have tried blanking both fields but it's not allowed.

**Comment by hexparrot** [comment]
The startup script for the java instance depends on the XMX value having a length greater than 0.  When absent, XMX is populated by the corresponding XMX value.  However, there shouldn't be anything stopping you from blanking it out--there should only be a restriction from starting the server (and a popup should appear).

Here's what I get when I remove the default 256 (note, after 1500ms or clicking elsewhere, the value is committed, no [enter] is necessary).

server_fin { command: 'modify_sc',
  section: 'java',
  property: 'java_xmx',
  new_value: '',
  uuid: '8cf1b010-f409-11e4-b297-578ac9075729',
  time_initiated: 1430928258449,
  success: true,
  err: null,
  time_resolved: 1430928258452 }

**Comment by flareofghast** [comment]
I thought blanking it would remove the arguments from the start command. Why is it necessary to set that?

**Comment by hexparrot** [comment]
@flareofghast In this case it is my own personal restriction; host uptime and stability are at risk if the JVM is left to its own devices about how much memory it is allowed.  Without explicitly limiting the Java heap size--in a calculated fashion, taking into consideration Java overhead and Linux overhead--the jar will feel no restriction in taking up as much RAM as it wants.  This could result in a situation where a greedy (and maybe leaky) server wants to take up much more than it safely should, and the host systems services could fail or falter, or less dramatically, the server just starts swapping.  

In the event of completely exhausted memory, the *only* service that should suffer is the Minecraft server, not the host services themselves, whether it is the webui or SSH--but the host services can start to suffer if the server starts swapping.

All in all--and especially with multiple servers running on one host--an admin should be able to know how much they want a single process to be able to consume and to know the bounds of their server demands and place it into a XMX value, in my opinion.

**Comment by flareofghast** [comment]
Ok.
