### ISSUE TITLE
Manage plugins?

### ISSUE THREAD

**Issue by CorruptedPixl** [hexparrot/mineos-node#347]
I'm running MineOS from a docker container on my NAS and am unable to find a way to manage plugins on live servers. I could create an archive, download it, add a plugin, then re-import it but that seems like a hassle. I looked around a bit and saw there's sftp support on other MineOS versions?

Currently I have the import path linked to a volume on the nas to import server archives, is there maybe a path to see the files of a running server?

It could be that I missed something, if so please let me know :D

**Comment by Indemnity83** [comment]
Your NAS should have mapped the `/var/games/minecraft` volume somewhere more persistent ... if you go to that mapped location you should be able to see the servers and add plugins/mods.

**Comment by CorruptedPixl** [comment]
I tried manually mapping that to a volume on the nas, and it works, but it doesn't copy the old server data to the new volume, it just loads from the (empty) new one. Any way to copy it over?

**Comment by 4o66** [comment]
By default, if you did not specify a mapped folder, the docker container will create a volume at /var/lib/docker/volumes/[volume name]/_data, which is normally only accessible to root.
To get the volume name and path, you can run `docker inspect [container name]|grep Mounts -A10`

Once you have the old path, make sure the container is stopped and run `rsync -av /var/lib/docker/volumes/[volume name]/_data/ /[path to new location]/` Note that the source patch ends with a forward-slash
