### ISSUE TITLE
Installation Failure

### ISSUE THREAD

**Issue by chokoth** [hexparrot/mineos-node#348]
I am trying to install mineos on a new debian 10 system using the instructions [here](https://minecraft.codeemo.com/mineoswiki/index.php?title=MineOS-node_(apt-get%2Bsystemd)).

When I get to the step "npm install --unsafe-perm" I get the following error:

make: Entering directory '/usr/games/minecraft/node_modules/posix/build'
  CXX(target) Release/obj.target/posix/src/posix.o
make: g++: Command not found
make: *** [posix.target.mk:111: Release/obj.target/posix/src/posix.o] Error 127
make: Leaving directory '/usr/games/minecraft/node_modules/posix/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_module                      s/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proces                      s.js:275:12)
gyp ERR! System Linux 4.19.0-8-amd64
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gy                      p/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/games/minecraft/node_modules/posix
gyp ERR! node -v v13.12.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! posix@4.2.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the posix@4.2.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-04-07T18_43_01_707Z-debug.log

I've attached the 
[log](https://github.com/hexparrot/mineos-node/files/4446479/2020-04-07T18_43_01_707Z-debug.log) mentioned to this post.

From what I could see, my only guess was somehow getting a corrupt installation of node.js. I removed that, cleaned apt-get, and re-installed it. However that seemed to make no difference.

I'm not sure if I'm missing some other dependency or if there is something going on that I'm missing.

Some system information: Debian 10 running on Virtualbox. 16gb of ram, 3 processors. All extended features within virtualbox are enabled.

Please let me know if I can provide further information.

**Comment by hexparrot** [comment]
`gyp ERR! node -v v13.12.0`

It appears you're using node 13, which is (I think) still not currently capable of correctly compiling the `npm` module `posix`.

You're also getting this error: `make: g++: Command not found` which suggests you did not yet successfully install `apt-get install build-essential`.

**Comment by hexparrot** [comment]
I successfully installed MineOS on Debian 10 using these slightly revised instructions:

https://minecraft.codeemo.com/mineoswiki/index.php?title=MineOS-node_(apt-get)_(Debian10)

Basic changes include using a more modern Java (openjdk-11-jre-headless) and ensuring `rsync` is installed.  Otherwise, everything else is the same.  There is no need to start anew, you should be able to follow these instructions to get up to spec with a working system.

**Comment by chokoth** [comment]
Wow, fast response! Thank you!

I'm not sure how the Debian guys decided a release without build-essentials was a good idea, but that got me past that issue. 

Now I'm having problems registering the service. It appears that on Debian 10 supervisor is no longer installed. I assume I need to do something with sysctl, but I'm unsure of the process. I'm trying to look it up now to see if I can figure out how to register correctly.

**Comment by chokoth** [comment]
Just want to note. I did have to restart, actually had to completely re-install the system (it was a virtual machine, nothing lost) in order to get a profile list. I assume it's related to running node 13, but I can't be sure. Thank you again for all your work on this!
