### ISSUE TITLE
PaperSpigot CI server moved, "Latest Paper" downloads 1.12.2

### ISSUE THREAD

**Issue by MFeldpausch** [hexparrot/mineos-node#349]
The CI server for paper used to be located at [ci.destroystokyo.com](ci.destroystokyo.com).  It is now located at [papermc.io/ci/](papermc.io/ci/).  The old releases are located at [papermc.io/ci/job/Paper/](https://papermc.io/ci/job/Paper/) while the new ones are each in their own job with each version.
[1.13](https://papermc.io/ci/job/Paper-1.13/)
[1.14](https://papermc.io/ci/job/Paper-1.14/)
[1.15](https://papermc.io/ci/job/Paper-1.15/)
Here are all of the URLs that will pull the paperclip.jar for each version from the CI.
1.8.8: https://papermc.io/ci/job/Paper/443/artifact/Paperclip.jar
1.9.4: https://papermc.io/ci/job/Paper/773/artifact/paperclip.jar
1.10.2: https://papermc.io/ci/job/Paper/916/artifact/paperclip.jar
1.11.2: https://papermc.io/ci/job/Paper/1104/artifact/paperclip.jar
1.12.2: https://papermc.io/ci/job/Paper/latest/artifact/paperclip.jar
1.13.2: https://papermc.io/ci/job/Paper-1.13/latest/artifact/paperclip.jar
1.14.4: https://papermc.io/ci/job/Paper-1.14/latest/artifact/paperclip.jar
1.15.2: https://papermc.io/ci/job/Paper-1.15/latest/artifact/paperclip.jar
There does not seems to be a way to pull the latest build of the latest Minecraft version, at least from what I can tell.
There is also an api that can pull versions.  The api page is at [https://papermc.io/api/v1/paper/](https://papermc.io/api/v1/paper/)
The api download links are at papermc.io/api/v1/paper/\<mc-version\>/latest/download

**Comment by MFeldpausch** [comment]
My friend and I modified the `profiles.js` file to automatically pull the version list from the API.  I will start a pull request as soon as we finish testing everything.

**Comment by repomanz** [comment]
@MFeldpausch has this code been merged into the main branch? Would love to get papermc working in mine-os node.

**Comment by hexparrot** [comment]
@repomanz this has been merged into the main branch as of today: b3fdd0b227ab04ceb742e7666c96caad96d158bc
