### ISSUE TITLE
[bug] Cannot build spigot jar files

### ISSUE THREAD

**Issue by dark-swordsman** [hexparrot/mineos-node#360]
Hello. Currently trying to build 1.15.2 with spigot on the web interface, as shown here:

![image](https://user-images.githubusercontent.com/7909209/84953460-c4296000-b0b0-11ea-868f-712914ad966a.png)

Tailing the mineos logs shows the following:

```

{"builder":{"id":"BuildTools-latest","time":1592429765689,"releaseTime":1592429765689,"type":"release","group":"spigot","webui_desc":"Latest BuildTools.jar for building Spigot/Craftbukkit","weight":0,"filename":"BuildTools.jar","downloaded":true,"version":0,"release_version":"","url":"https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar","$$hashKey":"object:1082"},"version":"1.15.2","command":"build_jar","level":"info","message":"[WEBUI] BuildTools starting with arguments:","timestamp":"2020-06-17T21:36:11.313Z"}
{"level":"error","message":"stderr: Error: Invalid or corrupt jarfile /var/games/minecraft/profiles/spigot_1.15.2/BuildTools.jar\n","timestamp":"2020-06-17T21:36:11.313Z"}
{"level":"info","message":"[WEBUI] BuildTools jar compilation finished unsuccessfully in /var/games/minecraft/profiles/spigot_1.15.2","timestamp":"2020-06-17T21:36:11.313Z"}
{"level":"info","message":"[WEBUI] Buildtools used: /var/games/minecraft/profiles/spigot_1.15.2/BuildTools.jar","timestamp":"2020-06-17T21:36:11.314Z"}
```

It seems it's failing because of a newline `\n` character at the end of the url? No exactly sure.

I'm going to try the manual method shown [here](https://discourse.codeemo.com/t/spigot-1-11-2-jar-creation-fails-with-buildtools/1753/3), but it'd be nice to have this fixed.

**Comment by hexparrot** [comment]
The \n would only be part of the reported error, but shouldn't be part of the actual paths used internally.  Can you check the contents of this command and see if it matches?

[root@rcmc ~]# md5sum /var/games/minecraft/profiles/spigot_1.15.2/BuildTools.jar
a8f71446b818fe9eab70e0d7290bf930  /var/games/minecraft/profiles/spigot_1.15.2/BuildTools.jar

**Comment by dark-swordsman** [comment]
Hi hex, thanks for the reply.

The result of my hash check was the following which seems to be different.

```
7b5ea53ba332630e5aca8e4abb807f70  /var/games/minecraft/profiles/spigot_1.15.2/BuildTools.jar
```

I also tried the method in the forum post I sent above.

Got caught with:

```
Error: Invalid or corrupt jarfile BuildTools.jar
```

I decided to just do the following:

1. Went to my server folder
2. Used `wget https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar`
3. Renamed the default `minecraft_server_1.15.2.jar` to something different
4. Ran buildtools, which completed successfully.

Checking the hash of that new build tools that I manually installed is the same as yours.

Now I am setting the jar file for the server to the spigot one, doesn't start. Same thing with the default minecraft jar.

Looking at the mineos tail, this is all I see:

```
{"level":"info","message":"[test1] root (73.95.78.50) joined server namespace","timestamp":"2020-06-17T22:04:20.611Z"}
{"level":"info","message":"[test1] 73.95.78.50 issued command : \"modify_sc\"","timestamp":"2020-06-17T22:04:28.492Z"}
{"level":"info","message":"[test1] received request \"modify_sc\"","timestamp":"2020-06-17T22:04:28.492Z"}
{"level":"info","message":"[test1] 73.95.78.50 issued command : \"modify_sc\"","timestamp":"2020-06-17T22:04:30.200Z"}
{"level":"info","message":"[test1] received request \"modify_sc\"","timestamp":"2020-06-17T22:04:30.200Z"}
{"level":"info","message":"[test1] 73.95.78.50 issued command : \"modify_sc\"","timestamp":"2020-06-17T22:04:33.668Z"}
{"level":"info","message":"[test1] received request \"modify_sc\"","timestamp":"2020-06-17T22:04:33.668Z"}
{"level":"info","message":"[test1] 73.95.78.50 issued command : \"start\"","timestamp":"2020-06-17T22:04:35.981Z"}
{"level":"info","message":"[test1] received request \"start\"","timestamp":"2020-06-17T22:04:35.982Z"}
```

Not sure if there is another place to log, because all it's telling me is that "start" isn't doing anything but sending an HTTP requests . Also, while it does save some settings, it doesn't save the jar file or profile, which I find odd.

**Comment by hexparrot** [comment]
It's uncertain what sort of installation you're using, and one of the main issues with 1.15 and beyond is the requirement to use Java 1.8 or higher.  A server starting, but doing nothing exhibits the same symptoms you're seeing.

But also, it could be that you're doing stuff as `root`.

Here's what you can do:

1. I see you're logging in as `root`.  This isn't the ideal user to do any webui stuff in.  It causes problems because `root` will steal ownership of files if they were previously owned by another user.
2. Do you use a non-root user?  If not, a) then that's not the issue, but also b) we should address this and have you start doing everything as an unprivileged user.
3. Provide the output to `java -version`:

    [mc@rcmc minecraft]$ java -version
    openjdk version "1.8.0_252"
    OpenJDK Runtime Environment (build 1.8.0_252-b09)
    OpenJDK 64-Bit Server VM (build 25.252-b09, mixed mode)

IMO, the solution is moments away, we just need to know whats up with 1-3.

**Comment by dark-swordsman** [comment]
As far as installation goes, I used the script you supplied [here](https://minecraft.codeemo.com/mineoswiki/index.php?title=MineOS-node_(apt-get)). This is number 2 under "Deployment Overview". [This script](https://gist.github.com/hexparrot/1a7a2881d6c951d693d6).

I ran it as root as suggested. After that, I made a separate user with sudo, then logged in with that user. 

Trying to create a server, I can access the "create server" functionality, but the server gets lost. It doesn't appear in the server dropdown list towards the top. Because of this, I gave up and just tried running them as root. 

Since you say "unpriviledged user", should I be doing it as a non-sudo user? 

For Java Version:
```
openjdk version "11.0.7" 2020-04-14
OpenJDK Runtime Environment (build 11.0.7+10-post-Ubuntu-3ubuntu1)
OpenJDK 64-Bit Server VM (build 11.0.7+10-post-Ubuntu-3ubuntu1, mixed mode, sharing)
```
This is via the `default-jre-headless` part of the script.

At this point, I've already moved onto AMP and will be trying Pterodactyl, so I'm not sure if I will be able to continue debugging since this already has had so many issues. But I'll let you know if we try it again.

**Comment by hexparrot** [comment]
That's fine.  Seems like comments on https://gist.github.com/hexparrot/1a7a2881d6c951d693d6 here suggest that newer versions of Debian/Ubuntu may have made this script no longer work, where it was known working before.

But I understand your frustration and desire to move on.  Thanks for your patience and hope your next attempts have success!
