### ISSUE TITLE
Default login to Web UI

### ISSUE THREAD

**Issue by jfkerekes** [hexparrot/mineos-node#377]
I can't find anything that gives me the default login to the Web UI. I can get to the login page but I have no idea what the username and password are and was never prompted to set one so I assume there is a default.

**Comment by jfkerekes** [comment]
Update: So I found where to set the web ui password but I can't find anything that tells me the user name

**Comment by Chickenagent007** [comment]
How can I update the Web Ui

**Comment by hexparrot** [comment]
@jfkerekes There is no default login; the webui uses any Linux non-system usernames and their respective passwords.

If you've installed the webui manually, use any non-root user.  If you've installed via MineOS Turnkey ISO, you have an `mc` user which you were explicitly prompted to set the password for during installation.  Alternatively, you could create your own user and set a password, and that would be enough, too.

@Chickenagent007 Updating the webui: https://minecraft.codeemo.com/mineoswiki/index.php?title=Updating_the_Webui
