### ISSUE TITLE
Authentication system with express/socketio

### ISSUE THREAD

**Issue by hexparrot** [hexparrot/mineos-node#40]
Authentication is probably the biggest hurdle before being able to form a release candidate which admins could put to the test as a development/testing environment.

I understand that the codebase I have created is fairly large and may not be immediately familiar, so the help I'm asking for does not need to--in any way--include, fork, or remotely relate to this git.

I'm hoping to get a working example of Express 4.x + socketio 1.3 that can authenticate a hard-coded user (no need to worry about Linux shadow passwords).  Even 'admin:password' would work wonderfully. 

Whether you use passport (+passport-local, passport.socketio, etc) or not, any piece of code that can accomplish the following task will greatly push forward the status of this project:  *I must be able to access the user "admin" (or whatever username) from the socket object.*

The socket object--through middleware--should be able to be modified to contain this (this is the goal of passport.socketio).  Again, this code can be 100% without MineOS code or html.  Anything that can get the socket object to provide the authenticated username will be the answer to the entire authentication issue and I can adapt it to make it work with the webui.

**Comment by hexparrot** [comment]
In addition to Express 4.x and socketio 1.3, I ask to find code that does *not* depend on MongoDB--any other session store should do, for the most part, e.g., cookies, memorystore, etc.

**Comment by flareofghast** [comment]
Yeah sorry I have been MIA for a little while. I just haven't had the time to give this a go. I do think I could do it with passport.socketio with my auth branch with out much more bother but just don't currently have time to look into it.

**Comment by hexparrot** [comment]
implemented with https://github.com/hexparrot/mineos-node/tree/authorization
