### ISSUE TITLE
Forge Profile Not Showing in Drop-Down

### ISSUE THREAD

**Issue by abermudez1718** [hexparrot/mineos-node#402]
I tried to create a Forge server recently and saw that in "Profiles" under "Available Server Jars/Packs" its not listed anymore. I checked the link in the source code https://github.com/hexparrot/mineos-node/blob/master/profiles.js#L227. (https://files.minecraftforge.net/net/minecraftforge/forge/promotions.json) and was greeted with a "404 Not Found message." It seems the promotions.json file was removed. We can still get to the following at least: https://files.minecraftforge.net/net/minecraftforge/forge/.

I would update the profiles.js and submit a pull request but I'm not too proficient in any of these HTML, CSS, or Javascript to write decent test case. I don't know the type of appropriate front-end design pattern to implement as a work-around for this issue. My skill sets lie in build systems and backend programming languages.

**Comment by hexparrot** [comment]
It's unfortunate we lost the autogenerated list of all the versions.  Since forge is dead on the vine because of this, I've made a separate branch to address Forge with a few hardcoded versions in the meantime.  Can you verify if this works for you:

https://github.com/hexparrot/mineos-node/tree/forgeupdate

**Comment by abermudez1718** [comment]
@hexparrot I did some investigation and found an interesting line in the logs when installing forge manually and booting it.

`[22Apr2021 23:14:33.480] [Forge Version Check/INFO] [net.minecraftforge.fml.VersionChecker/]: [forge] Starting version check at https://files.minecraftforge.net/maven/net/minecraftforge/forge/promotions_slim.json`. 

![InterestingLine](https://user-images.githubusercontent.com/24358651/115813715-ab20c800-a3c1-11eb-8a59-bd4c9ec831a6.JPG)

Going to that link gives us a list of versions. Maybe we could use that.

**Comment by abermudez1718** [comment]
@hexparrot Finished testing the https://github.com/hexparrot/mineos-node/tree/forgeupdate branch. Works well but there is a typo in the versions. Lines https://github.com/hexparrot/mineos-node/blob/forgeupdate/profiles.js#L231 and https://github.com/hexparrot/mineos-node/blob/forgeupdate/profiles.js#L237 are duplicates. It's missing ` { mcver: '1.16.5', forgever: '36.1.5' },`

**Comment by hexparrot** [comment]
https://github.com/hexparrot/mineos-node/commit/603d9c58b2b52b66098bbe0dfac2645a115d9c47

Commit made thanks to promotions_slim.json.  This was the perfect find!  This fix has been pushed to master, closing this branch.
