### ISSUE TITLE
Profiles not showing up in the menu

### ISSUE THREAD

**Issue by mrhanman** [hexparrot/mineos-node#406]
Some profiles are not showing up in the menu. The following is from the log, and each of these are the missing profiles. This still occurs even when using the latest profiles.js from github.

`{"level":"error","message":"Unable to retrieve profile: forge. The definition for this profile may be improperly formed or is pointing to an invalid URI.","timestamp":"2021-05-24T03:37:53.696Z"}
{"level":"error","message":"Unable to retrieve profile: ftb_third_party. The definition for this profile may be improperly formed or is pointing to an invalid URI.","timestamp":"2021-05-24T03:37:53.974Z"}
{"level":"error","message":"Unable to retrieve profile: ftb. The definition for this profile may be improperly formed or is pointing to an invalid URI.","timestamp":"2021-05-24T03:37:53.978Z"}
{"level":"error","message":"Unable to retrieve profile: mojang. The definition for this profile may be improperly formed or is pointing to an invalid URI.","timestamp":"2021-05-24T03:37:53.978Z"}`

**Comment by RossComputerGuy** [comment]
What was the solution? I'm having this issue on TrueNAS Core.

**Comment by mrhanman** [comment]
I never figured it out. For me, the solution was to stop using mineos and switch to [AMP](https://cubecoders.com/AMP).
