### ISSUE TITLE
Update dockerfile to use java 16

### ISSUE THREAD

**Issue by brandonmcclure** [hexparrot/mineos-node#416]
I use the `hexparrot/mineos:latest` image and would like to update the base image/java version that it is using to accommodate some of my plugins (and in preparation for 1.17+)

I have a draft [PR](https://github.com/brandonmcclure/mineos-node/pull/1/files) on my fork for the branch that I am playing around with this on. I outline some of my findings/issues below and would like others thoughts so that I don't go too far into the weeds on my customizations that they become difficult to merge back in.  (IE it matches up with the work done for #396 )

**Comment by brandonmcclure** [comment]
From what [I could tell](https://tracker.debian.org/pkg/openjdk-16), the openJDK 16 binaries are currently in the Sid release/repo still and are not released as stable. I tried to add the Sid repos to a buster and stretch base image and `apt install openjdk-jfre-headless` from the sid repo, but I ran into issues with the libc6 dependency and abandoned that route... 

I then used the `sid-slim` base image, and I can install the v16 package with:
```
RUN mkdir -p /usr/share/man/man1 && apt-get install -y openjdk-16-jre-headless
```
I spin up a container with this image and I can confirm that the the correct `java -version` is running, and when I connect to a server through the minecraft client my world edit plugin is working now! However when I connect through the web ui I get authentication failures... 

Digging into that it looks like debian is making a change to the [default hashing algorithm](https://www.debian.org/releases/testing/amd64/release-notes/ch-information.en.html#pam-default-password) from sha512 to yescrypt, and I can see that [auth.js](https://github.com/hexparrot/mineos-node/blob/master/auth.js) is hardcoded to use sha512crypt. There is a way to change the default hashing algorithm back to sha215 in debian, so I am going to try that and test out my custom sid image some more and will update this issue with what I find out!

**Comment by fuzzybair** [comment]
Java 16 is not LTS so I was a little concerned with this request but according to https://help.minecraft.net/hc/en-us/articles/360035131371-Minecraft-Java-Edition-system-requirements- "The Caves and Cliffs update of Minecraft (1.17): Java Edition requires Java 16. ".

**Comment by fuzzybair** [comment]
@brandonmcclure I created a PR #421 I was able to create two vanilla Minecraft server instances using the UI v1.16.5 and 1.17. My container is using Ubuntu 20.04 with Java 16. Ubuntu 20.04 is a stable and release LTS my personal preference is that over the unreleased Debian Sid

**Comment by hexparrot** [comment]
#421 merged, so the new docker builds should properly work with 1.17.

With regard to MineOS turnkey, I've resorted to AdoptOpenJDK binaries, so I didn't need to pull in from Sid.  Appears to work identically.
