### ISSUE TITLE
Java version information

### ISSUE THREAD

**Issue by flareofghast** [hexparrot/mineos-node#42]
I just realised I did this in bash for something else I am working on, maybe it would be of benefit to you.

```
/usr/libexec/java_home -V 2>&1 | grep 86 | awk -F ":" '{print $1}' > java
# pattern="([0-9] [0-9])"
sed -i -e 's/[ \t]*//' java
IFS=$'\n' read -d '' -r -a newJava < java
rm java


OIFS="$IFS"
IFS=([0-9] [0-9])
newJAVA=""
while [[ $newJAVA = "" ]]; do
        echo "Select your Java version for this instance"
        select newJAVA in ${newJava[@]}; do
                if [[ $newJAVA = "" ]]; then
                        echo "Please enter a valid option. Retry."
                else {
                        export JAVA_HOME=`/usr/libexec/java_home -v $newJAVA` 
                        echo $JAVA_HOME
                        echo `java -version`
                }
                fi
                break
                done
        done
IFS="$OIFS"
# exit 0
````

It only applies for the current session/terminal unless you run it as "source script.sh"
Hope it helps.

**Comment by flareofghast** [comment]
This might solve one part of the issue. 
http://stackoverflow.com/a/19734810/2818567

**Comment by hexparrot** [comment]
A few months later, it appears the need for this was not as I had initially expected.  Most people use a single version of Java and once it's working, they seem to stick with it.  Closing this until there's a pressing use case for multiple java version selection from the webui.
