### ISSUE TITLE
Java 1.18 not loading on MineOS Docker since latest MC update

### ISSUE THREAD

**Issue by muntedewok** [hexparrot/mineos-node#450]
Hey guys,

It would appear the version of jre in the MineOS docker needs to be updated in order for 1.18 server to launch. No issues with 1.17.1 and below as version is supported by the jre version present.

Can you please advise when this is going to be updated and pushed out, or if there is a way to perform this task manually.

Regards,

-Chris

**Comment by flareofghast** [comment]
I think you might be able to update the dockerfile but I am not sure how that is achieved.

**Comment by muntedewok** [comment]
> I think you might be able to update the dockerfile but I am not sure how that is achieved.

Yeah I'm happy to do this however not sure how to go about it. Actually maintaining the Docker image and releasing updates would be handy though.

**Comment by flareofghast** [comment]
I haven’t heard from hexparrot in a while and he hasn’t been active from June/July last year. We might need to move it to a fork. 
Hope he’s doing well though.

**Comment by EndlessUndo** [comment]
> Can you please advise when this is going to be updated and pushed out, or if there is a way to perform this task manually.

Try attaching with a terminal to the docker container and run this as root:

`apt-get update && apt-get install -y openjdk-17-jre-headless`

Worked for me!

**Comment by muntedewok** [comment]
> > Can you please advise when this is going to be updated and pushed out, or if there is a way to perform this task manually.
> 
> Try attaching with a terminal to the docker container console and run this as root:
> 
> `apt-get update && apt-get install -y openjdk-17-jre-headless`
> 
> Worked for me!

Didn't actually think to find out where the JRE repository was to perform a manual update >.< Worked fine, cheers :)

**Comment by thetruetype** [comment]
I have this problem now, nothing happens when I press start.
On my PC I had 1.17 installed and tried to run the server but it didn't work. Updated to java 1.18 on PC and it worked.
However I cannot intall java 1.18 in mineos docker.
If I try "apt-get update && apt-get install -y openjdk-18-jre-headless" it gives error that it can't be found.

**Comment by EndlessUndo** [comment]
> If I try "apt-get update && apt-get install -y openjdk-18-jre-headless" it gives error that it can't be found.

Try this command instead:
`apt-get update && apt-get install -y openjdk-17-jre-headless`

> I cannot intall java 1.18 in mineos docker.

Minecraft java 1.18 requires java jdk 17, but it seems you are trying to install java jdk 18, which may be the issue. Just to clear up any confusion: The java jdk (the server) and minecraft java version (the game running on the server) are not the same thing, even though they both are refered to as java. Until recently minecraft used java jdk 8, but changed to java jdk 17 in minecraft 1.18, which broke the docker container for all minecraft 1.18+ servers.

I hope this resolves your issue!

**Comment by thetruetype** [comment]
I got it working now, it was minecraft 1.12.2 that required java 1.8 `apt-get install openjdk-8-jdk` after that it was able to run! :)
