### ISSUE TITLE
logs/latest.log does not show up when selecting server from dropdown

### ISSUE THREAD

**Issue by cookiedabaker** [hexparrot/mineos-node#460]
When first loading into the MineOS dashboard (e.g. refreshing the page), the only tabs available are those under the "Host Settings" until a server is selected. At this point, the server dropdown menu at the top of the page is blank as no server is selected. 

If you select a server from this dropdown, then the "Server Settings" and "Backup and Restores" become available, but the "Logging" section remains empty (_logs/latest.log_ does not show up). _logs.latest.log_ will show up if you select the server from the server list below the "Load Averages" pane on the Dashboard. At this point, _logs/latest.log_ will show up, and will switch/update when selecting a server from the dropdown at the top of the window.

**Comment by ZEBaker98** [comment]
This issue was introduced when I overhauled the UI's request system to put less load on the server. I didn't realize that the menu-bar doesn't use the `change_page` function to change the current server but instead changes the current server directly. Pull request https://github.com/hexparrot/mineos-node/pull/461 fixes this issue.

**Comment by sandersac** [comment]
I am hitting this issue as well, but unfortunately @cookiedabaker's workaround is not working for me, so I have to open up the docker container and view the logs manually.

**Comment by ZEBaker98** [comment]
Have you tried using the links on the dashboard to switch between servers? They should not be affected by this issue. @hexparrot anything I can do to speed up the acceptance of pull request #461?

**Comment by sandersac** [comment]
Just gave that a try and no dice, unfortunately. I am running MineOS from the latest hexparrot/mineos image, though that looks to be a few commits behind github master
