### ISSUE TITLE
Question about changing directory for backup and archives only

### ISSUE THREAD

**Issue by pupshadow** [hexparrot/mineos-node#464]
Hello my question is can I change the base_dir for my own location for backup and archive in: `mineos.js`

> mineos.mc = function(server_name, base_dir) {

>  var self = this;
>  self.server_name = server_name;

>  process.umask(0002);

>  self.env = {
>    base_dir: base_dir,
>    cwd: path.join(base_dir, mineos.DIRS['servers'], server_name),
>    bwd: path.join(base_dir, mineos.DIRS['backup'], server_name),
>    awd: path.join(base_dir, mineos.DIRS['archive'], server_name),
>    pwd: path.join(base_dir, mineos.DIRS['profiles']),
>    sp: path.join(base_dir, mineos.DIRS['servers'], server_name, 'server.properties'),
>    sc: path.join(base_dir, mineos.DIRS['servers'], server_name, 'server.config'),
>    cc: path.join(base_dir, mineos.DIRS['servers'], server_name, 'cron.config')
>  }

If you would be able to point me in the right direction this would be amazing because I dont want to change the running location for anything else just the backup and archive.

**Comment by flareofghast** [comment]
For awd and bwd you should be able to change to wherever you want.

**Comment by pupshadow** [comment]
Would I just change the base_dir  to what I want the location for? like awd: path.join(**{filelocation}**, mineos.DIRS['archive'], server_name)

**Comment by ZEBaker98** [comment]
If you don't want to mess with the code you can also accomplish the same thing using linux symbolic links

`ln -s <target_file> <link_name>`

For example, if I had an external hard drive names MC-Backups mounted at `/mnt/MC-Backups` and there was a folder called backup on that drive I wanted to store my backups in, I could run the following commang.

`ln -s /mnt/MC-Backups/backup /var/games/minecraft/backup`

The same works for archives.

`ln -s /mnt/MC-Backups/arcive /var/games/minecraft/archive`

You may want to rename the old folders beforehand using `mv` so you can recover the files if something goes wrong.

```
cd /var/games/minecraft
mv archive archive-old
mv backup backup-old
```

**Comment by flareofghast** [comment]
Good point @ZEBaker98

**Comment by pupshadow** [comment]
> If you don't want to mess with the code you can also accomplish the same thing using linux symbolic links
> 
> `ln -s <target_file> <link_name>`
> 
> For example, if I had an external hard drive named MC-Backups mounted at `/mnt/MC-Backups` and there was a folder called backup on that drive I wanted to store my backups in, I could run the following commang.
> 
> `ln -s /mnt/MC-Backups/backup /var/games/minecraft/backup`
> 
> The same works for archives.
> 
> `ln -s /mnt/MC-Backups/arcive /var/games/minecraft/archive`
> 
> You may want to rename the old folders beforehand using `mv` so you can recover the files if something goes wrong.
> 
> ```
> cd /var/games/minecraft
> mv archive archive-old
> mv backup backup-old
> ```

I was just trying to learn the method for changing it in the future but this sounds like it will work better for my instance since I'm using a special data drive for all data that isn't needed for quick access. Thank you for your help with this question.
