### ISSUE TITLE
Trigger Update to Docker Hub

### ISSUE THREAD

**Issue by valeryan** [hexparrot/mineos-node#476]
Docker Hub has not been updated in 9 months but the last update to the docker file that fixes Minecraft 1.18 was updated 3 months ago. https://hub.docker.com/r/hexparrot/mineos

**Comment by hexparrot** [comment]
Updated.  This delay is going to be repeated, as docker hub now requires manual pushes unless using a paid subscription, rather than the previously-offered free docker builds from the Dockerfile.

**Comment by valeryan** [comment]
Wow that dumb, Docker is really trying to force people into paying. I wonder if the reverse is possible, using a GitHub action to trigger a manual docker build. I will look into that as I have some docker images of my own and I did not realize they took auto builds away...
