### ISSUE TITLE
fatal: could not create work tree dir 'minecraft': Permission denied

### ISSUE THREAD

**Issue by Canoidian** [hexparrot/mineos-node#482]
When I try to create this in /usr/games I get fatal: could not create work tree dir 'minecraft': Permission denied. What do I do

**Comment by flareofghast** [comment]
Git clone needs to be run as root. 
the instructions detail the steps.

**Comment by Canoidian** [comment]
It worked thanks.

**Comment by flareofghast** [comment]
Good to hear. Are you able to close this?
