### ISSUE TITLE
mineos: ERROR (spawn error)

### ISSUE THREAD

**Issue by Canoidian** [hexparrot/mineos-node#483]
What do I do? When I typed supervisorctl start mineos

**Comment by flareofghast** [comment]
Without any other information it could be a lot of things. I personally have had issues where mineos was looking for node but it wasn’t in the right location. Check your launch file and your node location.  
perhaps you should try mineos distro?

**Comment by flareofghast** [comment]
If it is that error you can find out if it is that it can’t find node. 
In the console type ‘sudo which node’ 
If it doesn’t say /usr/bin/node you’ll need to create a symlink or change the service file.
