### ISSUE TITLE
Doesn't work.

### ISSUE THREAD

**Issue by davidbdyer** [hexparrot/mineos-node#495]
Does not work, I followed the instructions to a T. I tried it on Debian, Ubuntu, TrueNas and Docker. Profiles either don't load or take a really long time to show up and download even slower than that. When i create a server it never starts. I've resorted to just setting up Minecraft server in a LXC on ProxMox.

**Comment by hexparrot** [comment]
Having also followed the instructions, I can still succeed in installing MineOS.

For it to have failed, consistently, on 3 fundamentally different installation sets is a concern, but it does not appear to be one I can reproduce with the information provided.

If you have the interest in sharing any error output you received, we can explore this further, but if you are already set with your LXC/Proxmox solution, then no worries.

**Comment by davidbdyer** [comment]
I’ve been a system admin for 20yrs and ai couldn’t get it. It doesn’t work on TrueNAS with the community jail, in Docker, with the ISO in a VM or installing the GUI on top of Debian or Ubuntu. The first 3 options are canned solutions.

**Comment by davidbdyer** [comment]
I didn't say it didn't install, I said the software doesn't work. Oddly after I tried it there were attempts to access my servers remotely and I've never had that happen before.

**Comment by hexparrot** [comment]
WeOkay, well having followed the install instructions, I was able to get it to work.

I appreciate that you have been a system administrator for 20 years, though, it would help me, a fellow system administrator and the software developer to get more actionable information than "it doesn't work".

There are log files, there is console output. These are in standard places, e.g., /var/log.  If all we get is 

'Doesn't work. #495'

> Does not work, I followed the instructions to a T. I tried it on Debian, Ubuntu, TrueNas and Docker. Profiles either don't load or take a really long time to show up and download even slower than that. When i create a server it never starts. I've resorted to just setting up Minecraft server in a LXC on ProxMox.

then I hope you can understand how hobbled I am at helping.   At any rate, you are very insistent it doesn't work, so I apologize for your experience.

**Comment by davidbdyer** [comment]
I understand logs help. There is nothing unique about me running the docker-compose provided and the logs generated in the first 5-10 minutes of operation.

mineos.log
`{"level":"info","message":"Starting up server, using commit: b6e0d1e Update rootless.md\n","timestamp":"2022-08-08T23:01:36.890Z"}
{"level":"info","message":"[WEBUI] mc connected from 192.168.21.106","timestamp":"2022-08-08T23:02:24.625Z"}
{"level":"info","message":"/usr/games/minecraft/profiles.d","timestamp":"2022-08-08T23:02:24.724Z"}
{"0":"de_DE","1":"en_US","2":"fr_FR","3":"it_IT","4":"ja_JP","5":"no_NB","6":"ru_RU","7":"sv_SE","level":"info","message":"","timestamp":"2022-08-08T23:02:24.753Z"}
{"level":"info","message":"Downloaded information for collection: BungeeCord (10 entries)","timestamp":"2022-08-08T23:02:25.044Z"}
{"level":"info","message":"Downloaded information for collection: Forge Mod (61 entries)","timestamp":"2022-08-08T23:02:25.082Z"}
{"level":"info","message":"Downloaded information for collection: Feed the Beast Third-Party Server Packs - old (278 entries)","timestamp":"2022-08-08T23:02:25.365Z"}
{"level":"info","message":"Downloaded information for collection: Imagicalmine (1 entries)","timestamp":"2022-08-08T23:02:25.367Z"}
{"level":"info","message":"Downloaded information for collection: Cuberite C++ Server (4 entries)","timestamp":"2022-08-08T23:02:25.368Z"}
{"level":"info","message":"Downloaded information for collection: Feed the Beast Server Packs - old (566 entries)","timestamp":"2022-08-08T23:02:25.558Z"}
{"level":"info","message":"Downloaded information for collection: Nukkit (2 entries)","timestamp":"2022-08-08T23:02:25.559Z"}
{"level":"info","message":"Downloaded information for collection: Mojang Official Minecraft Jars (593 entries)","timestamp":"2022-08-08T23:02:25.653Z"}
{"level":"info","message":"Downloaded information for collection: Spigot (1 entries)","timestamp":"2022-08-08T23:02:25.956Z"}
{"level":"info","message":"Downloaded information for collection: Mianite (23 entries)","timestamp":"2022-08-08T23:02:25.964Z"}
{"redownload":true,"command":"refresh_profile_list","level":"info","message":"[WEBUI] Received emit command from 192.168.21.106:mc","timestamp":"2022-08-08T23:02:29.700Z"}
{"level":"info","message":"Starting up server, using commit: b6e0d1e Update rootless.md\n","timestamp":"2022-08-08T23:04:23.115Z"}
{"level":"info","message":"[WEBUI] mc connected from 192.168.21.106","timestamp":"2022-08-08T23:11:02.450Z"}
{"level":"info","message":"/usr/games/minecraft/profiles.d","timestamp":"2022-08-08T23:11:02.540Z"}
{"0":"de_DE","1":"en_US","2":"fr_FR","3":"it_IT","4":"ja_JP","5":"no_NB","6":"ru_RU","7":"sv_SE","level":"info","message":"","timestamp":"2022-08-08T23:11:02.569Z"}
{"level":"info","message":"Downloaded information for collection: BungeeCord (10 entries)","timestamp":"2022-08-08T23:11:02.903Z"}
{"level":"info","message":"Downloaded information for collection: Forge Mod (61 entries)","timestamp":"2022-08-08T23:11:02.907Z"}
{"level":"info","message":"Downloaded information for collection: Cuberite C++ Server (4 entries)","timestamp":"2022-08-08T23:11:03.178Z"}
{"level":"info","message":"Downloaded information for collection: Imagicalmine (1 entries)","timestamp":"2022-08-08T23:11:03.178Z"}
{"level":"info","message":"Downloaded information for collection: Feed the Beast Server Packs - old (566 entries)","timestamp":"2022-08-08T23:11:03.324Z"}
{"level":"info","message":"Downloaded information for collection: Feed the Beast Third-Party Server Packs - old (278 entries)","timestamp":"2022-08-08T23:11:03.400Z"}
{"level":"info","message":"Downloaded information for collection: Nukkit (2 entries)","timestamp":"2022-08-08T23:11:03.401Z"}
{"level":"info","message":"Downloaded information for collection: Mojang Official Minecraft Jars (593 entries)","timestamp":"2022-08-08T23:11:03.555Z"}
{"level":"info","message":"Downloaded information for collection: Spigot (1 entries)","timestamp":"2022-08-08T23:11:03.863Z"}
{"level":"info","message":"Downloaded information for collection: Mianite (23 entries)","timestamp":"2022-08-08T23:11:03.870Z"}
{"redownload":true,"command":"refresh_profile_list","level":"info","message":"[WEBUI] Received emit command from 192.168.21.106:mc","timestamp":"2022-08-08T23:11:06.441Z"}
{"level":"info","message":"[WEBUI] mc connected from 192.168.21.106","timestamp":"2022-08-08T23:12:16.492Z"}
{"0":"de_DE","1":"en_US","2":"fr_FR","3":"it_IT","4":"ja_JP","5":"no_NB","6":"ru_RU","7":"sv_SE","level":"info","message":"","timestamp":"2022-08-08T23:12:16.496Z"}
{"level":"info","message":"[WEBUI] mc connected from 192.168.21.106","timestamp":"2022-08-08T23:13:25.900Z"}
{"0":"de_DE","1":"en_US","2":"fr_FR","3":"it_IT","4":"ja_JP","5":"no_NB","6":"ru_RU","7":"sv_SE","level":"info","message":"","timestamp":"2022-08-08T23:13:25.903Z"}
{"level":"info","message":"Downloaded information for collection: SpongeVanilla (764 entries)","timestamp":"2022-08-08T23:13:34.843Z"}
{"level":"info","message":"Downloaded information for collection: BungeeCord (10 entries)","timestamp":"2022-08-08T23:13:44.600Z"}
{"level":"info","message":"Downloaded information for collection: BungeeCord (10 entries)","timestamp":"2022-08-08T23:13:44.694Z"}
{"level":"info","message":"Downloaded information for collection: BungeeCord (10 entries)","timestamp":"2022-08-08T23:13:44.806Z"}
{"level":"info","message":"Downloaded information for collection: Cuberite C++ Server (4 entries)","timestamp":"2022-08-08T23:13:44.807Z"}
{"level":"info","message":"Downloaded information for collection: Travertine (5 entries)","timestamp":"2022-08-08T23:13:45.131Z"}
{"level":"info","message":"Downloaded information for collection: Forge Mod (61 entries)","timestamp":"2022-08-08T23:13:49.682Z"}
{"level":"info","message":"Downloaded information for collection: Forge Mod (61 entries)","timestamp":"2022-08-08T23:13:49.682Z"}
{"level":"info","message":"Downloaded information for collection: Imagicalmine (1 entries)","timestamp":"2022-08-08T23:13:49.684Z"}
{"level":"info","message":"Downloaded information for collection: Forge Mod (61 entries)","timestamp":"2022-08-08T23:13:49.684Z"}
{"level":"info","message":"Downloaded information for collection: Feed the Beast Third-Party Server Packs - old (278 entries)","timestamp":"2022-08-08T23:13:49.885Z"}
{"level":"info","message":"Downloaded information for collection: Feed the Beast Server Packs - old (566 entries)","timestamp":"2022-08-08T23:13:49.967Z"}
{"level":"info","message":"Downloaded information for collection: Nukkit (2 entries)","timestamp":"2022-08-08T23:13:49.968Z"}
{"level":"info","message":"Downloaded information for collection: Cuberite C++ Server (4 entries)","timestamp":"2022-08-08T23:13:50.006Z"}
{"level":"info","message":"Downloaded information for collection: Imagicalmine (1 entries)","timestamp":"2022-08-08T23:13:50.006Z"}
{"level":"info","message":"Downloaded information for collection: Cuberite C++ Server (4 entries)","timestamp":"2022-08-08T23:13:50.009Z"}
{"level":"info","message":"Downloaded information for collection: Imagicalmine (1 entries)","timestamp":"2022-08-08T23:13:50.010Z"}
{"level":"info","message":"Downloaded information for collection: Waterfall (9 entries)","timestamp":"2022-08-08T23:13:50.617Z"}`

**Comment by flareofghast** [comment]
This is indicating that the profiles information is downloading. If I’m reading it correctly you refreshed twice and it downloaded the info twice. 

What exactly were you or weren’t you seeing?

**Comment by davidbdyer** [comment]
The profiles take 30-40 minutes to show up and at least 10 minutes to download a single profile. The profile are not always persistent between logins. Even if the profile is downloaded, it doesn't appear in the UI unless the profiles are loaded. I can ssh in and see the profile are in the `var/games/mineos/minecraft/profiles` folder, but they don't show up in the UI, and the Minecraft server setting page doesn't see the jar. 

If it's relevant my server has 16GB of ram, 4 core i5 @ 3.6Ghz. I'm using Portainer to manage Docker.

Also servers wont start and there are no other services running on that port.

`
[01:49:16] [ServerMain/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
--
[01:49:18] [ServerMain/INFO]: Loaded 7 recipes
[01:49:18] [ServerMain/INFO]: Loaded 1179 advancements
[01:49:19] [ServerMain/WARN]: Failed to parse level-type default, defaulting to minecraft:normal
[01:49:19] [Server thread/INFO]: Starting minecraft server version 1.19
[01:49:19] [Server thread/INFO]: Loading properties
[01:49:19] [Server thread/INFO]: Default game type: SURVIVAL
[01:49:19] [Server thread/INFO]: Generating keypair
[01:49:20] [Server thread/INFO]: Starting Minecraft server on ip:25569
[01:49:20] [Server thread/INFO]: Using epoll channel type
[01:49:20] [Server thread/WARN]: **** FAILED TO BIND TO PORT!
[01:49:20] [Server thread/WARN]: The exception was: io.netty.channel.unix.Errors$NativeIoException: bind(..) failed: Cannot assign requested address
[01:49:20] [Server thread/WARN]: Perhaps a server is already running on that port?
[01:49:20] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.IllegalStateException: Failed to initialize server
at net.minecraft.server.MinecraftServer.v(SourceFile:678) ~[server-1.19.jar:?]
at net.minecraft.server.MinecraftServer.a(SourceFile:258) ~[server-1.19.jar:?]
at java.lang.Thread.run(Thread.java:833) [?:?]
[01:49:20] [Server thread/ERROR]: This crash report has been saved to: /var/games/minecraft/servers/test/./crash-reports/crash-2022-08-09_01.49.20-server.txt
[01:49:20] [Server thread/INFO]: Stopping server
[01:49:20] [Server thread/INFO]: Saving worlds
[01:49:20] [Server thread/ERROR]: Exception stopping the server
java.lang.NullPointerException: Cannot invoke "afo.p_()" because "$5" is null
at net.minecraft.server.MinecraftServer.a(SourceFile:532) ~[server-1.19.jar:?]
at net.minecraft.server.MinecraftServer.s(SourceFile:593) ~[server-1.19.jar:?]
at aep.s(SourceFile:547) ~[server-1.19.jar:?]
at net.minecraft.server.MinecraftServer.v(SourceFile:697) ~[server-1.19.jar:?]
at net.minecraft.server.MinecraftServer.a(SourceFile:258) ~[server-1.19.jar:?]
at java.lang.Thread.run(Thread.java:833) [?:?]
`

**Comment by flareofghast** [comment]
The last attempt for loading the profile info literally started downloading at timestamp

2022-08-08T23:13:34.843Z

And finished at 

2022-08-08T23:13:50.617Z

16 seconds later. 

There might be an issue replicating the data to the UI or requiring a page refresh (not reloading the profiles from the top right drop down).
What web browser are you using? 

Regarding starting servers the log does say it can’t bind to port. Perhaps the server.properties is not set correctly, I see the port is 25569 in the logs.  
Is the server IP and port correct in the server.properties?
(can also try 0.0.0.0 to listen on all ips)

**Comment by davidbdyer** [comment]
I just logged on, and thy profiles are still not populated, and it's been 2hrs. [https://davidbdyer.myqnapcloud.com:8443/mineos.png](url)

I'm using Firefox and Safari. Chrome's security won't let me view the page. I have noticed the only time profiles load is when I spam "refresh profile list" in the menu. They are loaded now after spamming the refresh button about 30 mins ago.

You are correct 0.0.0.0 did work. I'll probably change it to an external static IP if I can work out the other bugs.

**Comment by davidbdyer** [comment]
Have you noticed on the profile page there is no way to go back to Vanilla Servers after you select a modded one from the drop down unless you refresh. When I refresh there is nothing listed again even though 6 minute ago the list was populated.

**Comment by davidbdyer** [comment]
Now Mojang is showing up again after I clicked profile refresh.

**Comment by davidbdyer** [comment]
Now Mojang is gone again :(

**Comment by flareofghast** [comment]
If you open developer tools in the browser and then open the profiles or server webpage do you get any errors show up in the console?

**Comment by davidbdyer** [comment]
There are a few warnings. 

`Some cookies are misusing the recommended “SameSite“ attribute 8`

`Empty string passed to getElementById(). 17 [jquery-2.1.4.min.js:2:24216](https://192.168.21.3:8443/admin/assets/jquery/js/jquery-2.1.4.min.js)`
