### ISSUE TITLE
dockerhub needs to be updated

### ISSUE THREAD

**Issue by stuhby** [hexparrot/mineos-node#506]
I am attempting to run dockerhub app (https://hub.docker.com/r/hexparrot/mineos) in unRAID, but the jdk/jre is version 8. Newer minecraft versions require java 17+ I believe.

With java 8, server.properties will not function correctly w/ mc 1.19.2. Updated docker using apt install java 17 and server.properties works properly.

Is this because the dockerhub has not been updated w/ the latest github commits?

**Comment by stuhby** [comment]
upon re-install of container, this issue is gone...

**Comment by akinnee** [comment]
Needs another update. Cert is expired.
