### ISSUE TITLE
Installing error

### ISSUE THREAD

**Issue by MrBretze** [hexparrot/mineos-node#52]
I read your installing tutorial (https://github.com/hexparrot/mineos-node#installation) and i dont fix the error.

http://gyazo.com/31f766352e536212a921f54c35dd7c59
http://gyazo.com/6c6f569ec7e33af001a6680b77118626
http://gyazo.com/ca94f83985367d2c71722cd0a0079d22

**Comment by hexparrot** [comment]
So far the only two times I've seen installation fail is OSX and ArchLinux.  Are you using either of those?

**Comment by MrBretze** [comment]
Yes, ArchLinux (Debian 7)

**Comment by hexparrot** [comment]
I feel like those are two different distributions.  Arch is source-based, so it doesn't have any roots in Debian.  That said, only the `uname` package fails to build, which is this github issue here: https://github.com/davepacheco/node-uname/issues/3

That said, it should still have built all other packages, and the webui can work without that single package, so you should still be able to use it.  If for whatever reason you get an error starting up the webui, you can try opening `package.json`, locating the "uname": "0.0.x" line, remove it entirely, and try again from `npm install --all`

**Comment by MrBretze** [comment]
I made unparallel you had said but he did not pass it (http://gyazo.com/8bf279e2e5c1439bf04c9f43e14bc513)

**Comment by hexparrot** [comment]
That warning is not indicative of a failure.  Have you tried running the web-ui?

**Comment by MrBretze** [comment]
Ok I do not know, I'll test

**Comment by MrBretze** [comment]
Ok it worked
