### ISSUE TITLE
Docker image out of date

### ISSUE THREAD

**Issue by shinji257** [hexparrot/mineos-node#542]
The docker image is currently stuck on commit b6e0d1e and I don't know if we can get a new docker build sent over to the docker hub?

**Comment by brandonmcclure** [comment]
[This PR](https://github.com/hexparrot/mineos-node/pull/508) that I submitted will setup automatic builds for the docker image. I used to keep my [own image](https://hub.docker.com/repository/docker/bmcclure89/mineos/general) updated with security updates at least, but do not anymore. Use that image at your own risk.

This project [targets NodeJS 16 ](https://github.com/hexparrot/mineos-node/blob/f492bb7fcaa84b0fc7c63a2851286c91b39fde50/.github/workflows/node.js.yml#L19) as the latest NodeJS version. This is quite out of date, and there have been several PRs/Issues that have not really gone anywhere for what the refactor of this project would look like. Any updated docker image without addressing this larger refactor would not be the update that we need. I would not recommend using this anymore. 

If you are using docker, I would recommend using a more purpose built image for your servers: https://github.com/itzg/docker-minecraft-server
