### ISSUE TITLE
feedback/progress for downloading server jars

### ISSUE THREAD

**Issue by flareofghast** [hexparrot/mineos-node#55]
It really needs at least a downloading notification that changes to downloaded once done.
Ideally a % progress but whatever is easiest.

**Comment by hexparrot** [comment]
alright, % done now implemented on profiles page, next to the download button.  updates by the second.

https://github.com/hexparrot/mineos-node/pull/58

**Comment by flareofghast** [comment]
did you forget to push a request-progress module?

{"date":"Mon Jun 29 2015 06:49:00 GMT+0800 (AWST)","process":{"pid":1458,"uid":0,"gid":0,"cwd":"/","execPath":"/usr/bin/node","version":"v0.10.36","argv":["/usr/bin/node","/usr/games/minecraft/webui.js","start"],"memoryUsage":{"rss":130940928,"heapTotal":52032256,"heapUsed":24802320}},"os":{"loadavg":[0.18603515625,0.04736328125,0.01611328125],"uptime":30.72550644},"trace":[{"column":15,"file":"module.js","function":"Function.Module._resolveFilename","line":338,"method":"Module._resolveFilename","native":false},{"column":25,"file":"module.js","function":"Function.Module._load","line":280,"method":"Module._load","native":false},{"column":17,"file":"module.js","function":"Module.require","line":364,"method":"require","native":false},{"column":17,"file":"module.js","function":"require","line":380,"method":null,"native":false},{"column":20,"file":"/usr/games/minecraft/server.js","function":"","line":167,"method":null,"native":false},{"column":17,"file":"events.js","function":"Namespace.emit","line":95,"method":"emit","native":false},{"column":10,"file":"/usr/games/minecraft/node_modules/socket.io/lib/namespace.js","function":"Namespace.emit","line":205,"method":"emit","native":false},{"column":14,"file":"/usr/games/minecraft/node_modules/socket.io/lib/namespace.js","function":null,"line":172,"method":null,"native":false},{"column":13,"file":"node.js","function":"process._tickCallback","line":442,"method":"_tickCallback","native":false}],"stack":["Error: Cannot find module 'request-progress'","    at Function.Module._resolveFilename (module.js:338:15)","    at Function.Module._load (module.js:280:25)","    at Module.require (module.js:364:17)","    at require (module.js:380:17)","    at Namespace.<anonymous> (/usr/games/minecraft/server.js:167:20)","    at Namespace.emit (events.js:95:17)","    at Namespace.emit (/usr/games/minecraft/node_modules/socket.io/lib/namespace.js:205:10)","    at /usr/games/minecraft/node_modules/socket.io/lib/namespace.js:172:14","    at process._tickCallback (node.js:442:13)"],"level":"error","message":"uncaughtException: Cannot find module 'request-progress'","timestamp":"2015-06-28T22:49:00.959Z"}
