### ISSUE TITLE
Port editable

### ISSUE THREAD

**Issue by MrBretze** [hexparrot/mineos-node#62]
Add an option to change the port hebui ?

**Comment by hexparrot** [comment]
Is it not already editable from the web-ui via the server.properties pane?

**Comment by hexparrot** [comment]
I intend to do this, but more customization of the web-ui will follow after all the functionality already-coded is known to work properly.  Thanks for all your issue-creating!

**Comment by hexparrot** [comment]
now editable with PR 89: https://github.com/hexparrot/mineos-node/pull/89.

You'll need to pull the latest scripts and put the mineos.conf file in your /etc/ directory.
