### ISSUE TITLE
Crash transferring very large logfile

### ISSUE THREAD

**Issue by MrBretze** [hexparrot/mineos-node#65]
log: https://gist.github.com/MrBretze/8bb4e71fd34ff2c1c29f

**Comment by hexparrot** [comment]
alright, looks like your [Hierrachy2] server.log file is 66mb or so.  It might be the case that the web-ui cannot and will not transmit that large a file.  I'll have to see about capping it to a far lower value.

**Comment by hexparrot** [comment]
Confirmed with a 50mb log file.  I'll probably cap it at like 2mb tops, and figure out how to make that work.

**Comment by hexparrot** [comment]
I've only found a partial solution.  It's not the final one, but it should keep it from crashing.

Right now the cap is at 256kb.  Beyond that, the existing file just gets ignored so it doesn't block the whole webui.  You should be able to see this working with the latest commit: 7a84a820ec316fbc1257555d8171f5387d8fbe79

**Comment by MrBretze** [comment]
Please re-open this because is back ! :/

**Comment by hexparrot** [comment]
I can reopen this, but unless you can provide some information to allow *me* to reproduce this issue, it'll just be open, and not get fixed.

**Comment by MrBretze** [comment]
Spam the console to "/say blbllbl" by new command block in snapshot and active the repeat mode (is just a exemple), And the new design of mineos console is broken your fix :/

**Comment by hexparrot** [comment]
I don't understand what you're describing.
