### ISSUE TITLE
Sheduled task crash

### ISSUE THREAD

**Issue by MrBretze** [hexparrot/mineos-node#66]
log: https://gist.github.com/MrBretze/642f6352be428d8feb7f

**Comment by MrBretze** [comment]
log screen: http://img15.hostingpics.net/pics/545650mineos.png

**Comment by hexparrot** [comment]
Have you updated your scripts?  The error you're showing there with transmitting the server.log shouldn't happen anymore since it's capped.

**Comment by MrBretze** [comment]
I have update mi scripts and mineos always crash

**Comment by hexparrot** [comment]
What commit are you at?  "git show" should tell you the commit active

**Comment by MrBretze** [comment]
@hexparrot http://img11.hostingpics.net/pics/157462mineos2.png

**Comment by MrBretze** [comment]
Ho sorry i am not user the last commit :-1:

**Comment by MrBretze** [comment]
I update the git by git fetch and git git reset --hard origin/master. i use this cron format: 0 0/10 * 1/1 * ? *
to send a command: /say Test i presse the start button.

**Comment by hexparrot** [comment]
try the cronjob without the opening slash, e.g., "say Test i presse the start button."  instead of "/say ..."

Also, before you do any of that, try updating again, as I've made some changes to the cron to make it work better.

**Comment by MrBretze** [comment]
I update the git and remove the /
log: https://gist.github.com/MrBretze/56eb9e6323c0821ba15c

**Comment by MrBretze** [comment]
new, instant crash after the test
log: {"level":"info","message":"[Quake] 86.235.173.170 issued command : \"start\"","timestamp":"2015-07-05T22:56:21.225Z"}
{"level":"info","message":"[Quake] received request \"start\"","timestamp":"2015-07-05T22:56:21.225Z"}
{"date":"Sun Jul 05 2015 23:36:51 GMT+0000 (UTC)","process":{"pid":364,"uid":0,"gid":0,"cwd":"/","execPath":"/usr/bin/nodejs","version":"v0.10.29","argv":["/usr/bin/nodejs","/usr/games/minecraft/webui.js","start"],"memoryUsage":{"rss":264286208,"heapTotal":135907552,"heapUsed":79557896}},"os":{"loadavg":[1.35791015625,0.962890625,0.8916015625],"uptime":2423551.900902186},"trace":[{"column":12,"file":"/usr/games/minecraft/node_modules/cron/lib/cron.js","function":"Object.CronTime._parseField","line":321,"method":"CronTime._parseField","native":false},{"column":9,"file":"/usr/games/minecraft/node_modules/cron/lib/cron.js","function":"Object.CronTime._parse","line":285,"method":"CronTime._parse","native":false},{"column":8,"file":"/usr/games/minecraft/node_modules/cron/lib/cron.js","function":"Object.CronTime","line":19,"method":"CronTime","native":false},{"column":18,"file":"/usr/games/minecraft/node_modules/cron/lib/cron.js","function":"new CronJob","line":363,"method":null,"native":false},{"column":32,"file":"/usr/games/minecraft/server.js","function":null,"line":1123,"method":null,"native":false},{"column":9,"file":"/usr/games/minecraft/mineos.js","function":null,"line":131,"method":null,"native":false},{"column":14,"file":"evalmachine.<anonymous>","function":null,"line":272,"method":null,"native":false},{"column":5,"file":"/usr/lib/nodejs/graceful-fs/graceful-fs.js","function":null,"line":102,"method":null,"native":false},{"column":15,"file":"evalmachine.<anonymous>","function":"Object.oncomplete","line":107,"method":"oncomplete","native":false}],"stack":["Error: Field (?) cannot be parsed","    at Object.CronTime._parseField (/usr/games/minecraft/node_modules/cron/lib/cron.js:321:12)","    at Object.CronTime._parse (/usr/games/minecraft/node_modules/cron/lib/cron.js:285:9)","    at Object.CronTime (/usr/games/minecraft/node_modules/cron/lib/cron.js:19:8)","    at new CronJob (/usr/games/minecraft/node_modules/cron/lib/cron.js:363:18)","    at /usr/games/minecraft/server.js:1123:32","    at /usr/games/minecraft/mineos.js:131:9","    at evalmachine.<anonymous>:272:14","    at /usr/lib/nodejs/graceful-fs/graceful-fs.js:102:5","    at Object.oncomplete (evalmachine.<anonymous>:107:15)"],"level":"error","message":"uncaughtException: Field (?) cannot be parsed","timestamp":"2015-07-05T23:36:51.609Z"}
{"level":"info","message":"[EvoWar] Discovered server","timestamp":"2015-07-05T23:45:25.368Z"}
{"level":"info","message":"[EvoWar] Created tail on logs/latest.log","timestamp":"2015-07-05T23:45:25.369Z"}
{"level":"error","message":"[EvoWar] Create tail on server.log failed","timestamp":"2015-07-05T23:45:25.370Z"}
{"level":"info","message":"[EvoWar] Watching for file generation: server.log","timestamp":"2015-07-05T23:45:25.370Z"}
{"level":"info","message":"[Hierrachy] Discovered server","timestamp":"2015-07-05T23:45:25.424Z"}
{"level":"error","message":"[Hierrachy] Create tail on logs/latest.log failed","timestamp":"2015-07-05T23:45:25.424Z"}
{"level":"info","message":"[Hierrachy] Watching for file generation: logs/latest.log","timestamp":"2015-07-05T23:45:25.424Z"}
{"level":"error","message":"[Hierrachy] Create tail on server.log failed","timestamp":"2015-07-05T23:45:25.425Z"}
{"level":"info","message":"[Hierrachy] Watching for file generation: server.log","timestamp":"2015-07-05T23:45:25.425Z"}
{"level":"info","message":"[EvoWar] Discovered server","timestamp":"2015-07-05T23:46:02.312Z"}
{"level":"info","message":"[EvoWar] Created tail on logs/latest.log","timestamp":"2015-07-05T23:46:02.314Z"}
{"level":"error","message":"[EvoWar] Create tail on server.log failed","timestamp":"2015-07-05T23:46:02.314Z"}
{"level":"info","message":"[EvoWar] Watching for file generation: server.log","timestamp":"2015-07-05T23:46:02.314Z"}
{"level":"info","message":"[Hierrachy] Discovered server","timestamp":"2015-07-05T23:46:02.377Z"}
{"level":"error","message":"[Hierrachy] Create tail on logs/latest.log failed","timestamp":"2015-07-05T23:46:02.378Z"}
{"level":"info","message":"[Hierrachy] Watching for file generation: logs/latest.log","timestamp":"2015-07-05T23:46:02.378Z"}
{"level":"error","message":"[Hierrachy] Create tail on server.log failed","timestamp":"2015-07-05T23:46:02.378Z"}
{"level":"info","message":"[Hierrachy] Watching for file generation: server.log","timestamp":"2015-07-05T23:46:02.378Z"}
{"level":"info","message":"[Hierrachy2] Discovered server","timestamp":"2015-07-05T23:46:02.380Z"}
{"level":"info","message":"[Hierrachy2] Created tail on logs/latest.log","timestamp":"2015-07-05T23:46:02.381Z"}
{"level":"error","message":"[Hierrachy2] Create tail on server.log failed","timestamp":"2015-07-05T23:46:02.381Z"}
{"level":"info","message":"[Hierrachy2] Watching for file generation: server.log","timestamp":"2015-07-05T23:46:02.381Z"}
{"level":"info","message":"[Quake] Discovered server","timestamp":"2015-07-05T23:46:02.383Z"}
{"level":"info","message":"[Quake] Created tail on logs/latest.log","timestamp":"2015-07-05T23:46:02.383Z"}
{"level":"error","message":"[Quake] Create tail on server.log failed","timestamp":"2015-07-05T23:46:02.383Z"}
{"level":"info","message":"[Quake] Watching for file generation: server.log","timestamp":"2015-07-05T23:46:02.384Z"}
{"level":"info","message":"[Recrutements] Discovered server","timestamp":"2015-07-05T23:46:02.386Z"}
{"level":"info","message":"[Recrutements] Created tail on logs/latest.log","timestamp":"2015-07-05T23:46:02.386Z"}
{"level":"error","message":"[Recrutements] Create tail on server.log failed","timestamp":"2015-07-05T23:46:02.386Z"}
{"level":"info","message":"[Recrutements] Watching for file generation: server.log","timestamp":"2015-07-05T23:46:02.386Z"}
{"level":"info","message":"[SteelWar] Discovered server","timestamp":"2015-07-05T23:46:02.389Z"}
{"level":"info","message":"[SteelWar] Created tail on logs/latest.log","timestamp":"2015-07-05T23:46:02.389Z"}
{"level":"error","message":"[SteelWar] Create tail on server.log failed","timestamp":"2015-07-05T23:46:02.389Z"}
{"level":"info","message":"[SteelWar] Watching for file generation: server.log","timestamp":"2015-07-05T23:46:02.389Z"}
{"level":"info","message":"[Witcher] Discovered server","timestamp":"2015-07-05T23:46:02.390Z"}
{"level":"info","message":"[Witcher] Created tail on logs/latest.log","timestamp":"2015-07-05T23:46:02.390Z"}
{"level":"error","message":"[Witcher] Create tail on server.log failed","timestamp":"2015-07-05T23:46:02.391Z"}
{"level":"info","message":"[Witcher] Watching for file generation: server.log","timestamp":"2015-07-05T23:46:02.391Z"}

**Comment by MrBretze** [comment]
npm install warn: http://img11.hostingpics.net/pics/775713Mineos3.png  (I do not know if we need to create a new issue for her)

**Comment by hexparrot** [comment]
npm warn is ignorable--absolutely nothing to worry about that at all.

What are the values you're filling in for the time, e.g., (* * * * * *).  Based on the error, it seems you're not providing the 6 values it expects (first is seconds).  I'll adjust so the webui displays this expectation.

**Comment by MrBretze** [comment]
Its always crash
cron.config:
[01df95d8b3263babc1ac6ad6b1774b366445b844]
command=stuff
source=0 0/10 * 1/1 * ? *
msg=say Test
enabled=true

mineos log: 
https://gist.github.com/MrBretze/f0a5cf08e46ec5b46193

**Comment by MrBretze** [comment]
I created a very small script to eter to demarer of mineos has the latest verison (cd /usr/games/minecraft && git fetch && git reset --hard origin/master && npm install --all && nodejs service.js start)

**Comment by MrBretze** [comment]
and i use the to creatre mi cron expressions http://www.cronmaker.com/

**Comment by hexparrot** [comment]
What is the '?' in your cron expression?

**Comment by MrBretze** [comment]
I dont xD

**Comment by MrBretze** [comment]
I do not search more than his on cron expressions

**Comment by hexparrot** [comment]
The cronmaker you're using doesn't apply here.  It's for some format called "quartz" cron scheduling, which I'm not familiar with and differs from standard cron format.

**Comment by MrBretze** [comment]
this format is good ?

# Minute   Hour   Day of Month       Month          Day of Week
# (0-59)  (0-23)     (1-31)    (1-12 or Jan-Dec)  (0-6 or Sun-Sat)                
    0        2          12             *                *

**Comment by hexparrot** [comment]
The format is outlined in the link I just provided.  Cronjobs should be 6 time values.  It may be the case that 5 works--I don't know, it could be robust like that, but it'd be preferable to follow the format shown by the module creator.

**Comment by MrBretze** [comment]
i not view you link xD

**Comment by hexparrot** [comment]
This issue appears to just be from the wrong cron format.  If you come up with a crash using the prescribed format, feel free to open this back up.

**Comment by MrBretze** [comment]
Task not sheduled: http://puu.sh/iTjjq/55532e84d8.jpg
Log: https://gist.github.com/MrBretze/3e82b41444f4d6fbecfb

**Comment by MrBretze** [comment]
My scheduled task works with a "say Test"
