### ISSUE TITLE
Server profile not detected after download

### ISSUE THREAD

**Issue by flareofghast** [hexparrot/mineos-node#70]
Just built up a new server on Ubuntu 14.04.2 and downloaded 1.8.7, created a new server which worked fine and was detected but now it's not picking up the profile.
Restart Mineos service worked.

**Comment by flareofghast** [comment]
Also, no pop ups regarding changing options or accepting eula - that supposed to be the norm now?

**Comment by hexparrot** [comment]
It definitely shouldn't be the norm--any time the 'eula.txt' is detected, it should be able to identify it and bring up a popup.  Of course, if the eula exists already (and is false) when the web-ui / user logs on, it won't just pop up unsolicited, it should only come up after hitting 'start' and it makes its attempt.

That said, under the 'stop' dropdown is an 'accept eula' option.  I haven't been able to reproduce the issue you're describing and my main installation is Ubuntu 140.04.2.  I'll look further into it, but if you can provide any additional steps to how to get that to happen--I never need to restart the mineos service at any point; it works upon first install.

**Comment by flareofghast** [comment]
The EULA issue I mentioned here was that it popped up, but no notification of EULA accepted or any pop up notification about changing profile or XMS or XMX values. 

I thought that maybe the first profile not appearing as selectable in the server drop down may be similar issue as the first server not appearing on the front page?

**Comment by hexparrot** [comment]
My mistake--I should've read it more closely!  Yes, it is the norm now that *successful* operations will no longer show a popup, as it is usually not very useful.

Taking after highly responsive sites like gmail, (unless there's an option to undo it), you can just assume the action succeeded and no need to be reaffirmed.

Changing a `gamemode=0` to `gamemode=1` is not really the kind of change that should also say "modify_sc succeeded!" --- as if the user could do anything with that knowledge.  But if it fails, for whatever reason, indeed they should be notified.

Accepting the eula, on the other hand, I'm not sure *ever* had a notification.  This is something I'd like to implement, but just have not yet; it's right now a technical issue.

**Comment by flareofghast** [comment]
maybe it didn't. I thought I had remembered it but it's possible I didn't.

**Comment by hexparrot** [comment]
#75 hopefully fixes this issue by colorizing and making the eula button more responsive to the current file state.  Can you verify?
