### ISSUE TITLE
Server.log doesn't populate

### ISSUE THREAD

**Issue by flareofghast** [hexparrot/mineos-node#73]
My server.log has never worked. Is it supposed to, or is it as yet unimplemented?

**Comment by hexparrot** [comment]
With the exception of a few commits, the server.log should be working for quite some time now. What commit are you on?

**Comment by flareofghast** [comment]
commit c89c0fe3fefb7a5203604213a641202ccc30f47e

**Comment by hexparrot** [comment]
I can't seem to find a way to make it *not* work; server.log has always auto-updated in the webui for me. What does your mineos.log look like?

**Comment by flareofghast** [comment]
{"level":"info","message":"[WEBUI] peter connected from 192.168.1.176","timestamp":"2015-07-09T04:13:16.159Z"}
{"level":"info","message":"[WEBUI] Downloading official profiles.","timestamp":"2015-07-09T04:13:16.161Z"}
{"profile":{"id":"1.8.7","time":"2015-06-05T10:10:44+00:00","releaseTime":"2015-06-05T10:10:44+00:00","type":"release","group":"mojang","downloaded":false,"webui_desc":"Official Mojang Jar","weight":0,"$$hashKey":"object:125"},"command":"mojang_download","level":"info","message":"[WEBUI] Received emit command from 192.168.1.176:peter","timestamp":"2015-07-09T04:13:28.762Z"}
{"command":"create","server_name":"lavalava","properties":{"level-name":"lavalava","level-seed":"23rln23grrjqevEQV33RG$54","difficulty":"2","gamemode":"0","generate-structures":true},"level":"info","message":"[WEBUI] Received emit command from 192.168.1.176:peter","timestamp":"2015-07-09T04:14:12.124Z"}
{"level":"info","message":"[lavalava] Server created in filesystem.","timestamp":"2015-07-09T04:14:12.180Z"}
{"level":"info","message":"[lavalava] Discovered server","timestamp":"2015-07-09T04:14:12.552Z"}
{"level":"error","message":"[lavalava] Create tail on logs/latest.log failed","timestamp":"2015-07-09T04:14:12.554Z"}
{"level":"info","message":"[lavalava] Watching for file generation: logs/latest.log","timestamp":"2015-07-09T04:14:12.554Z"}
{"level":"error","message":"[lavalava] Create tail on server.log failed","timestamp":"2015-07-09T04:14:12.554Z"}
{"level":"info","message":"[lavalava] Watching for file generation: server.log","timestamp":"2015-07-09T04:14:12.554Z"}
{"level":"info","message":"[lavalava] peter (192.168.1.176) joined server namespace","timestamp":"2015-07-09T04:14:12.606Z"}
{"level":"info","message":"[lavalava] 192.168.1.176 issued command : \"modify_sc\"","timestamp":"2015-07-09T04:14:16.850Z"}
{"level":"info","message":"[lavalava] received request \"modify_sc\"","timestamp":"2015-07-09T04:14:16.852Z"}
{"level":"info","message":"[lavalava] 192.168.1.176 issued command : \"modify_sc\"","timestamp":"2015-07-09T04:14:27.683Z"}
{"level":"info","message":"[lavalava] received request \"modify_sc\"","timestamp":"2015-07-09T04:14:27.683Z"}
{"level":"info","message":"[lavalava] 192.168.1.176 issued command : \"modify_sc\"","timestamp":"2015-07-09T04:14:31.156Z"}
{"level":"info","message":"[lavalava] received request \"modify_sc\"","timestamp":"2015-07-09T04:14:31.156Z"}
{"level":"info","message":"[lavalava] 192.168.1.176 issued command : \"modify_sc\"","timestamp":"2015-07-09T04:14:34.676Z"}
{"level":"info","message":"[lavalava] received request \"modify_sc\"","timestamp":"2015-07-09T04:14:34.676Z"}
{"level":"info","message":"[lavalava] 192.168.1.176 issued command : \"modify_sc\"","timestamp":"2015-07-09T04:14:42.192Z"}
{"level":"info","message":"[lavalava] received request \"modify_sc\"","timestamp":"2015-07-09T04:14:42.192Z"}
{"level":"info","message":"[lavalava] 192.168.1.176 issued command : \"modify_sc\"","timestamp":"2015-07-09T04:14:45.926Z"}
{"level":"info","message":"[lavalava] received request \"modify_sc\"","timestamp":"2015-07-09T04:14:45.927Z"}
{"level":"info","message":"[lavalava] Discovered server","timestamp":"2015-07-09T04:17:44.305Z"}
{"level":"error","message":"[lavalava] Create tail on logs/latest.log failed","timestamp":"2015-07-09T04:17:44.307Z"}
{"level":"info","message":"[lavalava] Watching for file generation: logs/latest.log","timestamp":"2015-07-09T04:17:44.307Z"}
{"level":"error","message":"[lavalava] Create tail on server.log failed","timestamp":"2015-07-09T04:17:44.308Z"}
{"level":"info","message":"[lavalava] Watching for file generation: server.log","timestamp":"2015-07-09T04:17:44.308Z"}
{"level":"info","message":"[WEBUI] peter connected from 192.168.1.176","timestamp":"2015-07-09T04:17:54.661Z"}
{"level":"info","message":"[WEBUI] Downloading official profiles.","timestamp":"2015-07-09T04:17:54.662Z"}
{"level":"info","message":"[lavalava] peter (192.168.1.176) joined server namespace","timestamp":"2015-07-09T04:17:55.026Z"}
{"level":"info","message":"[lavalava] 192.168.1.176 issued command : \"modify_sc\"","timestamp":"2015-07-09T04:18:00.662Z"}
{"level":"info","message":"[lavalava] received request \"modify_sc\"","timestamp":"2015-07-09T04:18:00.663Z"}
{"level":"info","message":"[lavalava] 192.168.1.176 issued command : \"modify_sc\"","timestamp":"2015-07-09T04:18:20.409Z"}
{"level":"info","message":"[lavalava] received request \"modify_sc\"","timestamp":"2015-07-09T04:18:20.409Z"}
{"level":"info","message":"[lavalava] 192.168.1.176 issued command : \"modify_sc\"","timestamp":"2015-07-09T04:18:30.645Z"}
{"level":"info","message":"[lavalava] received request \"modify_sc\"","timestamp":"2015-07-09T04:18:30.645Z"}
{"level":"info","message":"[lavalava] 192.168.1.176 issued command : \"start\"","timestamp":"2015-07-09T04:18:32.384Z"}
{"level":"info","message":"[lavalava] received request \"start\"","timestamp":"2015-07-09T04:18:32.385Z"}
{"level":"info","message":"[lavalava] latest.log created! Watchfile logs/latest.log closed","timestamp":"2015-07-09T04:18:34.789Z"}
{"level":"info","message":"[lavalava] Created tail on logs/latest.log","timestamp":"2015-07-09T04:18:34.789Z"}
{"level":"info","message":"[lavalava] eula.txt detected: NOT YET ACCEPTED (eula=false)","timestamp":"2015-07-09T04:18:37.942Z"}
{"level":"info","message":"[lavalava] 192.168.1.176 issued command : \"accept_eula\"","timestamp":"2015-07-09T04:18:41.254Z"}
{"level":"info","message":"[lavalava] received request \"accept_eula\"","timestamp":"2015-07-09T04:18:41.254Z"}
{"level":"info","message":"[lavalava] eula.txt detected: ACCEPTED (eula=true)","timestamp":"2015-07-09T04:18:41.505Z"}
{"level":"info","message":"[lavalava] 192.168.1.176 issued command : \"start\"","timestamp":"2015-07-09T04:19:28.540Z"}
{"level":"info","message":"[lavalava] received request \"start\"","timestamp":"2015-07-09T04:19:28.541Z"}
{"level":"info","message":"[lavalava] 192.168.1.176 issued command : \"stuff\"","timestamp":"2015-07-09T04:20:47.777Z"}
{"level":"info","message":"[lavalava] received request \"stuff\"","timestamp":"2015-07-09T04:20:47.796Z"}
{"level":"info","message":"[lavalava] Discovered server","timestamp":"2015-07-09T14:42:27.432Z"}
{"level":"info","message":"[lavalava] Created tail on logs/latest.log","timestamp":"2015-07-09T14:42:27.456Z"}
{"level":"error","message":"[lavalava] Create tail on server.log failed","timestamp":"2015-07-09T14:42:27.456Z"}
{"level":"info","message":"[lavalava] Watching for file generation: server.log","timestamp":"2015-07-09T14:42:27.456Z"}
{"level":"info","message":"[lavalava] eula.txt detected: ACCEPTED (eula=true)","timestamp":"2015-07-09T14:42:27.923Z"}
{"level":"info","message":"[WEBUI] peter connected from 192.168.1.139","timestamp":"2015-07-09T22:26:18.019Z"}
{"level":"info","message":"[WEBUI] Downloading official profiles.","timestamp":"2015-07-09T22:26:18.020Z"}
{"level":"info","message":"[lavalava] peter (192.168.1.139) joined server namespace","timestamp":"2015-07-09T22:26:18.428Z"}
{"level":"info","message":"[lavalava] transmittting existing file contents: logs/latest.log (9517 bytes)","timestamp":"2015-07-09T22:26:18.860Z"}
{"level":"info","message":"[WEBUI] peter connected from 192.168.1.139","timestamp":"2015-07-09T22:26:52.785Z"}
{"level":"info","message":"[WEBUI] peter connected from 192.168.1.176","timestamp":"2015-07-09T22:30:38.443Z"}
{"level":"info","message":"[lavalava] peter (192.168.1.176) joined server namespace","timestamp":"2015-07-09T22:30:42.441Z"}
{"level":"info","message":"[lavalava] transmittting existing file contents: logs/latest.log (9517 bytes)","timestamp":"2015-07-09T22:30:42.488Z"}
{"level":"info","message":"[lavalava] 192.168.1.176 issued command : \"start\"","timestamp":"2015-07-09T22:31:06.818Z"}
{"level":"info","message":"[lavalava] received request \"start\"","timestamp":"2015-07-09T22:31:06.858Z"}
{"level":"info","message":"[lavalava] 192.168.1.176 issued command : \"stop\"","timestamp":"2015-07-09T22:31:18.570Z"}
{"level":"info","message":"[lavalava] received request \"stop\"","timestamp":"2015-07-09T22:31:18.629Z"}
{"level":"info","message":"[lavalava] Discovered server","timestamp":"2015-07-09T22:32:28.736Z"}
{"level":"info","message":"[lavalava] Created tail on logs/latest.log","timestamp":"2015-07-09T22:32:28.749Z"}
{"level":"error","message":"[lavalava] Create tail on server.log failed","timestamp":"2015-07-09T22:32:28.750Z"}
{"level":"info","message":"[lavalava] Watching for file generation: server.log","timestamp":"2015-07-09T22:32:28.750Z"}
{"level":"info","message":"[lavalava] eula.txt detected: ACCEPTED (eula=true)","timestamp":"2015-07-09T22:32:29.217Z"}
{"level":"info","message":"[WEBUI] peter connected from 192.168.1.176","timestamp":"2015-07-09T22:32:38.779Z"}
{"level":"info","message":"[WEBUI] Downloading official profiles.","timestamp":"2015-07-09T22:32:39.050Z"}
{"date":"Fri Jul 10 2015 08:02:39 GMT+0930 (ACST)","process":{"pid":1862,"uid":0,"gid":0,"cwd":"/","execPath":"/usr/bin/nodejs","version":"v0.10.25","argv":["/usr/bin/nodejs","/usr/games/minecraft/webui.js","start"],"memoryUsage":{"rss":81276928,"heapTotal":56147968,"heapUsed":35188096}},"os":{"loadavg":[0.150390625,0.09814453125,0.07177734375],"uptime":28222.122301954},"trace":[{"column":9,"file":"/usr/games/minecraft/server.js","function":"check_profiles","line":1042,"method":null,"native":false},{"column":7,"file":"/usr/games/minecraft/server.js","function":"self.send_profile_list","line":146,"method":"send_profile_list","native":false},{"column":10,"file":"/usr/games/minecraft/server.js","function":"","line":266,"method":null,"native":false},{"column":17,"file":"events.js","function":"Namespace.EventEmitter.emit","line":95,"method":"EventEmitter.emit","native":false},{"column":10,"file":"/usr/games/minecraft/node_modules/socket.io/lib/namespace.js","function":"Namespace.emit","line":205,"method":"emit","native":false},{"column":14,"file":"/usr/games/minecraft/node_modules/socket.io/lib/namespace.js","function":null,"line":172,"method":null,"native":false},{"column":13,"file":"node.js","function":"process._tickCallback","line":415,"method":"_tickCallback","native":false}],"stack":["TypeError: Object #<Object> has no method 'forEachOfLimit'","    at check_profiles (/usr/games/minecraft/server.js:1042:9)","    at self.send_profile_list (/usr/games/minecraft/server.js:146:7)","    at Namespace.<anonymous> (/usr/games/minecraft/server.js:266:10)","    at Namespace.EventEmitter.emit (events.js:95:17)","    at Namespace.emit (/usr/games/minecraft/node_modules/socket.io/lib/namespace.js:205:10)","    at /usr/games/minecraft/node_modules/socket.io/lib/namespace.js:172:14","    at process._tickCallback (node.js:415:13)"],"level":"error","message":"uncaughtException: Object #<Object> has no method 'forEachOfLimit'","timestamp":"2015-07-09T22:32:39.052Z"}
{"level":"info","message":"[lavalava] peter (192.168.1.176) joined server namespace","timestamp":"2015-07-09T22:32:39.158Z"}
{"level":"info","message":"[lavalava] transmittting existing file contents: logs/latest.log (1607 bytes)","timestamp":"2015-07-09T22:32:39.273Z"}
{"level":"info","message":"[lavalava] Discovered server","timestamp":"2015-07-09T22:32:42.860Z"}
{"level":"info","message":"[lavalava] Created tail on logs/latest.log","timestamp":"2015-07-09T22:32:42.862Z"}
{"level":"error","message":"[lavalava] Create tail on server.log failed","timestamp":"2015-07-09T22:32:42.862Z"}
{"level":"info","message":"[lavalava] Watching for file generation: server.log","timestamp":"2015-07-09T22:32:42.862Z"}
{"level":"info","message":"[lavalava] eula.txt detected: ACCEPTED (eula=true)","timestamp":"2015-07-09T22:32:43.326Z"}
{"level":"info","message":"[lavalava] Discovered server","timestamp":"2015-07-09T22:35:05.361Z"}
{"level":"info","message":"[lavalava] Created tail on logs/latest.log","timestamp":"2015-07-09T22:35:05.375Z"}
{"level":"error","message":"[lavalava] Create tail on server.log failed","timestamp":"2015-07-09T22:35:05.375Z"}
{"level":"info","message":"[lavalava] Watching for file generation: server.log","timestamp":"2015-07-09T22:35:05.375Z"}
{"level":"info","message":"[lavalava] eula.txt detected: ACCEPTED (eula=true)","timestamp":"2015-07-09T22:35:05.842Z"}
{"level":"info","message":"[WEBUI] peter connected from 192.168.1.176","timestamp":"2015-07-09T22:36:48.372Z"}
{"level":"info","message":"[WEBUI] Downloading official profiles.","timestamp":"2015-07-09T22:36:48.718Z"}
{"date":"Fri Jul 10 2015 08:06:48 GMT+0930 (ACST)","process":{"pid":1032,"uid":0,"gid":0,"cwd":"/","execPath":"/usr/bin/nodejs","version":"v0.10.25","argv":["/usr/bin/nodejs","/usr/games/minecraft/webui.js","start"],"memoryUsage":{"rss":74506240,"heapTotal":55116032,"heapUsed":30104968}},"os":{"loadavg":[0.01416015625,0.0146484375,0.00537109375],"uptime":113.201967931},"trace":[{"column":9,"file":"/usr/games/minecraft/server.js","function":"check_profiles","line":1042,"method":null,"native":false},{"column":7,"file":"/usr/games/minecraft/server.js","function":"self.send_profile_list","line":146,"method":"send_profile_list","native":false},{"column":10,"file":"/usr/games/minecraft/server.js","function":"","line":266,"method":null,"native":false},{"column":17,"file":"events.js","function":"Namespace.EventEmitter.emit","line":95,"method":"EventEmitter.emit","native":false},{"column":10,"file":"/usr/games/minecraft/node_modules/socket.io/lib/namespace.js","function":"Namespace.emit","line":205,"method":"emit","native":false},{"column":14,"file":"/usr/games/minecraft/node_modules/socket.io/lib/namespace.js","function":null,"line":172,"method":null,"native":false},{"column":13,"file":"node.js","function":"process._tickCallback","line":415,"method":"_tickCallback","native":false}],"stack":["TypeError: Object #<Object> has no method 'forEachOfLimit'","    at check_profiles (/usr/games/minecraft/server.js:1042:9)","    at self.send_profile_list (/usr/games/minecraft/server.js:146:7)","    at Namespace.<anonymous> (/usr/games/minecraft/server.js:266:10)","    at Namespace.EventEmitter.emit (events.js:95:17)","    at Namespace.emit (/usr/games/minecraft/node_modules/socket.io/lib/namespace.js:205:10)","    at /usr/games/minecraft/node_modules/socket.io/lib/namespace.js:172:14","    at process._tickCallback (node.js:415:13)"],"level":"error","message":"uncaughtException: Object #<Object> has no method 'forEachOfLimit'","timestamp":"2015-07-09T22:36:48.721Z"}
{"level":"info","message":"[lavalava] peter (192.168.1.176) joined server namespace","timestamp":"2015-07-09T22:36:48.773Z"}
{"level":"info","message":"[lavalava] transmittting existing file contents: logs/latest.log (1607 bytes)","timestamp":"2015-07-09T22:36:48.930Z"}
{"level":"info","message":"[lavalava] Discovered server","timestamp":"2015-07-09T22:36:52.529Z"}
{"level":"info","message":"[lavalava] Created tail on logs/latest.log","timestamp":"2015-07-09T22:36:52.531Z"}
{"level":"error","message":"[lavalava] Create tail on server.log failed","timestamp":"2015-07-09T22:36:52.532Z"}
{"level":"info","message":"[lavalava] Watching for file generation: server.log","timestamp":"2015-07-09T22:36:52.532Z"}
{"level":"info","message":"[lavalava] eula.txt detected: ACCEPTED (eula=true)","timestamp":"2015-07-09T22:36:52.990Z"}
{"level":"info","message":"[WEBUI] peter connected from 192.168.1.176","timestamp":"2015-07-09T22:39:07.275Z"}
{"level":"info","message":"[WEBUI] Downloading official profiles.","timestamp":"2015-07-09T22:39:07.364Z"}
{"date":"Fri Jul 10 2015 08:09:07 GMT+0930 (ACST)","process":{"pid":1057,"uid":0,"gid":0,"cwd":"/","execPath":"/usr/bin/nodejs","version":"v0.10.25","argv":["/usr/bin/nodejs","/usr/games/minecraft/webui.js","start"],"memoryUsage":{"rss":148488192,"heapTotal":56147968,"heapUsed":33104384}},"os":{"loadavg":[0.064453125,0.02978515625,0.0107421875],"uptime":251.847617708},"trace":[{"column":9,"file":"/usr/games/minecraft/server.js","function":"check_profiles","line":1042,"method":null,"native":false},{"column":7,"file":"/usr/games/minecraft/server.js","function":"self.send_profile_list","line":146,"method":"send_profile_list","native":false},{"column":10,"file":"/usr/games/minecraft/server.js","function":"","line":266,"method":null,"native":false},{"column":17,"file":"events.js","function":"Namespace.EventEmitter.emit","line":95,"method":"EventEmitter.emit","native":false},{"column":10,"file":"/usr/games/minecraft/node_modules/socket.io/lib/namespace.js","function":"Namespace.emit","line":205,"method":"emit","native":false},{"column":14,"file":"/usr/games/minecraft/node_modules/socket.io/lib/namespace.js","function":null,"line":172,"method":null,"native":false},{"column":13,"file":"node.js","function":"process._tickCallback","line":415,"method":"_tickCallback","native":false}],"stack":["TypeError: Object #<Object> has no method 'forEachOfLimit'","    at check_profiles (/usr/games/minecraft/server.js:1042:9)","    at self.send_profile_list (/usr/games/minecraft/server.js:146:7)","    at Namespace.<anonymous> (/usr/games/minecraft/server.js:266:10)","    at Namespace.EventEmitter.emit (events.js:95:17)","    at Namespace.emit (/usr/games/minecraft/node_modules/socket.io/lib/namespace.js:205:10)","    at /usr/games/minecraft/node_modules/socket.io/lib/namespace.js:172:14","    at process._tickCallback (node.js:415:13)"],"level":"error","message":"uncaughtException: Object #<Object> has no method 'forEachOfLimit'","timestamp":"2015-07-09T22:39:07.367Z"}
{"level":"info","message":"[lavalava] peter (192.168.1.176) joined server namespace","timestamp":"2015-07-09T22:39:07.834Z"}
{"level":"info","message":"[lavalava] transmittting existing file contents: logs/latest.log (1607 bytes)","timestamp":"2015-07-09T22:39:07.899Z"}
{"level":"info","message":"[lavalava] Discovered server","timestamp":"2015-07-09T22:39:11.186Z"}
{"level":"info","message":"[lavalava] Created tail on logs/latest.log","timestamp":"2015-07-09T22:39:11.188Z"}
{"level":"error","message":"[lavalava] Create tail on server.log failed","timestamp":"2015-07-09T22:39:11.188Z"}
{"level":"info","message":"[lavalava] Watching for file generation: server.log","timestamp":"2015-07-09T22:39:11.188Z"}
{"level":"info","message":"[lavalava] eula.txt detected: ACCEPTED (eula=true)","timestamp":"2015-07-09T22:39:11.648Z"}
{"level":"info","message":"[lavalava] Discovered server","timestamp":"2015-07-09T22:39:48.690Z"}
{"level":"info","message":"[lavalava] Created tail on logs/latest.log","timestamp":"2015-07-09T22:39:48.692Z"}
{"level":"error","message":"[lavalava] Create tail on server.log failed","timestamp":"2015-07-09T22:39:48.693Z"}
{"level":"info","message":"[lavalava] Watching for file generation: server.log","timestamp":"2015-07-09T22:39:48.693Z"}
{"level":"info","message":"[lavalava] eula.txt detected: ACCEPTED (eula=true)","timestamp":"2015-07-09T22:39:49.151Z"}
{"level":"info","message":"[WEBUI] peter connected from 192.168.1.176","timestamp":"2015-07-09T22:39:57.910Z"}
{"level":"info","message":"[WEBUI] Downloading official profiles.","timestamp":"2015-07-09T22:39:57.999Z"}
{"level":"info","message":"[lavalava] peter (192.168.1.176) joined server namespace","timestamp":"2015-07-09T22:39:58.419Z"}
{"level":"info","message":"[lavalava] transmittting existing file contents: logs/latest.log (1607 bytes)","timestamp":"2015-07-09T22:39:58.500Z"}
{"level":"info","message":"[lavalava] 192.168.1.176 issued command : \"start\"","timestamp":"2015-07-09T22:40:21.695Z"}
{"level":"info","message":"[lavalava] received request \"start\"","timestamp":"2015-07-09T22:40:21.723Z"}
{"level":"info","message":"[lavalava] 192.168.1.176 issued command : \"modify_sc\"","timestamp":"2015-07-09T22:44:09.029Z"}
{"level":"info","message":"[lavalava] received request \"modify_sc\"","timestamp":"2015-07-09T22:44:09.089Z"}
{"level":"info","message":"[lavalava] 192.168.1.176 issued command : \"modify_sc\"","timestamp":"2015-07-09T22:44:15.558Z"}
{"level":"info","message":"[lavalava] received request \"modify_sc\"","timestamp":"2015-07-09T22:44:15.558Z"}
{"level":"info","message":"[lavalava] Discovered server","timestamp":"2015-07-10T04:34:49.178Z"}
{"level":"info","message":"[lavalava] Created tail on logs/latest.log","timestamp":"2015-07-10T04:34:49.188Z"}
{"level":"error","message":"[lavalava] Create tail on server.log failed","timestamp":"2015-07-10T04:34:49.188Z"}
{"level":"info","message":"[lavalava] Watching for file generation: server.log","timestamp":"2015-07-10T04:34:49.188Z"}
{"level":"info","message":"[lavalava] eula.txt detected: ACCEPTED (eula=true)","timestamp":"2015-07-10T04:34:49.655Z"}
{"level":"info","message":"[WEBUI] peter connected from 192.168.1.176","timestamp":"2015-07-10T04:29:26.619Z"}
{"level":"info","message":"[WEBUI] Downloading official profiles.","timestamp":"2015-07-10T04:29:26.966Z"}
{"level":"info","message":"[lavalava] peter (192.168.1.176) joined server namespace","timestamp":"2015-07-10T04:29:27.144Z"}
{"level":"info","message":"[lavalava] transmittting existing file contents: logs/latest.log (11681 bytes)","timestamp":"2015-07-10T04:29:27.304Z"}
{"level":"info","message":"[lavalava] Discovered server","timestamp":"2015-07-10T04:36:10.084Z"}
{"level":"info","message":"[lavalava] Created tail on logs/latest.log","timestamp":"2015-07-10T04:36:10.086Z"}
{"level":"error","message":"[lavalava] Create tail on server.log failed","timestamp":"2015-07-10T04:36:10.087Z"}
{"level":"info","message":"[lavalava] Watching for file generation: server.log","timestamp":"2015-07-10T04:36:10.087Z"}
{"level":"info","message":"[lavalava] eula.txt detected: ACCEPTED (eula=true)","timestamp":"2015-07-10T04:36:10.546Z"}
{"level":"info","message":"[WEBUI] peter connected from 192.168.1.176","timestamp":"2015-07-10T04:36:21.146Z"}
{"level":"info","message":"[WEBUI] Downloading official profiles.","timestamp":"2015-07-10T04:36:21.237Z"}
{"level":"info","message":"[lavalava] peter (192.168.1.176) joined server namespace","timestamp":"2015-07-10T04:36:21.668Z"}
{"level":"info","message":"[lavalava] transmittting existing file contents: logs/latest.log (11681 bytes)","timestamp":"2015-07-10T04:36:21.759Z"}
{"level":"info","message":"[lavalava] 192.168.1.176 issued command : \"start\"","timestamp":"2015-07-10T04:36:27.630Z"}
{"level":"info","message":"[lavalava] received request \"start\"","timestamp":"2015-07-10T04:36:27.667Z"}
{"level":"info","message":"[WEBUI] peter connected from 118.211.27.66","timestamp":"2015-07-12T07:14:45.536Z"}
{"level":"info","message":"[lavalava] peter (118.211.27.66) joined server namespace","timestamp":"2015-07-12T07:15:07.385Z"}
{"level":"info","message":"[lavalava] transmittting existing file contents: logs/latest.log (7816 bytes)","timestamp":"2015-07-12T07:15:07.688Z"}
{"profile":{"id":"1.7.10","time":"2014-05-14T19:29:23+02:00","releaseTime":"2014-05-14T19:29:23+02:00","type":"release","group":"mojang","downloaded":false,"webui_desc":"Official Mojang Jar","weight":0,"$$hashKey":"object:158"},"command":"download","level":"info","message":"[WEBUI] Received emit command from 118.211.27.66:peter","timestamp":"2015-07-12T07:15:13.969Z"}
{"level":"info","message":"[WEBUI] Downloading official profiles.","timestamp":"2015-07-12T07:15:23.888Z"}
{"command":"create","server_name":"modded","properties":{"server-port":"25566","level-name":"projectRed","level-seed":";bk3jk3@#RGJKH@#RGklhqwdf","difficulty":"2","gamemode":"1","generate-structures":true},"level":"info","message":"[WEBUI] Received emit command from 118.211.27.66:peter","timestamp":"2015-07-12T07:16:19.878Z"}
{"level":"info","message":"[modded] Server created in filesystem.","timestamp":"2015-07-12T07:16:19.895Z"}
{"level":"info","message":"[modded] Discovered server","timestamp":"2015-07-12T07:16:20.291Z"}
{"level":"error","message":"[modded] Create tail on logs/latest.log failed","timestamp":"2015-07-12T07:16:20.292Z"}
{"level":"info","message":"[modded] Watching for file generation: logs/latest.log","timestamp":"2015-07-12T07:16:20.292Z"}
{"level":"error","message":"[modded] Create tail on server.log failed","timestamp":"2015-07-12T07:16:20.292Z"}
{"level":"info","message":"[modded] Watching for file generation: server.log","timestamp":"2015-07-12T07:16:20.293Z"}
{"level":"info","message":"[modded] peter (118.211.27.66) joined server namespace","timestamp":"2015-07-12T07:16:20.326Z"}
{"level":"info","message":"[modded] 118.211.27.66 issued command : \"modify_sc\"","timestamp":"2015-07-12T07:16:20.432Z"}
{"level":"info","message":"[modded] received request \"modify_sc\"","timestamp":"2015-07-12T07:16:20.434Z"}
{"level":"info","message":"[modded] 118.211.27.66 issued command : \"modify_sc\"","timestamp":"2015-07-12T07:16:30.990Z"}
{"level":"info","message":"[modded] received request \"modify_sc\"","timestamp":"2015-07-12T07:16:30.990Z"}
{"level":"info","message":"[modded] 118.211.27.66 issued command : \"copy_profile\"","timestamp":"2015-07-12T07:16:36.152Z"}
{"level":"info","message":"[modded] received request \"copy_profile\"","timestamp":"2015-07-12T07:16:36.152Z"}
{"level":"info","message":"[modded] 118.211.27.66 issued command : \"modify_sc\"","timestamp":"2015-07-12T07:16:40.715Z"}
{"level":"info","message":"[modded] received request \"modify_sc\"","timestamp":"2015-07-12T07:16:40.715Z"}
{"level":"info","message":"[modded] 118.211.27.66 issued command : \"modify_sc\"","timestamp":"2015-07-12T07:16:45.628Z"}
{"level":"info","message":"[modded] received request \"modify_sc\"","timestamp":"2015-07-12T07:16:45.628Z"}
{"level":"info","message":"[modded] 118.211.27.66 issued command : \"modify_sc\"","timestamp":"2015-07-12T07:16:48.961Z"}
{"level":"info","message":"[modded] received request \"modify_sc\"","timestamp":"2015-07-12T07:16:48.961Z"}
{"level":"info","message":"[WEBUI] peter connected from 118.211.27.66","timestamp":"2015-07-12T07:58:04.525Z"}
{"level":"info","message":"[lavalava] peter (118.211.27.66) joined server namespace","timestamp":"2015-07-12T07:58:25.548Z"}
{"level":"info","message":"[modded] peter (118.211.27.66) joined server namespace","timestamp":"2015-07-12T07:58:25.550Z"}
{"level":"info","message":"[lavalava] transmittting existing file contents: logs/latest.log (10912 bytes)","timestamp":"2015-07-12T07:58:25.925Z"}
{"level":"info","message":"[modded] 118.211.27.66 issued command : \"modify_sc\"","timestamp":"2015-07-12T07:59:13.294Z"}
{"level":"info","message":"[modded] received request \"modify_sc\"","timestamp":"2015-07-12T07:59:13.295Z"}
{"level":"info","message":"[modded] 118.211.27.66 issued command : \"start\"","timestamp":"2015-07-12T07:59:20.892Z"}
{"level":"info","message":"[modded] received request \"start\"","timestamp":"2015-07-12T07:59:20.893Z"}
{"level":"info","message":"[modded] latest.log created! Watchfile logs/latest.log closed","timestamp":"2015-07-12T07:59:22.691Z"}
{"level":"info","message":"[modded] Created tail on logs/latest.log","timestamp":"2015-07-12T07:59:22.691Z"}
{"level":"info","message":"[modded] eula.txt detected: NOT YET ACCEPTED (eula=false)","timestamp":"2015-07-12T07:59:35.822Z"}
{"level":"info","message":"[modded] 118.211.27.66 issued command : \"accept_eula\"","timestamp":"2015-07-12T07:59:37.962Z"}
{"level":"info","message":"[modded] received request \"accept_eula\"","timestamp":"2015-07-12T07:59:37.972Z"}
{"level":"info","message":"[modded] eula.txt detected: ACCEPTED (eula=true)","timestamp":"2015-07-12T07:59:38.235Z"}
{"level":"info","message":"[modded] 118.211.27.66 issued command : \"start\"","timestamp":"2015-07-12T07:59:42.102Z"}
{"level":"info","message":"[modded] received request \"start\"","timestamp":"2015-07-12T07:59:42.103Z"}
{"level":"info","message":"[modded] 118.211.27.66 issued command : \"stuff\"","timestamp":"2015-07-12T08:13:12.610Z"}
{"level":"info","message":"[modded] received request \"stuff\"","timestamp":"2015-07-12T08:13:12.611Z"}
{"level":"info","message":"[WEBUI] peter connected from 118.211.27.66","timestamp":"2015-07-12T08:30:50.968Z"}
{"level":"info","message":"[lavalava] peter (118.211.27.66) joined server namespace","timestamp":"2015-07-12T08:31:19.982Z"}
{"level":"info","message":"[modded] peter (118.211.27.66) joined server namespace","timestamp":"2015-07-12T08:31:19.999Z"}
{"level":"info","message":"[modded] transmittting existing file contents: logs/latest.log (6280 bytes)","timestamp":"2015-07-12T08:31:20.637Z"}
{"level":"info","message":"[lavalava] transmittting existing file contents: logs/latest.log (16554 bytes)","timestamp":"2015-07-12T08:31:20.653Z"}
{"level":"info","message":"[modded] 118.211.27.66 issued command : \"stop\"","timestamp":"2015-07-12T08:31:43.163Z"}
{"level":"info","message":"[modded] received request \"stop\"","timestamp":"2015-07-12T08:31:43.163Z"}
{"level":"info","message":"[WEBUI] peter connected from 124.169.224.4","timestamp":"2015-07-12T08:34:49.953Z"}
{"level":"info","message":"[lavalava] peter (124.169.224.4) joined server namespace","timestamp":"2015-07-12T08:35:07.108Z"}
{"level":"info","message":"[modded] peter (124.169.224.4) joined server namespace","timestamp":"2015-07-12T08:35:07.109Z"}
{"level":"info","message":"[lavalava] transmittting existing file contents: logs/latest.log (20423 bytes)","timestamp":"2015-07-12T08:35:12.553Z"}
{"level":"info","message":"[modded] transmittting existing file contents: logs/latest.log (6712 bytes)","timestamp":"2015-07-12T08:35:12.555Z"}

**Comment by hexparrot** [comment]
Question, what kind of server are you running, and what file does it actually produce logs to?

**Comment by flareofghast** [comment]
Ubuntu 14.04.2 /var/log/mineos.log

Followed my guide. I'll delete mineos and re-download and run again. 
Where is server.log supposed to exist? /var/games/minecraft/servers/myserver/?

**Comment by hexparrot** [comment]
Well, 'server.log' is used for older server software, such as vanilla and bukkit from the olden days.  'logs/latest.log' is used by more modern ones.  The webui only displays something when the file is there, and by the look of it, it looks like it's 'logs/latest.log', so you shouldn't be expecting anything to be showing up for the server.log file, after all.

**Comment by flareofghast** [comment]
Ahhh. I am using 1.8.7 so I guess that solves it. What version would use server.log?
Is it a wise design to have both displayed? Maybe an Ng-if="latest.log" or something?

**Comment by hexparrot** [comment]
It's possible--and at one point it was actually like that.  The problem was that various alternatives to vanilla/FTB don't use either, and I'm not sure all of the ones that could be in use.  And if it only displays when it's found, it also makes direct access to the console via the web-ui impossible.

Ultimately, I'll probably make it so if zero logs are identified, a new panel becomes available, one simply called "server console" or something, but that's still ahead.

**Comment by flareofghast** [comment]
Another idea is to make it say MC uses server.log or MC uses latest.log respectively in each page if it's not detected. (Haven't looked at latest commit).
