### ISSUE TITLE
Show larger unit of disk space in webui

### ISSUE THREAD

**Issue by MrBretze** [hexparrot/mineos-node#77]
Please convert kb to gb ?
(http://puu.sh/j8FJh/b57c5c8554.png)

**Comment by TheDoctorsLife** [comment]
or even MB?

**Comment by gh0st19** [comment]
I agree MB would be cool.

**Comment by hexparrot** [comment]
Yeah, MB would be the preferred unit to change to.  Right now though the kb value is the exact string value reported from the linux kernel via `/proc`, so it worked OK as a placeholder.  But I'll probably move it to MB.

**Comment by gh0st19** [comment]
You could use free -m instead of meminfo  if that would parse the output
correctly

**Comment by hexparrot** [comment]
Addressed in #111
