### ISSUE TITLE
latest.log

### ISSUE THREAD

**Issue by flareofghast** [hexparrot/mineos-node#78]
How often is the latest.log checked for updates? When I last looked at it, it was 20mins behind. I was trying to get some info on why my server wasn't starting. Then the next time I went to it it was all up to date.

**Comment by hexparrot** [comment]
Hrm, there shouldn't be any reason it lags behind.  The module that tails the logfiles doesn't operate on an arbitrary X ms interval: https://nodejs.org/docs/latest/api/fs.html#fs_fs_watch_filename_options_listener

It should *never* take 20 minutes, at any point, unless something is wrong.  According to the documentation, cross-platform inter-operability will differ slightly in implementation, but it still shouldn't ever wait 20 minutes.  What is your target system?

**Comment by flareofghast** [comment]
This one is running Ubuntu. 
Maybe it hadn't started writing to the log when I looked at it and the 20 minute lag was the last message.
It just seemed odd that I had recently clicked start but didn't have anything showing up for what seemed longer then it should have.
