### ISSUE TITLE
Spigot Profile

### ISSUE THREAD

**Issue by BlameDylan** [hexparrot/mineos-node#81]
Hello Everyone,
It would be extremely cool if we could have a spigot profile. I know spigot doesn't release official downloads, but have you had a look at [http://getspigot.org/spigot/](http://getspigot.org/spigot/)? It seems cool, and I would appreciate if this was added in at the earliest connivence.

**Thank you, and have a good day!**

**Comment by hexparrot** [comment]
I'd add this if it were current--looks like all of these are 1.7.10.

I was under the impression that it is expressly illegal to distribute fully working copies of Spigot (at least newer versions), and that building them was a requirement.

If you can find any sources to the contrary (and better, binaries to legal, current versions of Spigot), I can add this no problem.

**Comment by BlameDylan** [comment]
You can checkout [Yive's Mirror](http://tcpr.ca/spigot), it looks like it was updated today. **On the other hand,** you could make a spigot compiler although this would be a lot of work.

**Comment by BlameDylan** [comment]
As far as the licenesing issue goes, Spigot is GNU GPL v3, which means your allowed to distribute it. However, it is builds before the the DMCA that are illegal to use/download.

I'm pretty sure that any builds after 	September 5, 2014 are okay.

**Comment by hexparrot** [comment]
From what I've seen over the past week, Spigot is legal insofar that you use buildtools.jar, which downloads the requisite official jar and joins them together.  However, the link you've provide for Yive's mirror seems to do this step for you, putting it in what I think is illegal territory.  Of course, MineOS won't prevent you from using this--it's quite possible, simply by downloading the jar yourself and placing it in the servers 'live' directory, but linking to it from within the webui is a gray area at best, and unnecessary legal risk at worst.

Getting it working was a single wget command, but I think that Spigot can't get worked into the webui in this form.
