### ISSUE TITLE
Environment variables for startup scripts

### ISSUE THREAD

**Issue by arocnies** [hexparrot/mineos-node#82]
Currently the upstart startup script uses an absolute path for the MineOS home directory (*/usr/games/minecraft*). If the user does not want to use this directory, he must edit the startup script.

I would like this to be replaced with an environment variable. If the job fails to start because of an invalid path, the error message should inform the user.

**Comment by hexparrot** [comment]
I've been grappling with this for a while now and I'm trying to find a way that making such a change wouldn't cause more room for error for a greater number of users.

For example, consider a basic Ubuntu Server installation.  A user--by default--logs in with an unprivileged user, such as ```will```.  Then, the user escalates with ```su``` and tries to run the webui.

More likely than not, this will cause an error on account of ```su``` not carrying over the same environment variables that ```su -``` has.  And to ensure that the environmental variables are valid, the admin has to ensure it is set in ```/~/.bashrc``` or ```/etc/profile.d```, both of which are non-standard across different distributions.

I'm under the impression that diagnosing and setting environmental variables would be more difficult for the most novice users, compared to the cost of more seasoned admins changing path in the startup script once.  For the most part, I'd expect well over 99% of users to be using ```/usr/games/minecraft```, and those who wish to use a different path only have the following to do:

a) one time change the upstart script when adding it to ```/etc/init/````
OR
b) create a symlink from ```/usr/games/minecraft``` to their desired directory.

Seeing as how there is no environmental variable set thus far, that is one step--the same one step that could also be one of the above options--perhaps I'm just missing it though: what is the biggest benefit offered by replacing a simple line edit with an environmental variable?

**Comment by arocnies** [comment]
I see your point. I'll do some digging to see if there's other potential options.

**Comment by hexparrot** [comment]
I think that a symlink will be the least invasive, most future-proof way to handle this.  If the /usr/games/minecraft path is symlinked, you can still continue to use updates that expect that path, as well as init updates that you may copy over in the future.

Can you think of anything right off that makes this symlink option insufficient for your needs?
