### ISSUE TITLE
new installation - created server, started, played a little, tried to create second server - not in webui

### ISSUE THREAD

**Issue by flareofghast** [hexparrot/mineos-node#87]
As the title suggests I have created one server, played it a bit and then come back to the UI to create a new server.

first server is theBoys second is boysCreative.

````
{"level":"info","message":"[theBoys] Created tail on logs/latest.log","timestamp":"2015-08-22T06:10:16.022Z"}
{"command":"create","server_name":"boysCreative","properties":{"level-name":"creative","level-seed":"lblkvbhl23hrflj23h;iydED@","difficulty":"2","gamemode":"1","generate-structures":true},"level":"info","message":"[WEBUI] Received emit command from 192.168.1.176:peter","timestamp":"2015-08-22T06:30:04.660Z"}
{"level":"info","message":"[boysCreative] Server created in filesystem.","timestamp":"2015-08-22T06:30:04.675Z"}
{"level":"info","message":"[boysCreative] Discovered server","timestamp":"2015-08-22T06:30:05.078Z"}
````

It's now been several minutes and still not displaying in the UI.

**Comment by flareofghast** [comment]
reloading the page, fixed this issue.
I also noticed that the forms keep the same values from the last server creation.

**Comment by hexparrot** [comment]
The server detection mechanism works with an npm module that gets triggered on newly added or changed directories in /var/games/minecraft/servers.  If for whatever reason the module fails to detect it--which I have seen before, but have not ever been able to consistently reproduce, before refreshing the page, try the 'refresh server list' option in the webui.

Located in the upper right corner, by click on your username, you can have the server list refreshed which should be a more dependable means of ensuring all appropriately owned servers appear.
