### ISSUE TITLE
Cron issues

### ISSUE THREAD

**Issue by thesymbol** [hexparrot/mineos-node#91]
If you enter an invalid cron expression on a server and try to start it, the mineos-node process gets killed without any error message (even with -D).
Some check for validating the cron expression would be a good solution.
And another minor thing about the cron interface is that you have to manually refresh your browser, since the page do not auto-update when you click submit/start/etc.

**Comment by hexparrot** [comment]
I'm looking into this now.  Though, to be comprehensive, provide the example you used specifically that crashed it, so that it can be tested.

**Comment by thesymbol** [comment]
I tried to enter this as cron expression:
```0 0 12 1/1 * ? *```
and ones i hit start the mineos process exits.
although i have not used cron that much so im not 100% sure what the correct format is.
but im guessing this is the correct one to use since you select the task to run in the web interface of mineos:
```0 0 12 1/1 *```
and it does not crash the mineos process.

and also im having trouble that the cron tasks are not being run as they should, i have tried to send a command to minecraft every minute with ```say test``` as the argument for the command, but nothing happens cron for that is:
```0 0/1 * 1/1 *```

Correct me if im wrong with the cron expressions.

**Comment by hexparrot** [comment]
Cron is based off this npm module: https://www.npmjs.com/package/cron

It expects 6 time values (with compatibility for 5) to accommodate seconds.

**Comment by hexparrot** [comment]
Update your git scripts for #93.  I still have to make the webui indicate to the user that the cron expression is bad, but now it will no longer allow you to start a cron with a bad expression--it will auto disable it.

I'll be adding a top-right corner notice as well as probably adding help text real soon.  Let me know if this fixes the problem for you; it seemed to hold up just fine on my initial testing.

**Comment by thesymbol** [comment]
Sounds great, i do not know if you have done any work on FreeBSD crontab.
since i cannot get the cron tasks to run, (i checked the crontab -e but nothing is there, but there is information in the cron.config in the server folder).

**Comment by hexparrot** [comment]
Damn.  Didn't even think about that...so are you doing this all on FreeBSD?  If so, can you create a new issue for that?  I want to handle the "cron not working" in this issue (which I'm pretty much only testing on Linux), and then I'll have to tackle the FreeBSD one next.

**Comment by thesymbol** [comment]
ok i will.
