### ISSUE TITLE
profile is downloaded to /var/games/minecraft regardless of base_directory setting

### ISSUE THREAD

**Issue by josh4trunks** [hexparrot/mineos-node#96]
I noticed mineos-node was downloading to /var/games/minecraft even after setting base_directory to /mnt/minecraft. After the jar is downloaded, mineos doesn't show it as so, because I believe it is looking in /mnt/minecraft/profiles.

**Comment by hexparrot** [comment]
I corrected some errant hardcoded `/var/games/minecraft` that existed in the profile code and I checked the rest of the codebase and I think that is the last of *that* poor practice.

**Comment by josh4trunks** [comment]
Everything  seems to be working now.
Thanks!
